Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2018-11, with the labels that each got.

#777 Adds Speech-to-Speech Translation Sample.
  .kokoro/functions/speech-to-speech.cfg
  functions/speech-to-speech/.gcloudignore
  functions/speech-to-speech/.nvmrc
  functions/speech-to-speech/README.md
  functions/speech-to-speech/index.js
  functions/speech-to-speech/package.json
  functions/speech-to-speech/test/index.test.js
  functions/speech-to-speech/test/request-body.json
  functions/speech-to-speech/test/sample.integration.http.test.js
  functions/speech-to-speech/test/speech-recording.b64
  functions/speech-to-speech/test/speech-recording.wav
  functions/speech-to-speech/test/updateFunctions.sh
Labels: cla: yes

#815 NodeJS 6 code sample for Cloud Function to start/stop GCE instances
  .kokoro/functions/scheduleinstance.cfg
  functions/scheduleinstance/README.md
  functions/scheduleinstance/index.js
  functions/scheduleinstance/package.json
  functions/scheduleinstance/test/index.test.js
Labels: cla: yes

#798 Node 8: add Firestore reactive sample
  functions/node8/index.js
  functions/node8/package.json
  functions/node8/test/index.test.js
Labels: cla: yes

#819 Add [region tags for] Node 8 background snippets
  functions/node8/index.js
  functions/node8/test/index.test.js
Labels: cla: yes, needs review

#823 Fix test failure due to merge issue
  functions/node8/test/index.test.js
Labels: cla: yes

#820 Update functions/scheduleinstance code sample with PubSub functions & unit tests
  functions/scheduleinstance/index.js
  functions/scheduleinstance/package.json
  functions/scheduleinstance/test/index.test.js
Labels: cla: yes

#822 Add Node version clarification comments
  functions/imagemagick/index.js
  functions/log/index.js
Labels: cla: yes

#821 OCR sample: add cross-version support
  functions/ocr/app/index.js
  functions/ocr/app/package.json
  functions/ocr/app/test/index.test.js
Labels: cla: yes, needs review

#826 Use image with Node 8 for kokoro jobs
  .kokoro/common.cfg
  auth/system-test/auth.test.js
Labels: cla: yes

#801 Add Cloud Healthcare API alpha datasets samples and tests
  .kokoro/healthcare-datasets.cfg
  healthcare/datasets/README.md
  healthcare/datasets/datasets.js
  healthcare/datasets/package.json
  healthcare/datasets/system-test/datasets.test.js
Labels: cla: yes

#829 Fix security vulnerability
  .kokoro/appengine/node10/memcached.cfg
  .kokoro/appengine/node6/memcached.cfg
  .kokoro/appengine/node8/memcached.cfg
  appengine/memcached/package.json
Labels: cla: yes

#830 Update repo tools
  package-lock.json
  package.json
Labels: cla: yes

#764 functions: method not implemented should use 405
  functions/http/index.js
  functions/http/test/index.test.js
Labels: automerge, cla: yes

#818 Updated all App Engine standard samples to use Node.js 10 runtime.
  appengine/analytics/app.standard.yaml
  appengine/building-an-app/build/app.yaml
  appengine/building-an-app/update/app.yaml
  appengine/datastore/app.standard.yaml
  appengine/errorreporting/app.standard.yaml
  appengine/headless-chrome/app.yaml
  appengine/hello-world/standard/app.yaml
  appengine/loopback/app.standard.yaml
  appengine/mailjet/app.standard.yaml
  appengine/memcached/app.standard.yaml
  appengine/metadata/standard/app.yaml
  appengine/mongodb/app.standard.yaml
  appengine/parse-server/app.standard.yaml
  appengine/pubsub/app.standard.yaml
  appengine/redis/app.standard.yaml
  appengine/sendgrid/app.standard.yaml
  appengine/static-files/app.standard.yaml
  appengine/storage/standard/app.yaml
  appengine/twilio/app.standard.yaml
  appengine/typescript/app.yaml
  appengine/uglifyjs/app.yaml
Labels: cla: yes

#827 Delete empty folders
  bigquery/README.md
  computeengine/README.md
  datastore/README.md
  dlp/README.md
  dns/README.md
  logging/README.md
  monitoring/README.md
  pubsub/README.md
  resource/README.md
  spanner/README.md
  speech/README.md
  storage/README.md
  translate/README.md
  video/README.md
  vision/README.md
Labels: cla: yes

#835 Add Healthcare API Fhir sample
  healthcare/fhir/README.md
  healthcare/fhir/fhir_resources.js
  healthcare/fhir/fhir_stores.js
  healthcare/fhir/package.json
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
Labels: cla: yes

#837 Remove unused region tags
  functions/tips/index.js
Labels: cla: yes

#816 Fix XSS issue
  functions/helloworld/index.js
  functions/helloworld/package.json
  functions/helloworld/test/index.test.js
  functions/http/index.js
  functions/http/package.json
  functions/http/test/index.test.js
Labels: cla: yes, needs review

#861 Replace call to repo-tools lint
  appengine/analytics/package.json
  appengine/cloudsql/package.json
  appengine/cloudsql_postgresql/package.json
  appengine/datastore/package.json
  appengine/endpoints/package.json
  appengine/errorreporting/package.json
  appengine/headless-chrome/package.json
  appengine/hello-world/flexible/package.json
  appengine/hello-world/standard/package.json
  appengine/mailjet/package.json
  appengine/metadata/flexible/package.json
  appengine/metadata/standard/package.json
  auth/package.json
  containerengine/hello-world/package.json
  debugger/package.json
  endpoints/getting-started-grpc/package.json
  endpoints/getting-started/package.json
  error-reporting/package.json
  functions/background/package.json
  functions/billing/package.json
  functions/composer-storage-trigger/package.json
  functions/concepts/package.json
  functions/datastore/package.json
  functions/env_vars/package.json
  functions/firebase/package.json
  functions/gcs/package.json
  functions/headless-chrome/package.json
  functions/helloworld/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/scheduleinstance/package.json
  functions/sendgrid/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/speech-to-speech/package.json
  functions/sql/package.json
  functions/tips/package.json
  functions/uuid/package.json
  iot/http_example/package.json
  iot/manager/package.json
  iot/mqtt_example/package.json
  jobs/cjd_sample/package.json
  kms/package.json
  language/slackbot/package.json
  package.json
  storage-transfer/package.json
  trace/package.json
Labels: cla: yes

#854 Remove unused HTTP functions from scheduleinstance code sample
  functions/scheduleinstance/README.md
  functions/scheduleinstance/index.js
  functions/scheduleinstance/test/index.test.js
Labels: cla: yes

#838 Healthcare API alpha DICOM samples and tests
  healthcare/dicom/README.md
  healthcare/dicom/dicom_stores.js
  healthcare/dicom/dicomweb.js
  healthcare/dicom/package.json
  healthcare/dicom/resources/IM-0002-0001-JPEG-BASELINE-edited.dcm
  healthcare/dicom/resources/IM-0002-0001-JPEG-BASELINE.dcm
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
Labels: cla: yes

#864 Update repo-tools to 3.0
  appengine/analytics/package.json
  appengine/cloudsql/package.json
  appengine/cloudsql_postgresql/package.json
  appengine/datastore/package.json
  appengine/endpoints/package.json
  appengine/errorreporting/package.json
  appengine/headless-chrome/package.json
  appengine/static-files/package.json
  auth/package.json
  debugger/package.json
  error-reporting/package.json
  functions/background/package.json
  functions/datastore/package.json
  functions/env_vars/package.json
  functions/gcs/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/pubsub/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/tips/package.json
  functions/uuid/package.json
  iot/http_example/package.json
  iot/manager/package.json
  iot/mqtt_example/package.json
  jobs/cjd_sample/package.json
  kms/package.json
  language/slackbot/package.json
  storage-transfer/package.json
  trace/package.json
Labels: cla: yes

#840 Delete build badge for CircleCi
  README.md
Labels: cla: yes

#869 Delete yarn instructions
  CONTRIBUTING.md
  README.md
  appengine/README.md
  appengine/analytics/README.md
  appengine/datastore/README.md
  appengine/grunt/yarn.lock
  appengine/hello-world/flexible/README.md
  appengine/hello-world/standard/README.md
  containerengine/hello-world/README.md
  debugger/README.md
  error-reporting/README.md
  iot/mqtt_example/yarn.lock
  iot/scripts/yarn.lock
  iot/yarn.lock
  jobs/cjd_sample/README.md
  kms/README.md
  package.json
  storage-transfer/README.md
  trace/README.md
Labels: cla: yes

#872 Delete unused files
  .travis.yml
  CONTRIBUTORS
  cloudtasks/README.md
  key.json.enc
Labels: cla: yes

#870 Delete scripts folder
  package.json
  scripts/build
  scripts/clean
  scripts/generate
  scripts/update-dependencies.sh
Labels: cla: yes

#874 Remove empty App Engine tutorials
  appengine/bower/README.md
  appengine/cloudtasks/README.md
  appengine/express-memcached-session/README.md
  appengine/express/README.md
  appengine/extending-runtime/README.md
  appengine/geddy/README.md
  appengine/hapi/README.md
  appengine/koa/README.md
  appengine/kraken/README.md
  appengine/mailgun/README.md
  appengine/restify/README.md
  appengine/sails/README.md
  appengine/webpack/README.md
Labels: cla: yes

#880 Update jobs sample
  jobs/cjd_sample/package.json
  jobs/cjd_sample/quickstart.js
Labels: cla: yes

#882 Simplify auth in kms sample
  kms/keys.js
  kms/package.json
  kms/quickstart.js
Labels: cla: yes

#883 Delete grunt sample
  .kokoro/appengine/node10/grunt.cfg
  .kokoro/appengine/node6/grunt.cfg
  .kokoro/appengine/node8/grunt.cfg
  appengine/grunt/.gitignore
  appengine/grunt/.jshintrc
  appengine/grunt/Gruntfile.js
  appengine/grunt/README.md
  appengine/grunt/app.yaml
  appengine/grunt/package.json
  appengine/grunt/src/app.js
  appengine/grunt/src/bin/www
  appengine/grunt/src/public/stylesheets/style.css
  appengine/grunt/src/routes/index.js
  appengine/grunt/src/routes/users.js
  appengine/grunt/src/views/error.pug
  appengine/grunt/src/views/index.pug
  appengine/grunt/src/views/layout.pug
Labels: cla: yes

#779 GCF: Add Node 8 background function samples
  functions/background/index.js
  functions/background/package.json
  functions/background/test/index.test.js
  functions/node8/index.js
  functions/node8/package.json
  functions/node8/test/index.test.js
Labels: cla: yes

#881 Cloud Healthcare API alpha HL7v2 samples and tests
  healthcare/hl7v2/README.md
  healthcare/hl7v2/hl7v2_messages.js
  healthcare/hl7v2/hl7v2_stores.js
  healthcare/hl7v2/package.json
  healthcare/hl7v2/resources/hl7v2-sample-ingest.json
  healthcare/hl7v2/system-test/hl7v2_messages.test.js
  healthcare/hl7v2/system-test/hl7v2_stores.test.js
Labels: cla: yes, kokoro:run

#888 Fix the failed Kokoro test.
  .kokoro/build-with-appengine.sh
Labels: cla: yes

#891 HelloHTTP: Make Node 8 XSS-safe + add POST support
  functions/helloworld/index.js
  functions/helloworld/test/index.test.js
  functions/node8/.gcloudignore
  functions/node8/index.js
  functions/node8/package.json
  functions/node8/test/index.test.js
Labels: cla: yes

#900 Deprecate Node6 tests
  .kokoro/appengine/node6/analytics.cfg
  .kokoro/appengine/node6/building-an-app-build.cfg
  .kokoro/appengine/node6/building-an-app-update.cfg
  .kokoro/appengine/node6/cloudsql.cfg
  .kokoro/appengine/node6/cloudsql_postgresql.cfg
  .kokoro/appengine/node6/common.cfg
  .kokoro/appengine/node6/datastore.cfg
  .kokoro/appengine/node6/endpoints.cfg
  .kokoro/appengine/node6/errorreporting.cfg
  .kokoro/appengine/node6/headless-chrome.cfg
  .kokoro/appengine/node6/hello-world-flexible.cfg
  .kokoro/appengine/node6/hello-world-standard.cfg
  .kokoro/appengine/node6/loopback.cfg
  .kokoro/appengine/node6/mailjet.cfg
  .kokoro/appengine/node6/metadata-flexible.cfg
  .kokoro/appengine/node6/metadata-standard.cfg
  .kokoro/appengine/node6/mongodb.cfg
  .kokoro/appengine/node6/parse-server.cfg
  .kokoro/appengine/node6/pubsub.cfg
  .kokoro/appengine/node6/redis.cfg
  .kokoro/appengine/node6/sendgrid.cfg
  .kokoro/appengine/node6/static-files.cfg
  .kokoro/appengine/node6/storage-flexible.cfg
  .kokoro/appengine/node6/storage-standard.cfg
  .kokoro/appengine/node6/twilio.cfg
  .kokoro/appengine/node6/typescript.cfg
  .kokoro/appengine/node6/uglifyjs.cfg
Labels: cla: yes

#904 Delete tests for samples moving to different repos
  .kokoro/appengine/node10/errorreporting.cfg
  .kokoro/appengine/node8/errorreporting.cfg
  .kokoro/healthcare-datasets.cfg
Labels: cla: yes

#905 Fix failing tests
  .kokoro/error-reporting.cfg
  appengine/mailjet/package.json
  appengine/pubsub/app.js
  appengine/pubsub/package.json
Labels: cla: yes

#770 Fix functions/billing on Kokoro
  .kokoro/functions/billing.cfg
  functions/billing/index.js
  functions/billing/package.json
  functions/billing/test/index.test.js
Labels: cla: yes, do not merge

#909 Skip unit and integration tests for broken functions/helloworld
  functions/helloworld/package.json
Labels: cla: yes

#912 Update version tags for error-reporting
  error-reporting/snippets.js
Labels: cla: yes

#911 Adds updated Cloud SDK instructions
  iot/README.md
Labels: cla: yes

#921 Delete error-reporting samples
  appengine/errorreporting/README.md
  appengine/errorreporting/app.flexible.yaml
  appengine/errorreporting/app.js
  appengine/errorreporting/app.standard.yaml
  appengine/errorreporting/package.json
  appengine/errorreporting/test/app.test.js
  error-reporting/README.md
  error-reporting/package.json
  error-reporting/snippets.js
  error-reporting/system-test/snippets.test.js
Labels: cla: yes

#936 Delete unused variable in ocr
  functions/ocr/app/config.default.json
  functions/ocr/app/test/index.test.js
Labels: cla: yes

#927 GCF: Add Firebase remote config samples
  functions/firebase/index.js
  functions/firebase/test/index.test.js
  functions/node8/index.js
  functions/node8/test/index.test.js
Labels: cla: yes, needs review

#957 Delete samples for Trace
  .kokoro/trace.cfg
Labels: cla: yes

#893 Fix .blur call to add both parameters
  functions/imagemagick/index.js
Labels: cla: yes

#990 Delete edited file
  healthcare/dicom/resources/IM-0002-0001-JPEG-BASELINE-edited.dcm
Labels: cla: yes

#991 Delete file
  healthcare/dicom/resources/IM-0002-0001-JPEG-BASELINE.dcm
Labels: cla: yes
