Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2018-08, with the labels that each got.

#627 Fix busboy sample not working on GCF
  functions/http/index.js
Labels: GCF Docs, cla: yes, do not merge

#703 Remove tasks samples
  .kokoro/cloudtasks.cfg
  cloudtasks/README.md
  cloudtasks/package.json
  cloudtasks/system-test/tasks.test.js
  cloudtasks/tasks.js
Labels: cla: yes

#707 Fixing GCE deployment script for Cloud Memorystore
  memorystore/redis/gce_deployment/deploy.sh
  memorystore/redis/gce_deployment/startup-script.sh
Labels: cla: yes

#708 [KMS] Generalizing KMS samples for GCS docs
  kms/keys.js
Labels: cla: yes

#704 headless chrome tests: remove unappropriated warning
  appengine/headless-chrome/test/app.test.js
Labels: cla: yes

#711 Add ExpressJS links
  functions/helloworld/index.js
Labels: cla: yes

#712 Remove LabelCat example
  README.md
Labels: cla: yes, do not merge

#700 Add GCS package to functions/http
  functions/http/package.json
Labels: cla: yes

#713 Fix busboy + GCF race condition
  functions/http/index.js
Labels: cla: yes

#709 update region tags
  appengine/analytics/app.flexible.yaml
  appengine/analytics/app.js
  appengine/analytics/app.standard.yaml
  appengine/cloudsql/app.flexible.yaml
  appengine/cloudsql/app.standard.yaml
  appengine/cloudsql/createTables.js
  appengine/cloudsql/server.js
  appengine/cloudsql_postgresql/app.flexible.yaml
  appengine/cloudsql_postgresql/app.standard.yaml
  appengine/cloudsql_postgresql/createTables.js
  appengine/cloudsql_postgresql/server.js
  appengine/datastore/app.flexible.yaml
  appengine/datastore/app.js
  appengine/datastore/app.standard.yaml
  appengine/hello-world/flexible/app.js
  appengine/hello-world/flexible/app.yaml
  appengine/hello-world/standard/app.js
  appengine/mailjet/app.flexible.yaml
  appengine/mailjet/app.js
  appengine/mailjet/app.standard.yaml
  appengine/memcached/app.flexible.yaml
  appengine/memcached/app.js
  appengine/memcached/app.standard.yaml
  appengine/pubsub/app.flexible.yaml
  appengine/pubsub/app.js
  appengine/pubsub/app.standard.yaml
  appengine/pubsub/views/index.pug
  appengine/redis/server.js
  appengine/sendgrid/app.flexible.yaml
  appengine/sendgrid/app.js
  appengine/sendgrid/app.standard.yaml
  appengine/static-files/app.flexible.yaml
  appengine/static-files/app.js
  appengine/static-files/app.standard.yaml
  appengine/static-files/public/main.css
  appengine/storage/flexible/app.js
  appengine/storage/flexible/app.yaml
  appengine/storage/standard/app.js
  appengine/storage/standard/app.yaml
  appengine/twilio/app.flexible.yaml
  appengine/twilio/app.js
  appengine/twilio/app.standard.yaml
Labels: cla: yes, do not merge

#697 Node 6: add Firebase snippets
  functions/firebase/index.js
Labels: cla: yes, do not merge

#720 Add license header
  functions/firebase/index.js
Labels: cla: yes

#722 Added sample for Using Environment Variables.
  functions/env_vars/README.md
  functions/env_vars/index.js
  functions/env_vars/package.json
  functions/env_vars/test/index.test.js
Labels: cla: yes

#718 Update Region Tags
  appengine/endpoints/app.js
  appengine/errorreporting/app.flexible.yaml
  appengine/errorreporting/app.js
  appengine/errorreporting/app.standard.yaml
  appengine/grunt/Gruntfile.js
  appengine/grunt/app.yaml
  appengine/grunt/src/routes/index.js
  appengine/hello-world/standard/app.yaml
  appengine/loopback/app.flexible.yaml
  appengine/loopback/app.standard.yaml
  appengine/memcached/app.standard.yaml
  appengine/metadata/flexible/app.yaml
  appengine/metadata/flexible/server.js
  appengine/metadata/standard/app.yaml
  appengine/metadata/standard/server.js
  appengine/mongodb/app.flexible.yaml
  appengine/mongodb/app.standard.yaml
  appengine/mongodb/server.js
  appengine/parse-server/app.flexible.yaml
  appengine/parse-server/app.standard.yaml
  appengine/parse-server/server.js
  appengine/pubsub/app.standard.yaml
  appengine/redis/app.flexible.yaml
  appengine/redis/app.standard.yaml
Labels: cla: yes

#723 Add GCF SQL samples
  functions/sql/index.js
  functions/sql/package.json
  functions/sql/test/index.test.js
Labels: cla: yes

#715 Remove duplicate sample
  functions/http/index.js
  functions/http/test/index.test.js
Labels: cla: yes

#719 Add node8 firebase snippets
  functions/node8/index.js
  functions/node8/package.json
  functions/node8/test/index.test.js
Labels: cla: yes

#725 Update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#716 Composer: Move 'triggering DAGs' sample to GitHub.
  functions/composer-storage-trigger/index.js
  functions/composer-storage-trigger/package.json
Labels: cla: yes

#721 Added sample for handling CORS requests.
  functions/http/index.js
  functions/http/test/index.test.js
Labels: cla: yes

#727 Add linting to Kokoro + deprecate CircleCI
  .kokoro/lint.cfg
  .kokoro/lint.sh
  circle.yml
Labels: cla: yes
