Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2018-09, with the labels that each got.

#730 Fix GCF failures on Kokoro
  .kokoro/build.sh
  .kokoro/lint.sh
  appengine/cloudsql_postgresql/package.json
  functions/helloworld/package.json
  functions/ocr/app/package.json
  functions/slack/package.json
  kms/system-test/keys.test.js
Labels: cla: yes, do not merge

#732 Add error handling to composer GCF trigger sample
  functions/composer-storage-trigger/index.js
  functions/composer-storage-trigger/package.json
  functions/composer-storage-trigger/test/index.test.js
Labels: cla: yes

#728 Memorystore GCE : Replace GCS_APP_LOCATION with GCS_BUCKET_NAME
  memorystore/redis/gce_deployment/deploy.sh
  memorystore/redis/gce_deployment/startup-script.sh
Labels: cla: yes

#729 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#675 Headless Chrome: keep browser alive between requests.
  appengine/headless-chrome/app.js
Labels: cla: yes, do not merge

#735 GCF MySQL samples: use pools instead of connections
  functions/sql/index.js
Labels: cla: yes, do not merge

#736 Iot fix tests
  iot/http_example/system-test/cloudiot_http_example.test.js
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
Labels: cla: yes

#745 Fix link to cloudsql
  appengine/cloudsql/README.md
Labels: cla: yes

#741 Use library in GCF ImageMagick tutorial
  functions/imagemagick/index.js
  functions/imagemagick/package.json
  functions/imagemagick/test/index.test.js
Labels: cla: yes

#740 GCF: Add Stackdriver trigger sample
  functions/log/.gcloudignore
  functions/log/index.js
  functions/log/test/index.test.js
Labels: cla: yes

#742 Make firestore function work for all trigger types
  functions/firebase/index.js
  functions/node8/index.js
Labels: cla: yes

#737 Move Cloud Tasks Samples
  appengine/cloudtasks/README.md
  appengine/cloudtasks/app.flexible.yaml
  appengine/cloudtasks/app.standard.yaml
  appengine/cloudtasks/createTask.js
  appengine/cloudtasks/package.json
  appengine/cloudtasks/server.js
  appengine/cloudtasks/test/createTask.test.js
Labels: cla: yes

#739 Fix helloworld GCF test
  .kokoro/build.sh
  .kokoro/functions/common.cfg
  functions/helloworld/test/sample.integration.pubsub.test.js
Labels: automerge, cla: yes, kokoro:run

#748 Add billing samples (Node 8 ONLY)
  .kokoro/functions/billing.cfg
  functions/billing/.gcloudignore
  functions/billing/index.js
  functions/billing/package.json
  functions/billing/test/index.test.js
Labels: cla: yes
