Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2018-07, with the labels that each got.

#683 Fix failing tests
  .kokoro/appengine/cloudsql-postgresql.cfg
  .kokoro/appengine/pubsub.cfg
  .kokoro/cloudtasks.cfg
  appengine/cloudsql/package.json
  containerengine/hello-world/package.json
  endpoints/getting-started/package.json
  language/slackbot/package.json
Labels: cla: yes

#686 Adds semistandard dependency for kokoro lint
  iot/http_example/package.json
Labels: cla: yes

#688 Sample runner requires tests be named .test.js
  iot/http_example/system-test/cloudiot_http_example.test.js
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
Labels: cla: yes

#684 Check in Cloud Job Discovery quick start
  jobs/cjd_sample/README.md
  jobs/cjd_sample/package.json
  jobs/cjd_sample/quickstart.js
  jobs/cjd_sample/system-test/quickstart.test.js
Labels: cla: yes

#690 GCF: Add Node 8 samples
  functions/README.md
  functions/node8/index.js
  functions/node8/package.json
Labels: GCF Docs, cla: yes

#672 Add `console.error` statement
  functions/log/index.js
Labels: GCF Docs, cla: yes

#623 Add "shim" (mini-emulator) for GCF functions
  functions/helloworld/package.json
  functions/helloworld/shim.js
  functions/helloworld/test/shim.test.js
Labels: GCF Docs, cla: no

#682 Clarify mocking comments
  functions/helloworld/test/sample.unit.http.test.js
Labels: GCF Docs, cla: yes

#694 just adding ':' for log consistency
  functions/helloworld/index.js
Labels: cla: yes

#687 update gcloud command
  appengine/cloudtasks/README.md
Labels: cla: yes

#695 Add (missing) Node 8 unit tests
  functions/node8/package.json
  functions/node8/test/sample.unit.pubsub.test.js
  functions/node8/test/sample.unit.storage.test.js
Labels: GCF Docs, cla: yes

#678 s/errors/Error Reporting/
  functions/helloworld/index.js
Labels: GCF Docs, cla: yes

#677 Update retry samples
  functions/tips/index.js
Labels: GCF Docs, cla: yes

#661 Add code comments to file
  functions/ocr/app/index.js
Labels: GCF Docs, cla: yes

#650 Remove ephemeral agent sample + update region tag
  functions/tips/index.js
Labels: GCF Docs, cla: yes

#628 Tweak HTTP sample comments
  functions/http/index.js
Labels: GCF Docs, cla: yes

#696 Tips: add region tags
  functions/helloworld/index.js
Labels: GCF Docs, cla: yes

#692 Make docstrings consistent; add aliasing to make different event types clear
  functions/node8/index.js
Labels: GCF Docs, cla: yes

#698 Updates client library, cleans up JS, fixes package.js so the tests run
  iot/http_example/package.json
  iot/manager/manager.js
  iot/manager/package.json
  iot/mqtt_example/package.json
Labels: cla: yes
