Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2019-03, with the labels that each got.

#1156 refactor(concepts):ava to mocha
  functions/concepts/package.json
  functions/concepts/test/index.test.js
Labels: automerge, cla: yes

#1153 Refactor(background):ava to mocha
  functions/background/package.json
  functions/background/test/index.test.js
Labels: automerge, cla: yes

#1175 refactor(ocr):ava to mocha
  functions/ocr/app/package.json
  functions/ocr/app/test/index.test.js
Labels: automerge, cla: yes

#1146 refactor(auth): convert ava tests to mocha
  auth/package.json
  auth/system-test/auth.test.js
Labels: cla: yes

#1139 Update all samples to v1alpha2
  healthcare/datasets/datasets.js
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/dicom_stores.js
  healthcare/dicom/dicomweb.js
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/fhir/fhir_resources.js
  healthcare/fhir/fhir_stores.js
  healthcare/hl7v2/hl7v2_messages.js
  healthcare/hl7v2/hl7v2_stores.js
Labels: automerge, cla: yes

#930 Update error logging example
  functions/helloworld/index.js
Labels: automerge, cla: yes

#1192 iot: fix issues with conflicting topics/registries in parallel tests
  iot/manager/system-test/manager.test.js
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
  package.json
Labels: cla: yes

#1183 refactor(appengine-headless-chrome):ava to mocha
  appengine/headless-chrome/package.json
  appengine/headless-chrome/test/app.test.js
Labels: automerge, cla: yes

#1160 refactor(http):ava to mocha
  functions/http/package.json
  functions/http/test/index.test.js
Labels: automerge, cla: yes

#1179 refactor(cloudsql):ava to mocha
  appengine/cloudsql/package.json
  appengine/cloudsql/test/createTables.test.js
  appengine/cloudsql/test/server.test.js
Labels: automerge, cla: yes

#1182 refactor(appengine-storage):ava to mocha
  appengine/storage/flexible/package.json
  appengine/storage/flexible/system-test/app.test.js
  appengine/storage/standard/package.json
  appengine/storage/standard/system-test/app.test.js
Labels: automerge, cla: yes

#1180 refactor(cloudsql_postgresql):ava to mocha
  appengine/cloudsql_postgresql/package.json
  appengine/cloudsql_postgresql/test/createTables.test.js
  appengine/cloudsql_postgresql/test/server.test.js
Labels: automerge, cla: yes

#1165 refactor(spanner):ava to mocha
  functions/spanner/package.json
  functions/spanner/test/index.test.js
Labels: automerge, cla: yes

#1157 refactor(env_vars):ava to mocha
  functions/env_vars/package.json
  functions/env_vars/test/index.test.js
Labels: cla: yes

#1163 refactor(scheduleinstance):ava to mocha
  functions/scheduleinstance/package.json
  functions/scheduleinstance/test/index.test.js
Labels: automerge, cla: yes

#1161 refactor(imagemagick):ava to mocha
  functions/imagemagick/package.json
  functions/imagemagick/test/index.test.js
Labels: automerge, cla: yes

#1159 refactor(headless-chrome):ava to mocha
  functions/headless-chrome/package.json
  functions/headless-chrome/test/index.test.js
Labels: automerge, cla: yes

#1158 refactor(firebase):ava to mocha
  functions/firebase/package.json
  functions/firebase/test/index.test.js
Labels: automerge, cla: yes

#1155 refactor(composer-storage-trigger):ava to mocha
  functions/composer-storage-trigger/package.json
  functions/composer-storage-trigger/test/index.test.js
Labels: automerge, cla: yes

#1177 refactor(sendgrid):ava to mocha
  functions/sendgrid/package.json
  functions/sendgrid/test/index.test.js
Labels: cla: yes

#1194 Delete debugger samples
  .kokoro/debugger.cfg
  debugger/README.md
  debugger/app.js
  debugger/app.yaml
  debugger/package.json
  debugger/snippets.js
Labels: cla: yes

#1148 refactor(healthcare): convert ava tests to mocha
  healthcare/datasets/package.json
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/package.json
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
  healthcare/fhir/package.json
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
  healthcare/hl7v2/package.json
  healthcare/hl7v2/system-test/hl7v2_messages.test.js
  healthcare/hl7v2/system-test/hl7v2_stores.test.js
Labels: cla: yes

#1147 refactor(jobs): convert ava tests to mocha
  jobs/v2/package.json
  jobs/v2/system-test/quickstart.test.js
  jobs/v3/package.json
  jobs/v3/system-test/auto-complete-sample.test.js
  jobs/v3/system-test/basic-company-sample.test.js
  jobs/v3/system-test/basic-job-sample.test.js
  jobs/v3/system-test/batchdelete-jobs-sample.test.js
  jobs/v3/system-test/commute-search-sample.test.js
  jobs/v3/system-test/custom-attribute-sample.test.js
  jobs/v3/system-test/email-alert-search-sample.test.js
  jobs/v3/system-test/featured-job-search-sample.test.js
  jobs/v3/system-test/general-search-sample.test.js
  jobs/v3/system-test/histogram-sample.test.js
  jobs/v3/system-test/location-search-sample.test.js
  jobs/v3/system-test/quickstart.test.js
Labels: cla: yes

#1199 Update Readme for appengine/mongodb
  appengine/mongodb/README.md
Labels: cla: yes, kokoro:run

#814 Add env variable for storage buckets to test configs
  .kokoro/appengine/node10/storage-flexible.cfg
  .kokoro/appengine/node10/storage-standard.cfg
  .kokoro/appengine/node8/storage-flexible.cfg
  .kokoro/appengine/node8/storage-standard.cfg
Labels: cla: yes

#1209 Delete appengine/uglify
  .kokoro/appengine/node10/uglifyjs.cfg
  .kokoro/appengine/node8/uglifyjs.cfg
  appengine/uglifyjs/.gcloudignore
  appengine/uglifyjs/.gitignore
  appengine/uglifyjs/README.md
  appengine/uglifyjs/app.yaml
  appengine/uglifyjs/index.js
  appengine/uglifyjs/package.json
  appengine/uglifyjs/static/.eslintrc.yaml
  appengine/uglifyjs/static/index.html
  appengine/uglifyjs/static/index_min.html
  appengine/uglifyjs/static/message.js
  appengine/uglifyjs/static/style.css
Labels: cla: yes

#1211 Allow minor and patch updates
  appengine/analytics/package.json
  appengine/building-an-app/build/package.json
  appengine/building-an-app/update/package.json
  appengine/cloudsql/package.json
  appengine/cloudsql_postgresql/package.json
  appengine/datastore/package.json
  appengine/endpoints/package.json
  appengine/loopback/package.json
  appengine/mailjet/package.json
  appengine/memcached/package.json
  appengine/metadata/flexible/package.json
  appengine/metadata/standard/package.json
  appengine/mongodb/package.json
  appengine/pubsub/package.json
  appengine/redis/package.json
  appengine/sendgrid/package.json
  appengine/static-files/package.json
  appengine/twilio/package.json
  appengine/websockets/package.json
  auth/package.json
  cloud-sql/mysql/mysql/package.json
  cloud-sql/postgres/knex/package.json
  endpoints/getting-started-grpc/package.json
  endpoints/getting-started/package.json
  iot/beta-features/gateway/package.json
  iot/http_example/package.json
  iot/manager/package.json
  iot/mqtt_example/package.json
  iot/scripts/package.json
  jobs/v3/package.json
  memorystore/redis/package.json
  opencensus/package.json
  storage-transfer/package.json
Labels: cla: yes

#1202 refactor(storage-transfer): convert ava tests to mocha
  storage-transfer/package.json
  storage-transfer/system-test/transfer.test.js
  storage-transfer/test/transfer.test.js
Labels: cla: yes

#1214 Allow minor and patch updates in functions/
  functions/background/package.json
  functions/composer-storage-trigger/package.json
  functions/datastore/package.json
  functions/env_vars/package.json
  functions/errorreporting/package.json
  functions/firebase/package.json
  functions/log/package.json
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/scheduleinstance/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/sql/package.json
  functions/tips/package.json
  functions/uuid/package.json
Labels: cla: yes

#1221 Update Contributor guide
  CONTRIBUTING.md
Labels: cla: yes

#1222 Allow patches of dependencies in functions/sql
  functions/sql/package.json
Labels: cla: yes

#1219 Clean up package.json in root directory
  package.json
Labels: cla: yes

#1223 Fix billing tests always passing
  functions/billing/test/index.test.js
Labels: cla: yes

#1224 refactor(lint): prefer `const` over `var`
  .eslintrc.yml
  appengine/headless-chrome/app.js
  appengine/memcached/app.js
  appengine/metadata/standard/server.js
  appengine/pubsub/app.js
  appengine/typescript/index.ts
  cloud-sql/postgres/knex/server.js
  functions/http/index.js
  functions/log/index.js
  functions/ocr/app/index.js
  functions/ocr/app/test/index.test.js
  functions/sendgrid/test/index.test.js
  functions/speech-to-speech/functions/index.js
  functions/speech-to-speech/functions/test/sample.integration.http.test.js
  iot/beta-features/gateway/gateway.js
  iot/beta-features/gateway/gateway.test.js
  iot/http_example/cloudiot_http_example.js
  iot/manager/manager.js
  iot/manager/system-test/manager.test.js
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
  package.json
Labels: cla: yes

#1225 refactor(appengine-pubsub):ava to mocha
  appengine/pubsub/package.json
  appengine/pubsub/test/app.test.js
Labels: cla: yes

#1226 refactor(lint): enable the `no-var` eslint rule
  .eslintrc.yml
  appengine/loopback/server/server.js
  appengine/mailjet/app.js
  cloud-sql/mysql/mysql/views/index.pug
  containerengine/hello-world/server.js
  functions/composer-storage-trigger/index.js
  functions/imagemagick/test/index.test.js
  iot/beta-features/gateway/gateway.js
  iot/http_example/cloudiot_http_example.js
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
  storage-transfer/system-test/transfer.test.js
  storage-transfer/transfer.js
Labels: cla: yes

#1201 Add sample for OAuth Token via firebase functions
  .kokoro/functions/dialogflow.cfg
  functions/dialogflow/.firebaserc
  functions/dialogflow/firebase.json
  functions/dialogflow/functions/index.js
  functions/dialogflow/functions/package.json
  functions/dialogflow/functions/test/index.test.js
  functions/dialogflow/functions/test/updateFunctions.sh
Labels: cla: yes

#1220 Update Readme in root directory
  README.md
Labels: cla: yes

#1228 refactor(lint): prefer arrow callbacks
  .eslintrc.yml
  appengine/loopback/common/models/message.js
  appengine/loopback/server/server.js
  appengine/mailjet/app.js
  cloud-sql/mysql/mysql/server.js
  functions/composer-storage-trigger/index.js
  functions/dialogflow/functions/test/index.test.js
  functions/http/index.js
  functions/speech-to-speech/functions/index.js
  functions/speech-to-speech/functions/test/index.test.js
  functions/speech-to-speech/functions/test/sample.integration.http.test.js
  healthcare/dicom/dicomweb.js
  healthcare/fhir/fhir_resources.js
  iot/beta-features/gateway/gateway.js
  iot/http_example/cloudiot_http_example.js
  iot/manager/manager.js
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
  opencensus/metrics-quickstart.js
  storage-transfer/transfer.js
Labels: cla: yes

#1230 refactor: move createDataset sample to own file
  healthcare/datasets/createDataset.js
  healthcare/datasets/datasets.js
  healthcare/datasets/system-test/datasets.test.js
Labels: cla: yes
