Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-06, with the labels that each got.

#1837 healthcare API: clarify that server returns 200 on resource deletion …
  healthcare/fhir/deleteFhirResource.js
Labels: automerge, cla: yes

#1836 fix(cloud-sql): update samples to show TCP and Unix Socket connection methods
  .kokoro/build.sh
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql/app.flexible.yaml
  cloud-sql/mysql/mysql/app.standard.yaml
  cloud-sql/mysql/mysql/server.js
  cloud-sql/mysql/mysql/test/server.test.js
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/app.flexible.yaml
  cloud-sql/postgres/knex/app.standard.yaml
  cloud-sql/postgres/knex/createTable.js
  cloud-sql/postgres/knex/server.js
  cloud-sql/postgres/knex/test/createTable.test.js
Labels: cla: yes

#1845 Specify Node.js engine 10 or greater
  functions/speech-to-speech/functions/package.json
Labels: automerge, cla: yes

#1855 chore: test appengine on Node12
  .kokoro/appengine/node12/building-an-app-build.cfg
  .kokoro/appengine/node12/building-an-app-update.cfg
  .kokoro/appengine/node12/cloudsql.cfg
  .kokoro/appengine/node12/cloudsql_postgresql.cfg
  .kokoro/appengine/node12/common.cfg
  .kokoro/appengine/node12/datastore.cfg
  .kokoro/appengine/node12/endpoints.cfg
  .kokoro/appengine/node12/headless-chrome.cfg
  .kokoro/appengine/node12/hello-world-flexible.cfg
  .kokoro/appengine/node12/hello-world-standard.cfg
  .kokoro/appengine/node12/mailjet.cfg
  .kokoro/appengine/node12/memcached.cfg
  .kokoro/appengine/node12/metadata-flexible.cfg
  .kokoro/appengine/node12/metadata-standard.cfg
  .kokoro/appengine/node12/pubsub.cfg
  .kokoro/appengine/node12/redis.cfg
  .kokoro/appengine/node12/sendgrid.cfg
  .kokoro/appengine/node12/static-files.cfg
  .kokoro/appengine/node12/storage-flexible.cfg
  .kokoro/appengine/node12/storage-standard.cfg
  .kokoro/appengine/node12/twilio.cfg
  .kokoro/appengine/node12/typescript.cfg
Labels: cla: yes

#1850 healthcare API: FHIR resources cleanup and bug fixes
  healthcare/fhir/README.md
  healthcare/fhir/createFhirResource.js
  healthcare/fhir/deleteFhirResource.js
  healthcare/fhir/deleteFhirResourcePurge.js
  healthcare/fhir/executeFhirBundle.js
  healthcare/fhir/fhir_resources.js
  healthcare/fhir/patchFhirResource.js
  healthcare/fhir/resources/bundle.json
  healthcare/fhir/searchFhirResourcesGet.js
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/updateFhirResource.js
Labels: automerge, cla: yes

#1856 healthcare API: move binaryData var down so that it works from direct…
  healthcare/dicom/dicomWebStoreInstance.js
Labels: cla: yes

#1857 Update speech sample to use Cloud Speech dependency v4.0.0
  .kokoro/functions/speech-to-speech.cfg
  functions/speech-to-speech/functions/package.json
Labels: automerge, cla: yes

#1861 fix: export xml test results
  .kokoro/appengine/common.cfg
  .kokoro/cloud-tasks/common.cfg
  .kokoro/functions/common.cfg
  .kokoro/iot/common.cfg
  .kokoro/run/common.cfg
Labels: cla: yes

#1864 Removed the App Engine Redis sample
  .kokoro/appengine/node10/redis.cfg
  .kokoro/appengine/node12/redis.cfg
  appengine/redis/.gitignore
  appengine/redis/README.md
  appengine/redis/app.flexible.yaml
  appengine/redis/app.standard.yaml
  appengine/redis/package.json
  appengine/redis/server.js
  appengine/redis/test/server.test.js
Labels: cla: yes

#1867 Fixed region tag in run/events-pubsub/index.js
  run/events-pubsub/index.js
Labels: cla: yes

#1870 Move composer code out of functions folder
  .kokoro/composer/common.cfg
  .kokoro/composer/composer-storage-trigger.cfg
  .kokoro/composer/composer-transform-csv-to-json.cfg
  CODEOWNERS
  composer/functions/composer-storage-trigger/README.md
  composer/functions/composer-storage-trigger/index.js
  composer/functions/composer-storage-trigger/package.json
  composer/functions/composer-storage-trigger/test/index.test.js
Labels: cla: yes

#1863 Use @google-cloud/pubsub v2
  appengine/pubsub/package.json
Labels: automerge, cla: yes

#1871 fix(samples): auth samples used top level await
  auth/auth.js
Labels: cla: yes

#1869 healthcare API: fix create FHIR resource region tag
  healthcare/fhir/createFhirResource.js
Labels: automerge, cla: yes

#1752 Markdown Preview sample
  run/markdown-preview/README.md
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/editor/main.js
  run/markdown-preview/editor/package.json
  run/markdown-preview/editor/render.js
  run/markdown-preview/editor/templates/index.html
  run/markdown-preview/editor/templates/markdown.md
  run/markdown-preview/editor/test/deploy.sh
  run/markdown-preview/editor/test/main.test.js
  run/markdown-preview/editor/test/render.test.js
  run/markdown-preview/editor/test/runner.sh
  run/markdown-preview/editor/test/system.test.js
  run/markdown-preview/editor/test/url.sh
  run/markdown-preview/renderer/Dockerfile
  run/markdown-preview/renderer/main.js
  run/markdown-preview/renderer/package.json
  run/markdown-preview/renderer/test/main.test.js
Labels: cla: yes

#1835 run: use shorter suffix in service names
  .kokoro/build-with-run.sh
  run/hello-broken/s.sh
  run/hello-broken/test/cloudrun-ci.js
  run/hello-broken/test/system.test.js
Labels: api: run, cla: yes, type: bug

#1879 fix Markdown Preview flaky tests
  run/markdown-preview/editor/test/system.test.js
Labels: cla: yes

#1883 fix(cloud-sql): added return statements to fix 'http headers sent' error
  cloud-sql/mysql/mysql/server.js
  cloud-sql/sqlserver/mssql/server.js
Labels: automerge, cla: yes

#1880 Clarify infinite retries example
  functions/tips/index.js
Labels: automerge, cla: yes

#1889 Add region tag "run_secure_request_do"
  run/markdown-preview/editor/main.js
Labels: automerge, cla: yes

#1892 Update NodeJS billing sample code
  functions/billing/index.js
Labels: automerge, cla: yes

#1893 Fix system test
  run/markdown-preview/editor/test/system.test.js
Labels: cla: yes

#1896 Functions: remove node 8 samples
  .kokoro/datastore-functions.cfg
  .kokoro/functions/billing-periodic.cfg
  .kokoro/functions/common.cfg
  .kokoro/functions/imagemagick.cfg
  .kokoro/functions/ocr-app.cfg
  functions/background/package.json
  functions/billing/package.json
  functions/concepts/package.json
  functions/env_vars/package.json
  functions/firebase/package.json
  functions/helloworld/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/memorystore/redis/package.json
  functions/node8/.eslintrc.yml
  functions/node8/.gcloudignore
  functions/node8/index.js
  functions/node8/package.json
  functions/node8/test/index.test.js
  functions/node8/test/sample.unit.pubsub.test.js
  functions/node8/test/sample.unit.storage.test.js
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/scheduleinstance/package.json
  functions/security/package.json
  functions/sendgrid/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/tips/package.json
  functions/tips/test/index.test.js
  functions/tokenservice/functions/package.json
Labels: cla: yes

#1897 chore: update to Node 10 in datastore-functions
  .kokoro/datastore-functions.cfg
Labels: cla: yes

#1898 chore: update to Node 10 in functions/tokenservice
  .kokoro/functions/tokenservice.cfg
Labels: cla: yes

#1884 Adds Run Events GCS Trigger Sample
  run/README.md
  run/events-storage/.dockerignore
  run/events-storage/Dockerfile
  run/events-storage/README.md
  run/events-storage/app.js
  run/events-storage/index.js
  run/events-storage/package.json
  run/events-storage/test/app.test.js
Labels: cla: yes

#1895 chore: update tests to current LTS Node 12
  .kokoro/cloud-tasks/common.cfg
  .kokoro/common.cfg
  .kokoro/composer/common.cfg
  .kokoro/iot/common.cfg
Labels: cla: yes

#1906 run: events region tags
  run/events-pubsub/app.js
  run/events-storage/app.js
Labels: cla: yes
