Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-11, with the labels that each got.

#2040 Fix comment in Dockerfile
  run/helloworld/Dockerfile
Labels: cla: yes

#2042 Update e2e tests for markdown preview
  run/markdown-preview/editor/package.json
  run/markdown-preview/editor/test/deploy.sh
  run/markdown-preview/editor/test/e2e_test_cleanup.yaml
  run/markdown-preview/editor/test/e2e_test_setup.yaml
  run/markdown-preview/editor/test/retry.sh
  run/markdown-preview/editor/test/runner.sh
  run/markdown-preview/editor/test/system.test.js
  run/markdown-preview/editor/test/url.sh
  run/markdown-preview/renderer/package.json
  run/markdown-preview/renderer/test/deploy.sh
  run/markdown-preview/renderer/test/e2e_test_cleanup.yaml
  run/markdown-preview/renderer/test/e2e_test_setup.yaml
  run/markdown-preview/renderer/test/retry.sh
  run/markdown-preview/renderer/test/runner.sh
  run/markdown-preview/renderer/test/system.test.js
  run/markdown-preview/renderer/test/url.sh
Labels: cla: yes

#2043 chore: remove unused dependency in top level
  package.json
Labels: cla: yes

#2045 chore: turn on linting for run/idp-sql
  .eslintignore
  run/idp-sql/.eslintrc.json
  run/idp-sql/handlebars.js
  run/idp-sql/test/system.test.js
Labels: automerge, cla: yes

#2048 Update region tags for Cloud Run
  run/hello-broken/Dockerfile
  run/hello-broken/index.js
  run/hello-broken/s.sh
  run/hello-broken/test/cloudrun-ci.js
  run/helloworld/Dockerfile
  run/helloworld/index.js
  run/idp-sql/cloud-sql.js
  run/idp-sql/middleware.js
  run/idp-sql/secrets.js
  run/idp-sql/static/config.js
  run/idp-sql/static/firebase.js
  run/idp-sql/views/index.html
  run/image-processing/.env
  run/image-processing/Dockerfile
  run/image-processing/app.js
  run/image-processing/image.js
  run/image-processing/index.js
  run/logging-manual/app.js
  run/markdown-preview/editor/app.js
  run/markdown-preview/editor/render.js
  run/markdown-preview/editor/templates/index.html
  run/pubsub/Dockerfile
  run/pubsub/app.js
  run/pubsub/index.js
  run/system-package/Dockerfile
  run/system-package/app.js
Labels: automerge, cla: yes

#2046 Update Run testing
  run/image-processing/package.json
  run/image-processing/test/deploy.sh
  run/image-processing/test/e2e_test_cleanup.yaml
  run/image-processing/test/e2e_test_setup.yaml
  run/image-processing/test/retry.sh
  run/image-processing/test/runner.sh
  run/image-processing/test/system.test.js
  run/image-processing/test/url.sh
  run/image-processing/test/zombie.jpg
Labels: cla: yes

#2052 chore: delete unused variables
  functions/billing/index.js
  functions/billing/test/periodic.test.js
  functions/helloworld/test/index.test.js
  functions/helloworld/test/sample.integration.pubsub.test.js
Labels: automerge, cla: yes

#2050 chore: delete unused functions
  run/idp-sql/.eslintrc.json
  run/idp-sql/logging.js
Labels: api: run, automerge, cla: yes

#2056 chore: replace strictEqual with deepStrictEqual
  functions/security/test/index.test.js
Labels: cla: yes

#2051 chore: fix no-empty lint rule
  appengine/storage/flexible/system-test/.eslintrc.yaml
  appengine/storage/flexible/system-test/app.test.js
  appengine/storage/standard/system-test/.eslintrc.yaml
  appengine/storage/standard/system-test/app.test.js
  healthcare/.eslintrc.yml
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
  healthcare/hl7v2/system-test/hl7v2_messages.test.js
  healthcare/hl7v2/system-test/hl7v2_stores.test.js
  storage-transfer/system-test/transfer.test.js
Labels: cla: yes

#2057 chore: use browser env in eslint rule
  run/idp-sql/.eslintrc.json
  run/idp-sql/static/.eslintrc.json
Labels: cla: yes

#2061 chore: use fetch instead of request
  iot/http_example/cloudiot_http_example.js
  iot/http_example/package.json
Labels: cla: yes

#2063 chore: replace got with node-fetch
  appengine/metadata/flexible/package.json
  appengine/metadata/flexible/server.js
  appengine/metadata/standard/package.json
  appengine/metadata/standard/server.js
Labels: cla: yes

#2064 Add missed region tags
  functions/tips/index.js
  functions/tips/test/index.test.js
Labels: automerge, cla: yes

#2062 chore: delete IoT samples
  .kokoro/iot/common.cfg
  .kokoro/iot/iot-http-example.cfg
  .kokoro/iot/iot-manager.cfg
  .kokoro/iot/iot-mqtt-example.cfg
  iot/README.md
  iot/http_example/README.md
  iot/http_example/cloudiot_http_example.js
  iot/http_example/package.json
  iot/http_example/resources/README.md
  iot/http_example/resources/rsa_cert.pem
  iot/http_example/resources/rsa_private.pem
  iot/http_example/system-test/cloudiot_http_example.test.js
  iot/manager/.gitignore
  iot/manager/README.md
  iot/manager/manager.js
  iot/manager/package.json
  iot/manager/resources/ec_public.pem
  iot/manager/resources/rsa_cert.pem
  iot/manager/system-test/manager.test.js
  iot/mqtt_example/README.md
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
  iot/mqtt_example/package.json
  iot/mqtt_example/resources/README.md
  iot/mqtt_example/resources/rsa_cert.pem
  iot/mqtt_example/resources/rsa_private.pem
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
  iot/scripts/generate_keys.sh
  iot/scripts/iam.js
  iot/scripts/package.json
Labels: automerge, cla: yes

#2069 Update permissions for executable script
  run/idp-sql/setup.sh
Labels: automerge, cla: yes

#2070 chore(functions): remove unused sendgrid sample
  .kokoro/functions/sendgrid.cfg
  functions/sendgrid/.gitignore
  functions/sendgrid/README.md
  functions/sendgrid/config.default.json
  functions/sendgrid/index.js
  functions/sendgrid/package.json
  functions/sendgrid/test/index.test.js
Labels: api: cloudfunctions, cla: yes

#2068 [App Engine] TS : Adding the missing node type definition
  appengine/typescript/package.json
Labels: automerge, cla: yes

#2084 chore: cleanup leftover IoT references
  .kokoro/build.sh
  CODEOWNERS
Labels: cla: yes, kokoro:run, samples
