Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-02, with the labels that each got.

#1597 chore: replace repo tools tools.runAsync function with execSync
  auth/system-test/auth.test.js
  endpoints/getting-started-grpc/system-test/endpoints.test.js
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
  healthcare/hl7v2/system-test/hl7v2_messages.test.js
  healthcare/hl7v2/system-test/hl7v2_stores.test.js
  iot/http_example/system-test/cloudiot_http_example.test.js
  iot/manager/system-test/manager.test.js
  iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
  jobs/v2/system-test/quickstart.test.js
  jobs/v3/system-test/auto-complete-sample.test.js
  jobs/v3/system-test/basic-company-sample.test.js
  jobs/v3/system-test/basic-job-sample.test.js
  jobs/v3/system-test/batchdelete-jobs-sample.test.js
  jobs/v3/system-test/commute-search-sample.test.js
  jobs/v3/system-test/custom-attribute-sample.test.js
  jobs/v3/system-test/email-alert-search-sample.test.js
  jobs/v3/system-test/featured-job-search-sample.test.js
  jobs/v3/system-test/general-search-sample.test.js
  jobs/v3/system-test/histogram-sample.test.js
  jobs/v3/system-test/location-search-sample.test.js
  jobs/v3/system-test/quickstart.test.js
  opencensus/system-test/metrics-quickstart.test.js
Labels: cla: yes

#1600 fix: refactor stubConsole and restoreConsole methods in repo-tools with sinon dependency
  appengine/building-an-app/update/package.json
  appengine/building-an-app/update/test/server.test.js
  appengine/cloudsql/test/createTables.test.js
  appengine/cloudsql/test/server.test.js
  appengine/cloudsql_postgresql/test/createTables.test.js
  appengine/cloudsql_postgresql/test/server.test.js
  appengine/endpoints/test/app.test.js
  endpoints/getting-started/test/app.test.js
  functions/firebase/test/index.test.js
  functions/helloworld/test/index.test.js
  functions/helloworld/test/sample.unit.pubsub.test.js
  functions/helloworld/test/sample.unit.storage.test.js
  functions/http/test/index.test.js
  functions/imagemagick/test/index.test.js
  functions/log/test/index.test.js
  functions/node8/test/index.test.js
  functions/node8/test/sample.unit.pubsub.test.js
  functions/node8/test/sample.unit.storage.test.js
  functions/ocr/app/package.json
  functions/ocr/app/test/index.test.js
  functions/pubsub/package.json
  functions/pubsub/test/index.test.js
  functions/scheduleinstance/test/index.test.js
  functions/sendgrid/test/index.test.js
  functions/slack/test/index.test.js
  functions/tips/test/index.test.js
  storage-transfer/system-test/transfer.test.js
  storage-transfer/test/transfer.test.js
Labels: cla: yes

#1568 Data Catalog: add create fileset Entry sample
  datacatalog/quickstart/createFilesetEntry.js
  datacatalog/quickstart/package.json
  datacatalog/quickstart/system-test/createFilesetEntry.test.js
Labels: cla: yes

#1569 Data Catalog: add delete fileset Entry sample
  datacatalog/quickstart/deleteFilesetEntry.js
  datacatalog/quickstart/system-test/deleteFilesetEntry.test.js
Labels: cla: yes

#1613 Update {dialogflow -> tokenservice} functions CODEOWNERS
  CODEOWNERS
Labels: automerge, cla: yes

#1607 fix: reduce request usage
  functions/background/index.js
  functions/background/package.json
  functions/background/test/index.test.js
Labels: cla: yes

#1606 test: reduce request usage
  datastore/functions/package.json
  datastore/functions/test/index.test.js
Labels: cla: yes, kokoro:run

#1614 Adds projectId to example parameters
  iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
Labels: cla: yes
