Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-08, with the labels that each got.

#1938 refactor(run/markdown-preview): improve local testing and CI flakiness
  .kokoro/build-with-run.sh
  run/README.md
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/editor/app.js
  run/markdown-preview/editor/index.js
  run/markdown-preview/editor/package.json
  run/markdown-preview/editor/render.js
  run/markdown-preview/editor/test/app.test.js
  run/markdown-preview/editor/test/deploy.sh
  run/markdown-preview/editor/test/render.test.js
  run/markdown-preview/editor/test/runner.sh
  run/markdown-preview/editor/test/system.test.js
  run/markdown-preview/renderer/Dockerfile
  run/markdown-preview/renderer/app.js
  run/markdown-preview/renderer/index.js
  run/markdown-preview/renderer/package.json
  run/markdown-preview/renderer/test/app.test.js
Labels: api: run, cla: yes

#1941 fix(run/markdown-preview): region tags should encompass imports
  run/markdown-preview/editor/render.js
Labels: automerge, cla: yes

#1865 Setup tests and applied minor fixes for the App Engine Websockets sample
  .kokoro/appengine/node10/websockets.cfg
  .kokoro/appengine/node12/websockets.cfg
  appengine/websockets/app.js
  appengine/websockets/package.json
  appengine/websockets/test/app.test.js
  appengine/websockets/test/index.test.js
Labels: automerge, cla: yes

#1939 Cloud Run Hello World
  .kokoro/run/helloworld.cfg
  run/README.md
  run/helloworld/.dockerignore
  run/helloworld/.gcloudignore
  run/helloworld/Dockerfile
  run/helloworld/README.md
  run/helloworld/index.js
  run/helloworld/package.json
  run/helloworld/test/deploy.sh
  run/helloworld/test/index.test.js
  run/helloworld/test/runner.sh
  run/helloworld/test/system.test.js
  run/helloworld/test/url.sh
Labels: automerge, cla: yes

#1944 run: update to Node.js 12
  .kokoro/run/common.cfg
  run/events-pubsub/Dockerfile
  run/events-pubsub/package.json
  run/events-storage/Dockerfile
  run/events-storage/package.json
  run/hello-broken/Dockerfile
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/image-processing/package.json
  run/logging-manual/Dockerfile
  run/pubsub/Dockerfile
  run/pubsub/package.json
Labels: cla: yes

#1943 docs(run): Reflow index and remove knative reference
  run/README.md
Labels: api: run, automerge, cla: yes

#1942 fix: standardize run events pub/sub message
  run/events-pubsub/app.js
Labels: cla: yes

#1862 Add Cloud Healthcare API to Kokoro testing pipeline
  .kokoro/healthcare/common.cfg
  .kokoro/healthcare/datasets.cfg
  .kokoro/healthcare/dicom.cfg
  .kokoro/healthcare/fhir.cfg
  .kokoro/healthcare/hl7v2.cfg
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
  healthcare/fhir/exportFhirResources.js
  healthcare/fhir/importFhirResources.js
  healthcare/fhir/resources/fhir_data.ndjson
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
  healthcare/hl7v2/system-test/hl7v2_messages.test.js
  healthcare/hl7v2/system-test/hl7v2_stores.test.js
Labels: cla: yes

#1950 [Cloud Run] Add license to file
  run/markdown-preview/editor/index.js
Labels: automerge, cla: yes

#1961 healthcare API: increase sleep time for FHIR import LRO
  healthcare/fhir/importFhirResources.js
Labels: cla: yes, samples

#1940 chore(functions): remove redundant logging sample
  .kokoro/functions/log.cfg
  functions/log/index.js
  functions/log/package.json
  functions/log/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1963 chore(appengine/analytics): fix outdated got usage
  appengine/analytics/app.js
  appengine/analytics/package.json
Labels: automerge, cla: yes, samples
