Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#2088 fix: pin events library to specific version
  eventarc/pubsub/package.json
Labels: cla: yes, samples

#2090 chore(functions/firebase): fix RTDB paths not working
  functions/firebase/index.js
  functions/firebase/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2092 test: fix appengine metadata tests
  appengine/metadata/flexible/server.js
  appengine/metadata/standard/server.js
Labels: cla: yes, samples

#2097 fix: Update test runner for Cloud Run logging-manual
  run/logging-manual/package.json
  run/logging-manual/test/deploy.sh
  run/logging-manual/test/e2e_test_cleanup.yaml
  run/logging-manual/test/e2e_test_setup.yaml
  run/logging-manual/test/retry.sh
  run/logging-manual/test/runner.sh
  run/logging-manual/test/system.test.js
  run/logging-manual/test/url.sh
Labels: cla: yes, samples

#2098 fix: Update test runner for Helloworld app
  run/helloworld/package.json
  run/helloworld/test/deploy.sh
  run/helloworld/test/e2e_test_cleanup.yaml
  run/helloworld/test/e2e_test_setup.yaml
  run/helloworld/test/retry.sh
  run/helloworld/test/runner.sh
  run/helloworld/test/system.test.js
  run/helloworld/test/url.sh
Labels: cla: yes, samples

#2094 chore: fix deps that are too specific
  appengine/hello-world/flexible/package.json
  appengine/storage/flexible/package.json
  appengine/websockets/README.md
  appengine/websockets/package.json
  eventarc/pubsub/package.json
Labels: automerge, cla: yes, samples

#2099 chore(functions): actually support env vars in target URL
  .kokoro/build.sh
  .kokoro/functions/helloworld.cfg
  functions/helloworld/test/sample.integration.http.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2102 Update test runner for Hello-broken
  run/hello-broken/package.json
  run/hello-broken/test/deploy.sh
  run/hello-broken/test/e2e_test_cleanup.yaml
  run/hello-broken/test/e2e_test_setup.yaml
  run/hello-broken/test/retry.sh
  run/hello-broken/test/runner.sh
  run/hello-broken/test/system.test.js
  run/hello-broken/test/url.sh
  run/helloworld/test/system.test.js
  run/idp-sql/test/system.test.js
  run/image-processing/test/system.test.js
  run/logging-manual/package.json
  run/logging-manual/test/system.test.js
  run/markdown-preview/editor/test/system.test.js
  run/markdown-preview/renderer/test/system.test.js
Labels: automerge, cla: yes, samples

#2065 chore(functions): switch to Node 12
  .kokoro/functions/common.cfg
  functions/billing/package.json
  functions/concepts/package.json
  functions/env_vars/package.json
  functions/firebase/package.json
  functions/helloworld/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/memorystore/redis/package.json
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/scheduleinstance/package.json
  functions/security/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/speech-to-speech/functions/package.json
  functions/tips/package.json
  functions/tokenservice/functions/package.json
Labels: api: cloudfunctions, cla: yes, samples

#2104 chore: delete samples for talent API
  CODEOWNERS
  jobs/v3/README.md
  jobs/v3/auto-complete-sample.js
  jobs/v3/basic-company-sample.js
  jobs/v3/basic-job-sample.js
  jobs/v3/batchdelete-jobs-sample.js
  jobs/v3/commute-search-sample.js
  jobs/v3/create-auth-credential.js
  jobs/v3/custom-attribute-sample.js
  jobs/v3/email-alert-search-sample.js
  jobs/v3/featured-job-search-sample.js
  jobs/v3/general-search-sample.js
  jobs/v3/histogram-sample.js
  jobs/v3/location-search-sample.js
  jobs/v3/package.json
  jobs/v3/quickstart.js
  jobs/v3/sleep.js
  jobs/v3/system-test/auto-complete-sample.test.js
  jobs/v3/system-test/basic-company-sample.test.js
  jobs/v3/system-test/basic-job-sample.test.js
  jobs/v3/system-test/batchdelete-jobs-sample.test.js
  jobs/v3/system-test/commute-search-sample.test.js
  jobs/v3/system-test/custom-attribute-sample.test.js
  jobs/v3/system-test/email-alert-search-sample.test.js
  jobs/v3/system-test/featured-job-search-sample.test.js
  jobs/v3/system-test/general-search-sample.test.js
  jobs/v3/system-test/histogram-sample.test.js
  jobs/v3/system-test/location-search-sample.test.js
  jobs/v3/system-test/quickstart.test.js
  jobs/v4/job_search_autocomplete_job_title.js
  jobs/v4/job_search_batch_delete_job.js
  jobs/v4/job_search_commute_search.js
  jobs/v4/job_search_create_client_event.js
  jobs/v4/job_search_create_company.js
  jobs/v4/job_search_create_job.js
  jobs/v4/job_search_create_job_custom_attributes.js
  jobs/v4/job_search_create_tenant.js
  jobs/v4/job_search_custom_ranking_search.js
  jobs/v4/job_search_delete_company.js
  jobs/v4/job_search_delete_job.js
  jobs/v4/job_search_delete_tenant.js
  jobs/v4/job_search_get_company.js
  jobs/v4/job_search_get_job.js
  jobs/v4/job_search_get_tenant.js
  jobs/v4/job_search_histogram_search.js
  jobs/v4/job_search_list_companies.js
  jobs/v4/job_search_list_jobs.js
  jobs/v4/job_search_list_tenants.js
  jobs/v4/package.json
Labels: cla: yes, samples, type: docs

#2109 Archive functions/tokenservice sample
  .kokoro/functions/tokenservice.cfg
  CODEOWNERS
  functions/tokenservice/.firebaserc
  functions/tokenservice/README.md
  functions/tokenservice/firebase.json
  functions/tokenservice/functions/index.js
  functions/tokenservice/functions/package.json
  functions/tokenservice/functions/test/index.test.js
Labels: cla: yes, samples

#2106 chore(functions): remove BASE_URL env var
  functions/helloworld/test/sample.integration.http.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2111 fix: Update test runner for PubSub CloudRun sample
  run/pubsub/package.json
  run/pubsub/test/deploy.sh
  run/pubsub/test/e2e_test_cleanup.yaml
  run/pubsub/test/e2e_test_setup.yaml
  run/pubsub/test/retry.sh
  run/pubsub/test/runner.sh
  run/pubsub/test/system.test.js
  run/pubsub/test/url.sh
Labels: cla: yes, samples

#2110 Update system-package tests
  run/system-package/package.json
  run/system-package/test/deploy.sh
  run/system-package/test/e2e_test_cleanup.yaml
  run/system-package/test/e2e_test_setup.yaml
  run/system-package/test/retry.sh
  run/system-package/test/runner.sh
  run/system-package/test/system.test.js
  run/system-package/test/url.sh
Labels: cla: yes, samples

#2112 chore(App Engine standard): update samples to Node 14
  appengine/analytics/app.standard.yaml
  appengine/analytics/package.json
  appengine/building-an-app/build/app.yaml
  appengine/building-an-app/build/package.json
  appengine/building-an-app/update/app.yaml
  appengine/building-an-app/update/package.json
  appengine/cloudsql/app.standard.yaml
  appengine/cloudsql/package.json
  appengine/cloudsql_postgresql/app.standard.yaml
  appengine/cloudsql_postgresql/package.json
  appengine/datastore/app.standard.yaml
  appengine/datastore/package.json
  appengine/hello-world/standard/app.yaml
  appengine/hello-world/standard/package.json
  appengine/mailjet/app.standard.yaml
  appengine/mailjet/package.json
  appengine/memcached/app.standard.yaml
  appengine/memcached/package.json
  appengine/metadata/standard/app.yaml
  appengine/metadata/standard/package.json
  appengine/pubsub/app.standard.yaml
  appengine/pubsub/package.json
  appengine/sendgrid/app.standard.yaml
  appengine/sendgrid/package.json
  appengine/static-files/app.standard.yaml
  appengine/static-files/package.json
  appengine/storage/standard/app.yaml
  appengine/storage/standard/package.json
  appengine/twilio/app.standard.yaml
  appengine/twilio/package.json
  appengine/typescript/app.yaml
  appengine/typescript/package.json
  appengine/websockets/package.json
Labels: cla: yes, samples

#2114 Chore: Update endpoints/getting-started-grpc to use @grpc/grpc-js
  endpoints/getting-started-grpc/client.js
  endpoints/getting-started-grpc/server.js
Labels: cla: yes, samples

#2116 Revert "chore: update endpoints/getting-started-grpc to use @grpc/grp…
  endpoints/getting-started-grpc/client.js
  endpoints/getting-started-grpc/server.js
Labels: cla: yes, samples

#2105 build: add system test config for event arc & functions
  .kokoro/build.sh
  .kokoro/eventarc-audit-storage.cfg
  .kokoro/eventarc-pubsub.cfg
  eventarc/audit-storage/package.json
  eventarc/audit-storage/test/deploy.sh
  eventarc/pubsub/package.json
  eventarc/pubsub/test/deploy.sh
  functions/helloworld/package.json
  functions/helloworld/test/sample.system.http.test.js
  functions/helloworld/test/sample.system.pubsub.test.js
  functions/helloworld/test/sample.system.storage.test.js
  functions/speech-to-speech/functions/test/index.test.js
Labels: cla: yes, samples
