Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#1981 docs(terminology): update language to follow recommendations
  functions/http/test/index.test.js
  functions/tips/test/index.test.js
  functions/tokenservice/functions/test/index.test.js
Labels: cla: yes, samples

#1995 feat: remove supertest from deps
  functions/helloworld/package.json
Labels: cla: yes

#1990 (Maybe) Fix broken billing sample
  functions/billing/index.js
  functions/billing/test/index.test.js
Labels: automerge, cla: yes, samples

#1997 chore(functions/pubsub): use consistent param names
  functions/pubsub/index.js
  functions/pubsub/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2006 chore(functions/pubsub): update gcloud command
  functions/pubsub/README.md
Labels: api: cloudfunctions, cla: yes, samples

#2003 feat: add eventarc generic sample
  eventarc/generic/.dockerignore
  eventarc/generic/Dockerfile
  eventarc/generic/app.js
  eventarc/generic/index.js
  eventarc/generic/package.json
  eventarc/generic/test/app.test.js
  eventarc/generic/test/deploy.sh
  eventarc/generic/test/runner.sh
  eventarc/generic/test/system.test.js
  eventarc/generic/test/url.sh
Labels: automerge, cla: yes, samples

#2002 chore: enable snippet-bot
  .github/snippet-bot.yml
Labels: cla: yes, samples

#1984 [Cloud Run] Identity Platform + Cloud SQL sample
  .kokoro/build-with-run.sh
  .kokoro/run/idp-sql.cfg
  run/idp-sql/.gitignore
  run/idp-sql/Dockerfile
  run/idp-sql/README.md
  run/idp-sql/app.js
  run/idp-sql/app.json
  run/idp-sql/cloud-sql.js
  run/idp-sql/handlebars.js
  run/idp-sql/index.js
  run/idp-sql/logging.js
  run/idp-sql/middleware.js
  run/idp-sql/package.json
  run/idp-sql/postcreate.sh
  run/idp-sql/postgres-secrets.json
  run/idp-sql/secrets.js
  run/idp-sql/setup.sh
  run/idp-sql/static/config.js
  run/idp-sql/static/firebase.js
  run/idp-sql/test/app.test.js
  run/idp-sql/test/e2e_test_cleanup.yaml
  run/idp-sql/test/e2e_test_setup.yaml
  run/idp-sql/test/retry.sh
  run/idp-sql/test/system.test.js
  run/idp-sql/views/index.html
Labels: cla: yes, samples

#2018 chore(functions): remove unused signed url sample
  functions/http/index.js
  functions/http/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2019 chore(functions): remove unused promise sample
  functions/background/README.md
  functions/background/index.js
  functions/background/package.json
  functions/background/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2017 chore(functions): remove unused template sample
  functions/helloworld/index.js
  functions/helloworld/index.pug
  functions/helloworld/package.json
  functions/helloworld/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2016 chore(functions): delete unused sample
  functions/concepts/loadable.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2020 fix: eventarc pubsub fix
  eventarc/pubsub/app.js
Labels: cla: yes, samples

#2013 chore(functions/ocr): Remove unused region tags + add clarifying comment
  functions/ocr/app/index.js
  functions/ocr/app/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2022 Add new updated SQL Server sample region tags.
  cloud-sql/sqlserver/mssql/server.js
Labels: cla: yes

#2023 chore: remove unmatched end region tag
  cloud-sql/mysql/mysql/server.js
Labels: cla: yes

#2024 chore: use node-fetch instead of gaxios
  datastore/functions/package.json
  datastore/functions/test/index.test.js
Labels: automerge, cla: yes, samples

#2035 Remove outdated SQL Server sample region tags.
  cloud-sql/sqlserver/mssql/server.js
Labels: cla: yes

#2037 chore: activate no-unused-vars eslint rule
  .eslintrc.json
  cloud-sql/sqlserver/mssql/server.js
  functions/http/package.json
  functions/http/test/index.test.js
  healthcare/datasets/system-test/datasets.test.js
  healthcare/fhir/patchFhirResource.js
  jobs/v4/job_search_create_client_event.js
Labels: cla: yes

#2036 chore: clarify contributing guidelines
  CONTRIBUTING.md
Labels: automerge, cla: yes

#2028 chore: use node-fetch instead of axios
  appengine/analytics/app.js
  appengine/analytics/package.json
  functions/security/index.js
  functions/security/package.json
  functions/security/test/index.test.js
  functions/tips/index.js
  functions/tips/package.json
Labels: cla: yes, samples

#2038 chore: activate more eslint rules
  .eslintrc.json
  cloud-sql/mysql/mysql/server.js
  cloud-sql/sqlserver/mssql/server.js
  eventarc/audit-storage/test/system.test.js
  eventarc/generic/test/system.test.js
  eventarc/pubsub/test/system.test.js
  run/hello-broken/package.json
  run/hello-broken/test/system.test.js
  run/helloworld/package.json
  run/helloworld/test/system.test.js
  run/image-processing/test/system.test.js
  run/markdown-preview/renderer/test/system.test.js
  run/pubsub/test/system.test.js
  run/system-package/package.json
  run/system-package/test/system.test.js
Labels: cla: yes
