Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-09, with the labels that each got.

#1962 chore(functions/firebase): remove "data" property
  functions/firebase/index.js
  functions/firebase/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#1964 chore(functions/firebase): use Node 12 function signatures
  functions/firebase/index.js
Labels: api: cloudfunctions, cla: yes, samples

#1965 chore: add sofisl as repo owner
  CODEOWNERS
Labels: automerge, cla: yes, samples

#1967 chore(functions/firebase): fix samples + tests not running
  .kokoro/functions/firebase.cfg
  functions/firebase/index.js
  functions/firebase/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#1972 docs: update slack url. fixes #1820
  README.md
Labels: cla: yes

#1976 chore: update Data Analytics PA CODEOWNERS
  CODEOWNERS
Labels: cla: yes, samples

#1978 feat: init eventarc quickstarts
  eventarc/audit-storage/.dockerignore
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/README.md
  eventarc/audit-storage/anthos.md
  eventarc/audit-storage/app.js
  eventarc/audit-storage/index.js
  eventarc/audit-storage/package.json
  eventarc/audit-storage/test/app.test.js
  eventarc/audit-storage/test/deploy.sh
  eventarc/audit-storage/test/runner.sh
  eventarc/audit-storage/test/system.test.js
  eventarc/audit-storage/test/url.sh
  eventarc/pubsub/.dockerignore
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/README.md
  eventarc/pubsub/anthos.md
  eventarc/pubsub/app.js
  eventarc/pubsub/index.js
  eventarc/pubsub/package.json
  eventarc/pubsub/test/app.test.js
  eventarc/pubsub/test/deploy.sh
  eventarc/pubsub/test/runner.sh
  eventarc/pubsub/test/system.test.js
  eventarc/pubsub/test/url.sh
  run/events-pubsub/README.md
Labels: cla: yes

#1979 eventarc: cal event log
  eventarc/audit-storage/app.js
  eventarc/audit-storage/test/app.test.js
Labels: cla: yes

#1980 chore(functions): show client library init
  functions/pubsub/index.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1986 Eventarc Quickstart Brushup
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/index.js
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/app.js
  eventarc/pubsub/index.js
  eventarc/pubsub/package.json
Labels: automerge, cla: yes, samples
