Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2020-04, with the labels that each got.

#1692 chore: refactor cloud sql server test
  appengine/cloudsql/package.json
  appengine/cloudsql/test/serverListening.test.js
Labels: cla: yes

#1693 chore: refactor pubsub test
  appengine/pubsub/package.json
  appengine/pubsub/test/appListening.test.js
Labels: cla: yes

#1699 chore: refactor typescript test
  appengine/typescript/index.ts
  appengine/typescript/package.json
  appengine/typescript/test/app.test.js
Labels: automerge, cla: yes

#1701 fix: move code to outside of sample snippets
  appengine/analytics/app.js
  appengine/static-files/app.js
  containerengine/hello-world/server.js
Labels: automerge, cla: yes

#1705 GCF: add bearer-auth sample
  .kokoro/functions/security.cfg
  functions/security/index.js
  functions/security/package.json
  functions/security/test/index.test.js
Labels: automerge, cla: yes

#1711 fix: use unique logfile names
  .kokoro/build-with-appengine.sh
  .kokoro/build-with-run.sh
  .kokoro/build.sh
Labels: automerge, cla: yes

#1713 GCF CI/CD: Use consistent region tags across languages
  functions/ci_cd/cloudbuild.yaml
Labels: cla: yes

#1714 GCF: refactor connection pooling sample
  functions/tips/index.js
  functions/tips/package.json
Labels: cla: yes

#1716 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#1708 feat: add node sample for cloud composer tutorial
  CODEOWNERS
  composer/README.md
  composer/composer_transform_csv_to_json.js
  composer/package.json
  composer/test/composer_transform_csv_to_json.test.js
Labels: cla: yes

#1718 Update Data Catalog samples to V1
  datacatalog/cloud-client/createEntryGroup.js
  datacatalog/cloud-client/createFilesetEntry.js
  datacatalog/cloud-client/lookupEntry.js
  datacatalog/quickstart/createFilesetEntry.js
  datacatalog/quickstart/deleteFilesetEntry.js
Labels: automerge, cla: yes

#1720 chore: update IoT to Node 10
  .kokoro/iot/common.cfg
  iot/http_example/package.json
  iot/manager/package.json
  iot/mqtt_example/package.json
  iot/scripts/package.json
Labels: automerge, cla: yes

#1698 chore:refactor memcached test
  appengine/memcached/app.js
  appengine/memcached/package.json
  appengine/memcached/test/app.test.js
Labels: automerge, cla: yes

#1721 healthcare API: update hl7v2 samples from v1beta1 to v1
  healthcare/hl7v2/createHl7v2Message.js
  healthcare/hl7v2/createHl7v2Store.js
  healthcare/hl7v2/deleteHl7v2Message.js
  healthcare/hl7v2/deleteHl7v2Store.js
  healthcare/hl7v2/getHl7v2Message.js
  healthcare/hl7v2/getHl7v2Store.js
  healthcare/hl7v2/getHl7v2StoreIamPolicy.js
  healthcare/hl7v2/ingestHl7v2Message.js
  healthcare/hl7v2/listHl7v2Messages.js
  healthcare/hl7v2/listHl7v2Stores.js
  healthcare/hl7v2/package.json
  healthcare/hl7v2/patchHl7v2Message.js
  healthcare/hl7v2/patchHl7v2Store.js
  healthcare/hl7v2/setHl7v2StoreIamPolicy.js
Labels: automerge, cla: yes

#1722 chore: refactor cloudsql_postgresql test from repo-tools
  appengine/cloudsql_postgresql/package.json
  appengine/cloudsql_postgresql/test/serverListening.test.js
Labels: automerge, cla: yes, kokoro:run

#1726 Delete unused SQL samples
  functions/sql/index.js
  functions/sql/package.json
  functions/sql/test/index.test.js
Labels: cla: yes

#1729 Add "gcf filesystem is not persistent" note
  functions/http/index.js
Labels: automerge, cla: yes

#1723 feat!: require node 10 in engines field
  package.json
Labels: cla: yes

#1725 build!: update to latest version of gts and typescript
  .eslintrc
  .eslintrc.yml
  .estlintrc.json
  .prettierignore
  .prettierrc
  .prettierrc.js
  appengine/typescript/index.ts
  appengine/typescript/package.json
  appengine/websockets/test/index.test.js
  package.json
Labels: cla: yes

#1712 fix #1710: async pooling bug in MySQL
  cloud-sql/mysql/mysql/server.js
Labels: cla: yes

#1732 healthcare API: update datasets and DICOM samples from v1beta1 to v1
  healthcare/datasets/createDataset.js
  healthcare/datasets/deidentifyDataset.js
  healthcare/datasets/deleteDataset.js
  healthcare/datasets/getDataset.js
  healthcare/datasets/getDatasetIamPolicy.js
  healthcare/datasets/listDatasets.js
  healthcare/datasets/package.json
  healthcare/datasets/patchDataset.js
  healthcare/datasets/setDatasetIamPolicy.js
  healthcare/datasets/system-test/datasets.test.js
  healthcare/dicom/createDicomStore.js
  healthcare/dicom/deleteDicomStore.js
  healthcare/dicom/dicomWebDeleteStudy.js
  healthcare/dicom/dicomWebRetrieveInstance.js
  healthcare/dicom/dicomWebRetrieveRendered.js
  healthcare/dicom/dicomWebRetrieveStudy.js
  healthcare/dicom/dicomWebSearchForInstances.js
  healthcare/dicom/dicomWebSearchStudies.js
  healthcare/dicom/dicomWebStoreInstance.js
  healthcare/dicom/exportDicomInstanceGcs.js
  healthcare/dicom/getDicomStore.js
  healthcare/dicom/getDicomStoreIamPolicy.js
  healthcare/dicom/importDicomInstance.js
  healthcare/dicom/listDicomStores.js
  healthcare/dicom/package.json
  healthcare/dicom/patchDicomStore.js
  healthcare/dicom/setDicomStoreIamPolicy.js
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
Labels: cla: yes

#1733 healthcare API: update FHIR samples from v1beta1 to v1
  healthcare/fhir/createFhirStore.js
  healthcare/fhir/deleteFhirResource.js
  healthcare/fhir/deleteFhirResourcePurge.js
  healthcare/fhir/deleteFhirStore.js
  healthcare/fhir/exportFhirResources.js
  healthcare/fhir/fhir_resources.js
  healthcare/fhir/getFhirResource.js
  healthcare/fhir/getFhirResourceHistory.js
  healthcare/fhir/getFhirStore.js
  healthcare/fhir/getFhirStoreCapabilities.js
  healthcare/fhir/getFhirStoreIamPolicy.js
  healthcare/fhir/getPatientEverything.js
  healthcare/fhir/importFhirResources.js
  healthcare/fhir/listFhirResourceHistory.js
  healthcare/fhir/listFhirStores.js
  healthcare/fhir/package.json
  healthcare/fhir/patchFhirStore.js
  healthcare/fhir/searchFhirResourcesGet.js
  healthcare/fhir/searchFhirResourcesPost.js
  healthcare/fhir/setFhirStoreIamPolicy.js
  healthcare/fhir/system-test/fhir_resources.test.js
  healthcare/fhir/system-test/fhir_stores.test.js
  healthcare/fhir/updateFhirResource.js
Labels: cla: yes

#1734 GCF: delete extraneous getmetrics sample
  functions/log/index.js
  functions/log/test/index.test.js
Labels: cla: yes

#1736 healthcare API: use new request body for notificationConfigs when patching HL7v2 store
  healthcare/hl7v2/patchHl7v2Store.js
Labels: automerge, cla: yes

#1744 Change for...of to for...in
  functions/http/index.js
Labels: cla: yes

#1748 chore: delete unused config
  .kokoro/require-system-tests.sh
  appengine/analytics/package.json
  appengine/building-an-app/build/package.json
  appengine/cloudsql/package.json
  appengine/cloudsql_postgresql/package.json
  appengine/datastore/package.json
  appengine/mailjet/package.json
  appengine/memcached/.cloud-repo-tools.json
  appengine/metadata/flexible/package.json
  appengine/metadata/standard/package.json
  appengine/pubsub/package.json
  appengine/redis/package.json
  appengine/sendgrid/.cloud-repo-tools.json
  appengine/static-files/package.json
  appengine/storage/flexible/package.json
  appengine/storage/standard/package.json
  appengine/websockets/package.json
  containerengine/hello-world/package.json
  functions/env_vars/package.json
  functions/helloworld/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/sendgrid/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/speech-to-speech/functions/package.json
  functions/tips/package.json
  healthcare/datasets/package.json
  healthcare/dicom/package.json
  healthcare/fhir/package.json
  healthcare/hl7v2/package.json
  iot/manager/package.json
  opencensus/package.json
Labels: cla: yes

#1749 chore: remove instance of repo-tools in appengine/endpoints
  appengine/endpoints/package.json
  appengine/endpoints/test/appListening.test.js
Labels: automerge, cla: yes

#1743 feat: add Blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#1753 fix: add missing await for an async function call
  functions/imagemagick/index.js
Labels: automerge, cla: yes

#1754 Reference how to test, and remove unneeded step
  appengine/storage/standard/README.md
  appengine/storage/standard/system-test/app.test.js
Labels: cla: yes

#1755 fix: spacing for code samples
  iot/manager/manager.js
Labels: automerge, cla: yes

#1751 functions/slack: config.json -> env vars
  functions/slack/index.js
  functions/slack/test/index.test.js
Labels: automerge, cla: yes

#1746 fix(cloud-sql): update unclear configuration in postgres connection sample
  cloud-sql/postgres/knex/server.js
Labels: cla: yes

#1756 Use correct GCF URL in Slack sample
  functions/slack/index.js
Labels: automerge, cla: yes

#1760 Background function: return on completion
  functions/node8/index.js
Labels: automerge, cla: yes
