Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-05, with the labels that each got.

#2229 chore: Update tests to Node 14
  .kokoro/datastore-functions.cfg
  .kokoro/functions/billing-periodic.cfg
  .kokoro/functions/imagemagick.cfg
  .kokoro/functions/ocr-app.cfg
  .kokoro/functions/speech-to-speech.cfg
  .kokoro/healthcare/common.cfg
Labels: cla: yes, samples

#2151 chore(run): upgrade to Node 14
  run/helloworld/Dockerfile
Labels: api: run, cla: yes, samples

#2127 chore(functions): Move tests to Node 14 image
  .kokoro/functions/common.cfg
Labels: api: cloudfunctions, cla: yes, samples

#2237 healthcare API: lint fixes
  cloud-sql/postgres/knex/test/createTable.test.js
  healthcare/dicom/dicomWebRetrieveInstance.js
  healthcare/dicom/dicomWebRetrieveRendered.js
  healthcare/dicom/dicomWebRetrieveStudy.js
  healthcare/dicom/dicomWebSearchForInstances.js
  healthcare/dicom/dicomWebSearchStudies.js
  healthcare/dicom/dicomWebStoreInstance.js
  healthcare/dicom/getDicomStore.js
  healthcare/dicom/getDicomStoreIamPolicy.js
  healthcare/dicom/importDicomInstance.js
  healthcare/dicom/listDicomStores.js
  healthcare/dicom/setDicomStoreIamPolicy.js
  healthcare/dicom/system-test/dicomweb.test.js
  healthcare/fhir/createFhirResource.js
  healthcare/fhir/executeFhirBundle.js
  healthcare/fhir/exportFhirResources.js
  healthcare/fhir/getFhirResource.js
  healthcare/fhir/getFhirResourceHistory.js
  healthcare/fhir/getFhirStore.js
  healthcare/fhir/getFhirStoreCapabilities.js
  healthcare/fhir/getFhirStoreIamPolicy.js
  healthcare/fhir/getPatientEverything.js
  healthcare/fhir/importFhirResources.js
  healthcare/fhir/listFhirResourceHistory.js
  healthcare/fhir/listFhirStores.js
  healthcare/fhir/searchFhirResourcesGet.js
  healthcare/fhir/searchFhirResourcesPost.js
  healthcare/fhir/setFhirStoreIamPolicy.js
  healthcare/fhir/updateFhirResource.js
  healthcare/hl7v2/createHl7v2Message.js
  healthcare/hl7v2/getHl7v2Message.js
  healthcare/hl7v2/getHl7v2Store.js
  healthcare/hl7v2/getHl7v2StoreIamPolicy.js
  healthcare/hl7v2/ingestHl7v2Message.js
  healthcare/hl7v2/listHl7v2Messages.js
  healthcare/hl7v2/listHl7v2Stores.js
  healthcare/hl7v2/setHl7v2StoreIamPolicy.js
Labels: cla: yes, samples
