Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-06, with the labels that each got.

#2244 Update CODEOWNERS / Blunderbuss for SoDA teams
  .github/blunderbuss.yml
  CODEOWNERS
Labels: automerge, cla: yes, samples

#2252 Add retries to Run tests
  run/idp-sql/test/system.test.js
Labels: cla: yes, samples

#2259 fix(functions/slack): use @googleapis/kgsearch module
  functions/slack/index.js
  functions/slack/package.json
  functions/slack/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2262 chore(functions/pubsub): increase test timeout
  functions/pubsub/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2269 fix(functions/billing): use @google-cloud/billing module
  functions/billing/index.js
  functions/billing/package.json
Labels: api: cloudfunctions, cla: yes, samples

#2272 fix(run): run test retries
  run/idp-sql/test/system.test.js
Labels: api: run, cla: yes, samples

#2274 fix: function test updates
  functions/tips/index.js
  functions/tips/test/index.test.js
Labels: cla: yes, samples

#2270 fix(functions/billing): remove usage of request module
  functions/billing/package.json
  functions/billing/test/index.test.js
  functions/billing/test/periodic.test.js
Labels: api: cloudfunctions, cla: yes, samples
