Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-03, with the labels that each got.

#2190 fix(functions/scheduledinstance): Update JSON parsing and sample tests
  functions/scheduleinstance/index.js
  functions/scheduleinstance/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2149 added opencensus sample and test
  .kokoro/build.sh
  .kokoro/monitoring-opencensus.cfg
  CODEOWNERS
  monitoring/opencensus/README.md
  monitoring/opencensus/app.js
  monitoring/opencensus/package.json
  monitoring/opencensus/system-test/app.test.js
Labels: automerge, cla: yes, samples

#2194 chore: delete eventarc anthos files
  eventarc/audit-storage/anthos.md
  eventarc/pubsub/anthos.md
Labels: automerge, cla: yes, samples

#2201 docs: add region tag for sigterm handler
  run/idp-sql/index.js
Labels: automerge, cla: yes, samples

#2202 chore(functions): clarify termination example
  functions/concepts/termination.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2163 chore(functions): avoid requiring all of googleapis
  functions/billing/index.js
  functions/billing/test/index.test.js
  functions/slack/index.js
  functions/slack/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2209 chore(eventarc): update region tags
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/app.js
  eventarc/audit-storage/index.js
Labels: api: eventarc, cla: yes, kokoro:run, samples

#2206 chore(functions): remove RTDB path params
  functions/firebase/index.js
  functions/firebase/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2205 chore(monitoring/prometheus): Update prometheus to fix failing test
  monitoring/prometheus/app.js
Labels: api: monitoring, cla: yes, samples

#2212 chore(appengine): update CODEOWNERS
  CODEOWNERS
Labels: api: appengine, automerge, cla: yes, samples

#2213 chore(functions): update node-fetch invocation
  functions/tips/index.js
Labels: api: cloudfunctions, automerge, cla: yes, samples
