Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-11, with the labels that each got.

#2401 feat(functions/v2): add GCE + CAL sample
  functions/v2/index.js
  functions/v2/package.json
  functions/v2/test/system.test.js
Labels: automerge, cla: yes, api: cloudfunctions, samples

#2402 chore(functions): address comments on CAL samples
  functions/v2/index.js
  functions/v2/package.json
  functions/v2/test/index.test.js
Labels: cla: yes, api: cloudfunctions, samples

#2413 Update Cloud SQL sample apps with Kubernetes Engine yaml files.
  cloud-sql/mysql/mysql/deployment.yaml
  cloud-sql/mysql/mysql/service-account.yaml
  cloud-sql/mysql/mysql/service.yaml
  cloud-sql/postgres/knex/deployment.yaml
  cloud-sql/postgres/knex/service-account.yaml
  cloud-sql/postgres/knex/service.yaml
Labels: cla: yes, samples

#2435 Rename CLOUD_SQL_CONNECTION_NAME to INSTANCE_CONNECTION_NAME
  .kokoro/build.sh
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql/app.flexible.yaml
  cloud-sql/mysql/mysql/app.standard.yaml
  cloud-sql/mysql/mysql/server.js
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/app.flexible.yaml
  cloud-sql/postgres/knex/app.standard.yaml
  cloud-sql/postgres/knex/package.json
  cloud-sql/postgres/knex/server.js
  cloud-sql/sqlserver/mssql/README.md
  cloud-sql/sqlserver/mssql/app.yaml
Labels: cla: yes, samples

#2436 Switch JSON middleware for UrlEncoded
  appengine/building-an-app/update/server.js
Labels: cla: yes, samples, actions:force-run

#2438 Assign Serverless issues to aap-dpes team
  .github/blunderbuss.yml
Labels: cla: yes, samples

#2433 chore(functions/v2): address comments on CAL samples
  functions/v2/index.js
  functions/v2/test/index.test.js
Labels: cla: yes, api: cloudfunctions, samples

#2443 chore: auto-run actions on renovate PRs
  .github/trusted-contribution.yml
Labels: cla: yes, samples

#2444 build: auto-remove actions run label
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples, actions:force-run

#2445 build: use github.rest client for label removal
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples, actions:force-run

#2446 build: remove checkout build echo
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples

#2430 Add Cloud Run sample
  .kokoro/run/jobs.cfg
  run/jobs/.eslintrc.json
  run/jobs/.gcloudignore
  run/jobs/Procfile
  run/jobs/README.md
  run/jobs/index.js
  run/jobs/package.json
  run/jobs/test/index.test.js
Labels: cla: yes, samples

#2448 build: use github-script@v5 in CI
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples, actions:force-run

#2449 build: use github token for label removal
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples

#2450 build: add PR write permissions to label job
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples, actions:force-run

#2451 build: add a missing comma in the label script
  .github/workflows/ci.yaml.template
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
Labels: cla: yes, samples
