Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-07, with the labels that each got.

#2275 feat(run): Update sample to use Secret Manager integration
  run/idp-sql/README.md
  run/idp-sql/cloud-sql.js
  run/idp-sql/package.json
  run/idp-sql/postcreate.sh
  run/idp-sql/secrets.js
  run/idp-sql/test/e2e_test_setup.yaml
  run/idp-sql/test/system.test.js
Labels: api: run, automerge, cla: yes, samples, snippet-bot:no-prefix-req

#2266 build(functions/speech-to-speech): remove usage of request
  functions/speech-to-speech/functions/package.json
  functions/speech-to-speech/functions/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2280 fix(functions/pubsub): drop dependency on request
  functions/pubsub/package.json
  functions/pubsub/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2281 fix(appengine/pubsub): clean up dependencies
  appengine/pubsub/package.json
  appengine/pubsub/test/appListening.test.js
Labels: api: appengine, cla: yes, samples

#2263 fix(functions/helloworld): stop using request
  functions/helloworld/package.json
  functions/helloworld/test/index.test.js
  functions/helloworld/test/sample.integration.http.test.js
  functions/helloworld/test/sample.integration.pubsub.test.js
  functions/helloworld/test/sample.integration.storage.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2265 fix(opencensus): remove unused dependencies
  monitoring/opencensus/package.json
Labels: cla: yes, samples

#2278 feat: update readme to use Secret Manager
  cloud-sql/mysql/mysql/README.md
  cloud-sql/postgres/knex/README.md
Labels: cla: yes, samples

#2284 chore: run cloud build on trusted PRs
  .github/trusted-contribution.yml
Labels: cla: yes, samples

#2283 fix(functions/security): clean up dependencies
  functions/security/package.json
Labels: api: cloudfunctions, cla: yes, samples

#2282 fix(functions/imagemagick): drop dependency on request
  functions/imagemagick/package.json
  functions/imagemagick/test/index.test.js
Labels: api: cloudfunctions, cla: yes, samples

#2285 docs: add a security policy
  SECURITY.md
Labels: cla: yes, samples

#2286 chore(CODEOWNERS): Remove grant as functions owner
  CODEOWNERS
Labels: cla: yes, kokoro:run, samples

#2290 fix: Update secret gcloud command
  cloud-sql/mysql/mysql/README.md
  cloud-sql/postgres/knex/README.md
Labels: automerge, cla: yes, samples

#2293 fix(run/markdown-preview): full width input form
  run/markdown-preview/editor/templates/index.html
Labels: api: run, cla: yes, samples

#2291 build: use GitHub Actions for linting
  .github/workflows/lint.yaml
  .kokoro/lint.cfg
  .kokoro/lint.sh
Labels: cla: yes, samples

#2268 feat: Add Cloud Run websocket sample
  .kokoro/build-with-run.sh
  .kokoro/run/websockets.cfg
  run/websockets/.eslintrc.json
  run/websockets/README.md
  run/websockets/app.js
  run/websockets/index.js
  run/websockets/package.json
  run/websockets/public/.eslintrc.json
  run/websockets/public/index.css
  run/websockets/public/index.html
  run/websockets/public/index.js
  run/websockets/redis.js
  run/websockets/test/e2e_test_cleanup.yaml
  run/websockets/test/e2e_test_setup.yaml
  run/websockets/test/retry.sh
  run/websockets/test/system.test.js
  run/websockets/users.js
Labels: api: run, cla: yes, samples

#2299 feat(functions): add CloudEvents-based PubSub sample
  functions/v2/.gitignore
  functions/v2/index.js
  functions/v2/test/index.test.js
Labels: api: cloudfunctions, automerge, cla: yes, samples
