Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-08, with the labels that each got.

#2304 healthcare API: fix some doc bugs and move sleep.js into files
  healthcare/dicom/importDicomInstance.js
  healthcare/dicom/listDicomStores.js
  healthcare/fhir/deleteFhirResource.js
  healthcare/fhir/deleteFhirResourcePurge.js
  healthcare/fhir/exportFhirResources.js
  healthcare/fhir/importFhirResources.js
  healthcare/fhir/listFhirStores.js
  healthcare/fhir/setFhirStoreIamPolicy.js
  healthcare/hl7v2/setHl7v2StoreIamPolicy.js
  healthcare/sleep.js
Labels: cla: yes, samples

#2303 fix: Fix Markdown rendering of README cmd
  run/websockets/README.md
Labels: cla: yes, samples

#2297 Update README.md
  run/websockets/README.md
Labels: cla: yes, samples

#2305 build: perform 404 scanning on docs
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  README.md
  appengine/README.md
  appengine/endpoints/README.md
  functions/README.md
  linkinator.config.json
  monitoring/opencensus/README.md
  monitoring/prometheus/README.md
  run/idp-sql/README.md
  workflows/quickstart/README.md
Labels: cla: yes, samples

#2308 sample(run): Update node.js version
  cloud-tasks/app/app.yaml
  cloud-tasks/app/createTask.js
  cloud-tasks/app/package.json
  cloud-tasks/function/package.json
Labels: cla: yes, api: run, samples

#2315 chore(appengine): Fix typos in README
  appengine/README.md
Labels: cla: yes, samples

#2314 fix(build): migrate to using main branch
  .github/workflows/ci.yaml
  .kokoro/build-with-appengine.sh
  .kokoro/build-with-run.sh
  .kokoro/build.sh
  CONTRIBUTING.md
  appengine/README.md
  appengine/analytics/README.md
  appengine/building-an-app/build/README.md
  appengine/building-an-app/update/README.md
  appengine/datastore/README.md
  appengine/hello-world/flexible/README.md
  appengine/hello-world/standard/README.md
  appengine/typescript/README.md
  appengine/websockets/README.md
  containerengine/hello-world/README.md
  datastore/functions/README.md
  eventarc/audit-storage/README.md
  eventarc/pubsub/README.md
  run/hello-broken/README.md
  run/helloworld/README.md
  run/idp-sql/README.md
  run/idp-sql/cloud-sql.js
  run/image-processing/README.md
  run/logging-manual/README.md
  run/markdown-preview/README.md
  run/pubsub/README.md
  run/system-package/README.md
  run/websockets/README.md
Labels: cla: yes, samples

#2318 minor: Update title to reflect compute platform
  run/websockets/public/index.html
Labels: cla: yes, samples

#2316 build: enable cloud build for healthcare/dicom
  healthcare/dicom/system-test/dicom_stores.test.js
  healthcare/dicom/system-test/dicomweb.test.js
Labels: cla: yes, samples

#2307 Update Cloud SQL Postgres sample to create table on app start
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/createTable.js
  cloud-sql/postgres/knex/server.js
  cloud-sql/postgres/knex/test/createTable.test.js
Labels: cla: yes, samples

#2313 fix: add retries to test
  run/websockets/test/system.test.js
Labels: automerge, cla: yes, samples

#2320 feat(functions): {add GCS, refactor other} v2 sample
  functions/v2/index.js
  functions/v2/package.json
  functions/v2/test/index.test.js
Labels: cla: yes, api: cloudfunctions, samples
