Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2021-02, with the labels that each got.

#2145 fix: remove cleanup call
  .kokoro/build-with-run.sh
Labels: cla: yes, samples

#2150 fix: Remove unused Cloud Build substitutions from test
  run/image-processing/test/e2e_test_cleanup.yaml
  run/image-processing/test/e2e_test_setup.yaml
Labels: cla: yes, samples

#2155 chore(functions): update scheduleinstance owner
  CODEOWNERS
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2161 fix(functions): add fully qualified domain name for metadata sample
  functions/security/index.js
Labels: api: cloudfunctions, cla: yes, samples

#2159 fix(run): remove retries from bad request test
  run/hello-broken/test/system.test.js
Labels: api: run, automerge, cla: yes, samples

#2160 chore(functions): remove unused exception handler
  functions/slack/index.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2162 chore(functions): add node termination example
  functions/concepts/termination.js
Labels: api: cloudfunctions, automerge, cla: yes, samples

#2165 chore: delete storage transfer samples
  .kokoro/storage-transfer.cfg
  CONTRIBUTING.md
  README.md
  storage-transfer/README.md
  storage-transfer/package.json
  storage-transfer/system-test/transfer.test.js
  storage-transfer/test/transfer.test.js
  storage-transfer/transfer.js
Labels: cla: yes, samples

#2164 feat(run): add package.json for quickstart
  run/helloworld/package.docs.json
Labels: api: run, automerge, cla: yes, samples

#2168 fix: update eventarc storage name
  eventarc/audit-storage/app.js
  eventarc/audit-storage/test/app.test.js
Labels: cla: yes, samples

#2176 fix(run): Update Logging test with retries
  run/logging-manual/package.json
  run/logging-manual/test/system.test.js
Labels: api: run, cla: yes, samples

#2185 healthcare API: use mocha-test to retry dataset failures
  healthcare/datasets/package.json
  healthcare/datasets/system-test/datasets.test.js
Labels: cla: yes, samples

#2187 fix: add production dependency for GAE app
  appengine/typescript/package.json
Labels: cla: yes, samples

#2189 feat(functions): add HTTP termination example
  functions/concepts/termination.js
Labels: api: cloudfunctions, automerge, cla: yes, samples
