Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-05, with the labels that each got.

#2627 fix: add timeout to Cloud Builds
  run/hello-broken/test/system.test.js
  run/helloworld/test/system.test.js
  run/idp-sql/test/system.test.js
  run/image-processing/test/system.test.js
  run/jobs/.gcloudignore
  run/jobs/test/e2e_test_setup.yaml
  run/jobs/test/system.test.js
  run/logging-manual/test/system.test.js
  run/markdown-preview/editor/test/system.test.js
  run/markdown-preview/renderer/test/system.test.js
  run/pubsub/test/system.test.js
  run/system-package/test/system.test.js
  run/websockets/test/system.test.js
Labels: samples

#2635 chore(functions/ocr): fix newline-induced test flakes
  functions/ocr/app/index.js
  functions/ocr/app/package.json
  functions/ocr/app/test/index.test.js
Labels: api: cloudfunctions, samples

#2638 chore(functions/v2): fix failing region tag check
  functions/v2/cloudEventLogging/test/index.test.js
  functions/v2/http-logging/test/index.test.js
Labels: api: cloudfunctions, samples

#2634 chore(functions/http): update Busboy usage
  functions/http/index.js
Labels: api: cloudfunctions, samples

#2620 fix(cloudsql): update samples with proper env variable
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql/app.flexible.yaml
  cloud-sql/mysql/mysql/app.standard.yaml
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/app.flexible.yaml
  cloud-sql/postgres/knex/app.standard.yaml
Labels: api: cloudsql, samples

#2642 Add docs specific package.json for quickstart
  run/jobs/package.docs.json
Labels: samples

#2650 feat(functions/v2): update imagemagick sample
  functions/imagemagick/index.js
  functions/imagemagick/package.json
  functions/imagemagick/test/integration.test.js
  functions/imagemagick/test/unit.test.js
  functions/imagemagick/zombie.jpg
Labels: api: cloudfunctions, samples

#2654 fix(run/websocket): Debug Websocket test errors
  run/websockets/app.js
  run/websockets/package.json
Labels: api: run, samples

#2649 docs: add Google Cloud Samples browser link to readme template
  README.md
Labels: samples

#2646 feat(functions/v2): use FF testing layer for GCS sample
  functions/v2/helloGCS/.gcloudignore
  functions/v2/helloGCS/package.json
  functions/v2/helloGCS/test/integration.test.js
  functions/v2/helloGCS/test/unit.test.js
Labels: api: cloudfunctions, samples

#2645 feat(functions/helloPubSub): use new FF testing layer
  functions/v2/helloPubSub/package.json
  functions/v2/helloPubSub/test/integration.test.js
  functions/v2/helloPubSub/test/unit.test.js
Labels: api: cloudfunctions, samples

#2647 feat(functions/v2): use FF testing layer in audit log sample
  functions/v2/helloAuditLog/.gcloudignore
  functions/v2/helloAuditLog/index.js
  functions/v2/helloAuditLog/package.json
  functions/v2/helloAuditLog/test/integration.test.js
  functions/v2/helloAuditLog/test/unit.test.js
Labels: api: cloudfunctions, samples

#2659 chore(functions/helloworld): update to use FF testing layer
  functions/helloworld/index.js
  functions/helloworld/package.json
  functions/helloworld/test/sample.integration.http.test.js
  functions/helloworld/test/sample.unit.http.test.js
Labels: api: cloudfunctions, samples

#2651 feat(functions/v2): update slack sample
  .github/workflows/functions-slack.yaml
  functions/slack/index.js
  functions/slack/package.json
  functions/slack/test/integration.test.js
  functions/slack/test/unit.test.js
Labels: api: cloudfunctions, samples

#2648 feat(functions/v2): add bigquery sample
  .github/workflows/functions-v2-hellobigquery.yaml
  functions/v2/helloBigQuery/.gcloudignore
  functions/v2/helloBigQuery/index.js
  functions/v2/helloBigQuery/package.json
  functions/v2/helloBigQuery/test/integration.test.js
Labels: api: cloudfunctions, samples

#2641 fix(functions/v2): update folder name
  functions/v2/httpLogging/index.js
  functions/v2/httpLogging/package.json
  functions/v2/httpLogging/test/index.test.js
Labels: api: cloudfunctions, samples

#2644 build!: drop support for Node 10
  appengine/building-an-app/update/package.json
  appengine/endpoints/package.json
  appengine/pubsub/package.json
  appengine/twilio/package.json
  auth/package.json
  cloud-sql/mysql/mysql/package.json
  cloud-sql/postgres/knex/package.json
  cloud-sql/sqlserver/mssql/package.json
  cloud-tasks/app/package.json
  cloud-tasks/function/package.json
  composer/functions/composer-storage-trigger/package.json
  composer/package.json
  containerengine/hello-world/package.json
  datacatalog/cloud-client/package.json
  datacatalog/quickstart/package.json
  datastore/functions/package.json
  endpoints/getting-started-grpc/package.json
  endpoints/getting-started/package.json
  eventarc/audit-storage/package.json
  eventarc/generic/package.json
  eventarc/pubsub/package.json
  functions/billing/package.json
  functions/concepts/package.json
  functions/env_vars/package.json
  functions/firebase/package.json
  functions/helloworld/package.json
  functions/http/package.json
  functions/imagemagick/package.json
  functions/log/package.json
  functions/memorystore/redis/package.json
  functions/ocr/app/package.json
  functions/pubsub/package.json
  functions/scheduleinstance/package.json
  functions/security/package.json
  functions/slack/package.json
  functions/spanner/package.json
  functions/tips/package.json
  functions/v2/autoLabelInstance/package.json
  functions/v2/helloAuditLog/package.json
  functions/v2/helloGCS/package.json
  functions/v2/helloPubSub/package.json
  functions/v2/package.json
  healthcare/datasets/package.json
  healthcare/dicom/package.json
  healthcare/fhir/package.json
  healthcare/hl7v2/package.json
  memorystore/redis/package.json
  opencensus/package.json
  package.json
  run/hello-broken/package.json
  run/helloworld/package.docs.json
  run/idp-sql/package.json
  run/markdown-preview/renderer/package.json
  run/pubsub/package.json
Labels: samples

#2667 chore(functions/v2): fix failing logging tests
  functions/v2/cloudEventLogging/package.json
  functions/v2/cloudEventLogging/test/index.test.js
  functions/v2/httpLogging/test/index.test.js
Labels: api: cloudfunctions, samples

#2665 chore(functions/v2): add tests to GH actions
  .github/workflows/functions-v2-cloudeventlogging.yaml
  .github/workflows/functions-v2-httplogging.yaml
  functions/v2/cloudEventLogging/package.json
  functions/v2/httpLogging/package.json
Labels: api: cloudfunctions, samples
