Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-04, with the labels that each got.

#2582 build(deps):upgrade deps in action for appengine storage flex and standard
  .github/workflows/appengine-storage-flexible.yaml
  .github/workflows/appengine-storage-standard.yaml
  appengine/storage/flexible/system-test/app.test.js
  appengine/storage/standard/system-test/app.test.js
Labels: automerge, samples

#2580 build(deps):Update google-github-actions, actions/checkout, and setup-node for appengine/typescript
  .github/workflows/appengine-typescript.yaml
  appengine/typescript/index.ts
  appengine/typescript/test/app.test.js
Labels: samples

#2579 build(deps): Update google-github-actions, actions/checkout, and setup-node for appengine/metadata
  .github/workflows/appengine-metadata-flexible.yaml
  appengine/metadata/flexible/test/server.test.js
Labels: samples

#2590 build: renovate bot renovate/actions GitHub script 6.x
  .github/workflows/appengine-analytics.yaml
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/appengine-datastore.yaml
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/appengine-memcached.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/appengine-static-files.yaml
  .github/workflows/appengine-twilio.yaml
  .github/workflows/appengine-websockets.yaml
  .github/workflows/auth.yaml
  .github/workflows/cloud-tasks-function.yaml
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/containerengine-hello-world.yaml
  .github/workflows/datacatalog-cloud-client.yaml
  .github/workflows/datacatalog-quickstart.yaml
  .github/workflows/datastore-functions.yaml
  .github/workflows/endpoints-getting-started-grpc.yaml
  .github/workflows/endpoints-getting-started.yaml
  .github/workflows/functions-firebase.yaml
  .github/workflows/functions-helloworld.yaml
  .github/workflows/functions-http.yaml
  .github/workflows/functions-pubsub.yaml
  .github/workflows/functions-scheduleinstance.yaml
  .github/workflows/functions-security.yaml
  .github/workflows/functions-slack.yaml
  .github/workflows/functions-spanner.yaml
  .github/workflows/functions-speech-to-speech-functions.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
  .github/workflows/monitoring-opencensus.yaml
  .github/workflows/monitoring-prometheus.yaml
  .github/workflows/opencensus.yaml
Labels: samples

#2593 build: update renovate bot renovate/actions setup node 3.x, and checkout to 3.x, and move checkout before auth
  .github/workflows/appengine-analytics.yaml
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/appengine-datastore.yaml
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/appengine-memcached.yaml
  .github/workflows/appengine-metadata-flexible.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/appengine-static-files.yaml
  .github/workflows/appengine-storage-standard.yaml
  .github/workflows/appengine-twilio.yaml
  .github/workflows/appengine-websockets.yaml
  .github/workflows/auth.yaml
  .github/workflows/ci.yaml
  .github/workflows/cloud-tasks-function.yaml
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/containerengine-hello-world.yaml
  .github/workflows/datacatalog-cloud-client.yaml
  .github/workflows/datacatalog-quickstart.yaml
  .github/workflows/datastore-functions.yaml
  .github/workflows/endpoints-getting-started-grpc.yaml
  .github/workflows/endpoints-getting-started.yaml
  .github/workflows/functions-firebase.yaml
  .github/workflows/functions-helloworld.yaml
  .github/workflows/functions-http.yaml
  .github/workflows/functions-pubsub.yaml
  .github/workflows/functions-scheduleinstance.yaml
  .github/workflows/functions-security.yaml
  .github/workflows/functions-slack.yaml
  .github/workflows/functions-spanner.yaml
  .github/workflows/functions-speech-to-speech-functions.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
  .github/workflows/monitoring-opencensus.yaml
  .github/workflows/monitoring-prometheus.yaml
  .github/workflows/opencensus.yaml
Labels: samples

#2594 build: ugprade googleapis. winston, and functions/framework
  datastore/functions/package.json
  functions/billing/package.json
  functions/helloworld/package.json
  functions/imagemagick/package.json
  functions/pubsub/package.json
  functions/speech-to-speech/functions/package.json
  functions/v2/package.json
  run/idp-sql/package.json
Labels: samples

#2585 feat(cloudsql/postgres): update to V2 sample.
  .kokoro/build.sh
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/app.standard.yaml
  cloud-sql/postgres/knex/connect-tcp.js
  cloud-sql/postgres/knex/connect-unix.js
  cloud-sql/postgres/knex/deployment.yaml
  cloud-sql/postgres/knex/index.js
  cloud-sql/postgres/knex/package.json
  cloud-sql/postgres/knex/server/server.js
  cloud-sql/postgres/knex/test/server.test.js
  cloud-sql/postgres/knex/views/index.pug
Labels: api: cloudsql, samples

#2576 feat(cloudsql/mysql): update to V2 sample
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql/app.standard.yaml
  cloud-sql/mysql/mysql/connect-tcp.js
  cloud-sql/mysql/mysql/connect-unix.js
  cloud-sql/mysql/mysql/deployment.yaml
  cloud-sql/mysql/mysql/index.js
  cloud-sql/mysql/mysql/package.json
  cloud-sql/mysql/mysql/server/server.js
  cloud-sql/mysql/mysql/test/server-unix.test.js
  cloud-sql/mysql/mysql/test/server.test.js
  cloud-sql/mysql/mysql/views/index.pug
Labels: api: cloudsql, samples

#2586 feat(cloudsql/sqlserver): update to V2 sample.
  .kokoro/build.sh
  cloud-sql/sqlserver/mssql/README.md
  cloud-sql/sqlserver/mssql/app.yaml
  cloud-sql/sqlserver/mssql/connect-tcp.js
  cloud-sql/sqlserver/mssql/deployment.yaml
  cloud-sql/sqlserver/mssql/index.js
  cloud-sql/sqlserver/mssql/package.json
  cloud-sql/sqlserver/mssql/server/server.js
  cloud-sql/sqlserver/mssql/test/server.test.js
  cloud-sql/sqlserver/mssql/views/index.pug
Labels: api: cloudsql, samples

#2587 chore(functions/storage): clarify comments
  functions/helloworld/index.js
Labels: api: cloudfunctions, samples

#2601 chore(cloudsql): add comments around env. vars for secret manager
  cloud-sql/mysql/mysql/connect-unix.js
  cloud-sql/postgres/knex/connect-unix.js
Labels: api: cloudsql, samples

#2602 chore(cloudsql): update comments with proper dialects and method names
  cloud-sql/mysql/mysql/connect-tcp.js
  cloud-sql/mysql/mysql/connect-unix.js
  cloud-sql/postgres/knex/connect-tcp.js
  cloud-sql/postgres/knex/connect-unix.js
  cloud-sql/sqlserver/mssql/connect-tcp.js
Labels: api: cloudsql, samples

#2607 chore(run/jobs): update number of tasks run
  run/jobs/index.js
  run/jobs/test/e2e_test_setup.yaml
  run/jobs/test/index.test.js
  run/jobs/test/system.test.js
Labels: api: run, samples

#2619 chore(cloudsql): update dir path for unix socket proxy launch command
  cloud-sql/mysql/mysql/README.md
  cloud-sql/postgres/knex/README.md
Labels: api: cloudsql, samples

#2605 chore(functions/ocr): remove unused dependency
  functions/ocr/app/package.json
Labels: api: cloudfunctions, samples

#2603 chore(functions/helloworld): update product name
  functions/helloworld/index.js
Labels: api: cloudfunctions, samples

#2610 chore(functions): move helloPubSub to separate directory
  .github/workflows/functions-v2-hellopubsub.yaml
  functions/v2/helloPubSub/index.js
  functions/v2/helloPubSub/package.json
  functions/v2/helloPubSub/test/index.test.js
Labels: api: cloudfunctions, samples

#2596 feat: adding cloud event structured logging sample
  functions/v2/cloud-event-logging/index.js
  functions/v2/cloud-event-logging/package.json
  functions/v2/cloud-event-logging/test/index.test.js
Labels: samples

#2611 chore(functions): move helloAuditLogging to separate directory
  .github/workflows/functions-v2-helloauditlog.yaml
  functions/v2/helloAuditLog/index.js
  functions/v2/helloAuditLog/package.json
  functions/v2/helloAuditLog/test/index.test.js
Labels: api: cloudfunctions, samples

#2608 chore(functions): move autoLabelInstance to separate directory
  .github/workflows/functions-v2-autolabelinstance.yaml
  functions/v2/autoLabelInstance/index.js
  functions/v2/autoLabelInstance/package.json
  functions/v2/autoLabelInstance/test/index.test.js
  functions/v2/autoLabelInstance/test/system.test.js
Labels: api: cloudfunctions, samples

#2609 chore(functions): move helloGCS to separate directory
  .github/workflows/functions-v2-hellogcs.yaml
  functions/v2/helloGCS/index.js
  functions/v2/helloGCS/package.json
  functions/v2/helloGCS/test/index.test.js
Labels: api: cloudfunctions, samples

#2628 fix: update sample directory name
  functions/v2/cloudEventLogging/index.js
  functions/v2/cloudEventLogging/package.json
  functions/v2/cloudEventLogging/test/index.test.js
Labels: samples
