Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-03, with the labels that each got.

#2563 build: remove leftover pubsub config
  .kokoro/functions/pubsub.cfg
Labels: samples

#2566 fix(functions/helloworld): include FF import
  functions/helloworld/index.js
Labels: api: cloudfunctions, samples

#2572 chore: extend log polling
  run/jobs/test/system.test.js
Labels: samples

#2577 healthcare API: do not use Healthcare client libraries for FHIR search
  healthcare/fhir/README.md
  healthcare/fhir/searchFhirResourcesGet.js
  healthcare/fhir/searchFhirResourcesPost.js
Labels: samples

#2581 build(deps): build(deps): Update google-github-actions, actions/checkout, and setup-node for cloud-tasks/app
  .github/workflows/cloud-tasks-app.yaml
  cloud-tasks/app/test/create_task.test.js
Labels: automerge, samples
