Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-01, with the labels that each got.

#2462 chore(functions/helloworld): fix failing tests
  functions/helloworld/package.json
  functions/helloworld/test/sample.integration.pubsub.test.js
  functions/helloworld/test/sample.system.http.test.js
  functions/helloworld/test/sample.system.pubsub.test.js
  functions/helloworld/test/sample.system.storage.test.js
Labels: api: cloudfunctions, samples

#2457 feat(functions/v2): update to the new declarative signature APIs
  functions/v2/index.js
  functions/v2/package.json
  functions/v2/test/index.test.js
Labels: api: cloudfunctions, samples

#2473 chore(functions/v2): fix region tags
  functions/v2/index.js
Labels: api: cloudfunctions, samples

#2468 chore(run/websockets): Update VPC access connector name for Cloud Run Test
  run/websockets/test/e2e_test_cleanup.yaml
  run/websockets/test/e2e_test_setup.yaml
  run/websockets/test/system.test.js
Labels: automerge, api: run, samples

#2386 fix(deps): upgrade to @google-cloud/compute version 3
  functions/billing/index.js
  functions/billing/package.json
  functions/billing/test/index.test.js
Labels: automerge, cla: yes, samples

#2474 build: migrate tag enforcer to github actions
  .github/workflows/ci.yaml
  .github/workflows/region-tags-tests.sh
  .kokoro/region-tags-tests.cfg
  .kokoro/require-system-tests.cfg
  .kokoro/require-system-tests.sh
Labels: samples

#2476 chore(functions/helloworld): fix incorrectly documented error behavior
  functions/helloworld/index.js
Labels: api: cloudfunctions, samples

#2475 fix(functions/tips): document correct retry behavior
  functions/tips/index.js
Labels: automerge, api: cloudfunctions, samples

#2400 chore(functions): Move to Node 16 (+ fix flaky tests)
  .kokoro/build.sh
  .kokoro/functions/common.cfg
  functions/helloworld/package.json
  functions/helloworld/test/sample.integration.pubsub.test.js
  functions/helloworld/test/sample.integration.storage.test.js
  functions/helloworld/test/sample.system.pubsub.test.js
  functions/helloworld/test/sample.system.storage.test.js
  functions/pubsub/package.json
Labels: automerge, cla: yes, api: cloudfunctions, samples

#2479 chore(functions/gce-cal): update GCE library + fix typo
  functions/v2/package.json
  functions/v2/test/system.test.js
Labels: api: cloudfunctions, samples

#2480 fix(functions): keep ffProc code within sample
  functions/helloworld/test/sample.integration.storage.test.js
Labels: api: cloudfunctions, samples

#2482 fix(functions/v2): add missing region tags
  functions/v2/index.js
Labels: api: cloudfunctions, samples

#2478 chore(CI): print out Kokoro test logs
  .kokoro/build.sh
Labels: samples

#2477 build: migrate datacatalog to GH actions
  .github/workflows/datacatalog-cloud-client.yaml
  .github/workflows/datacatalog-quickstart.yaml
  .github/workflows/workflows.json
  .kokoro/containerengine-hello-world.cfg
  .kokoro/datacatalog.cfg
  datacatalog/cloud-client/package.json
  datacatalog/cloud-client/system-test/createEntryGroup.test.js
  datacatalog/cloud-client/system-test/createFilesetEntry.test.js
  datacatalog/cloud-client/system-test/lookupEntry.test.js
  datacatalog/quickstart/package.json
  datacatalog/quickstart/system-test/createFilesetEntry.test.js
  datacatalog/quickstart/system-test/deleteFilesetEntry.test.js
Labels: samples

#2486 build: migrate containerengine-hello-world to github actions
  .github/workflows/containerengine-hello-world.yaml
  .github/workflows/workflows.json
  .kokoro/containerengine-hello-world.cfg
Labels: samples
