Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-02, with the labels that each got.

#2494 Update Cloud SQL for SQL Server sample app w/ Kubernetes Engine files.
  cloud-sql/sqlserver/mssql/Dockerfile
  cloud-sql/sqlserver/mssql/deployment.yaml
  cloud-sql/sqlserver/mssql/service-account.yaml
  cloud-sql/sqlserver/mssql/service.yaml
Labels: samples

#2496 build: move appengine building an app to GH actions
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/building-an-app-build.cfg
  .kokoro/appengine/node10/building-an-app-update.cfg
  .kokoro/appengine/node12/building-an-app-build.cfg
  .kokoro/appengine/node12/building-an-app-update.cfg
  appengine/building-an-app/build/test/server.test.js
  appengine/building-an-app/update/test/server.test.js
Labels: samples

#2518 build: move firebase/functions to GH Actions
  .github/workflows/functions-firebase.yaml
  .github/workflows/workflows.json
  .kokoro/functions/firebase.cfg
  functions/firebase/test/index.test.js
Labels: samples

#2520 chore(run): Update failing tests
  run/hello-broken/package.json
  run/image-processing/package.json
  run/markdown-preview/renderer/package.json
  run/pubsub/package.json
  run/system-package/package.json
  run/websockets/test/e2e_test_cleanup.yaml
  run/websockets/test/e2e_test_setup.yaml
  run/websockets/test/system.test.js
Labels: api: run, samples

#2495 build: move appengine-analytics to GH Actions
  .github/workflows/appengine-analytics.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/analytics.cfg
  appengine/analytics/app.js
Labels: samples

#2498 build: move appengine-datastore to GH Actions
  .github/workflows/appengine-datastore.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/datastore.cfg
  .kokoro/appengine/node12/datastore.cfg
  appengine/datastore/app.js
  appengine/datastore/test/app.test.js
Labels: samples

#2499 build: move appengine endpoints to GH Actions
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/endpoints.cfg
  .kokoro/appengine/node12/endpoints.cfg
  appengine/endpoints/app.js
Labels: samples

#2502 build: move appengine/metadata flexible and standard to GH Actions
  .github/workflows/apengine-metadata-flexible.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/metadata-flexible.cfg
  .kokoro/appengine/node10/metadata-standard.cfg
  .kokoro/appengine/node12/metadata-flexible.cfg
  .kokoro/appengine/node12/metadata-standard.cfg
  appengine/metadata/flexible/test/server.test.js
  appengine/metadata/standard/server.js
  appengine/metadata/standard/test/server.test.js
Labels: samples

#2500 build: move appengine hello-world standard and flex to GH actions
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/hello-world-flexible.cfg
  .kokoro/appengine/node10/hello-world-standard.cfg
  .kokoro/appengine/node12/hello-world-flexible.cfg
  .kokoro/appengine/node12/hello-world-standard.cfg
  appengine/hello-world/flexible/test/app.test.js
  appengine/hello-world/standard/test/app.test.js
Labels: samples

#2501 build: move appengine memcached to GH Actions
  .github/workflows/appengine-memcached.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/memcached.cfg
  .kokoro/appengine/node12/memcached.cfg
  appengine/memcached/test/app.test.js
Labels: samples

#2503 build: move appengine/pubsub to GH Actions
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/pubsub.cfg
  .kokoro/appengine/node12/pubsub.cfg
  appengine/pubsub/test/app.test.js
Labels: samples

#2504 build: move appengine/static-files to GH Actions
  .github/workflows/appengine-static-files.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/static-files.cfg
  .kokoro/appengine/node12/static-files.cfg
  appengine/static-files/test/app.test.js
Labels: samples

#2505 build: move appengine storage to GH Actions
  .github/workflows/appengine-storage-flexible.yaml
  .github/workflows/appengine-storage-standard.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/storage-flexible.cfg
  .kokoro/appengine/node10/storage-standard.cfg
  .kokoro/appengine/node12/storage-flexible.cfg
  .kokoro/appengine/node12/storage-standard.cfg
  appengine/storage/flexible/system-test/app.test.js
  appengine/storage/standard/system-test/app.test.js
Labels: samples

#2506 build: move appengine websockets to GH Actions
  .github/workflows/appengine-websockets.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/websockets.cfg
  .kokoro/appengine/node12/websockets.cfg
  appengine/websockets/test/app.test.js
  appengine/websockets/test/index.test.js
Labels: samples

#2507 build: move appengine typescript to GH Actions
  .github/workflows/appengine-typescript.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/typescript.cfg
  .kokoro/appengine/node12/typescript.cfg
  appengine/typescript/test/app.test.js
Labels: samples

#2508 build: move appengine twilio to GH Actions
  .github/workflows/appengine-twilio.yaml
  .github/workflows/workflows.json
  .kokoro/appengine/node10/twilio.cfg
  .kokoro/appengine/node12/twilio.cfg
  appengine/twilio/test/app.test.js
Labels: samples

#2509 build: remove unused functions/background
  .kokoro/functions/background.cfg
Labels: samples

#2510 build: remove unused memorystore/redis test
  .kokoro/memorystore-redis.cfg
Labels: samples

#2511 build: move datastore functions to GH Actions
  .github/workflows/datastore-functions.yaml
  .github/workflows/workflows.json
  .kokoro/datastore-functions.cfg
  datastore/functions/test/index.test.js
Labels: samples

#2497 feat(functions/helloworld): Use declarative syntax for http sample
  functions/helloworld/index.js
  functions/helloworld/package.json
  functions/helloworld/test/sample.unit.http.test.js
Labels: api: cloudfunctions, samples

#2513 build: move functions/security to GH Actions
  .github/workflows/functions-security.yaml
  .github/workflows/workflows.json
  .kokoro/functions/security.cfg
  functions/security/test/index.test.js
Labels: samples

#2514 build: move functions/slack to GH Actions
  .github/workflows/functions-slack.yaml
  .github/workflows/workflows.json
  .kokoro/functions/slack.cfg
  functions/slack/test/index.test.js
Labels: samples

#2515 build: move functions/spanner to GH Actions
  .github/workflows/functions-spanner.yaml
  .github/workflows/workflows.json
  .kokoro/functions/spanner.cfg
  functions/spanner/test/index.test.js
Labels: samples

#2516 build: move functions/http to GH Actions
  .github/workflows/functions-http.yaml
  .github/workflows/workflows.json
  .kokoro/functions/http.cfg
  functions/http/test/index.test.js
Labels: samples

#2531 fix: revert #2383 for composer code
  composer/composer_transform_csv_to_json.js
Labels: samples

#2311 Update sample.integration.http.test.js
  appengine/analytics/app.js
  appengine/building-an-app/build/server.js
  appengine/building-an-app/update/server.js
  appengine/datastore/app.js
  appengine/endpoints/app.js
  appengine/endpoints/test/appListening.test.js
  appengine/hello-world/flexible/app.js
  appengine/hello-world/standard/app.js
  appengine/memcached/app.js
  appengine/memcached/test/app.test.js
  appengine/metadata/flexible/server.js
  appengine/metadata/standard/server.js
  appengine/pubsub/app.js
  appengine/pubsub/test/appListening.test.js
  appengine/static-files/app.js
  appengine/storage/flexible/app.js
  appengine/storage/standard/app.js
  appengine/twilio/app.js
  appengine/typescript/index.ts
  appengine/typescript/test/app.test.js
  appengine/websockets/app.js
  appengine/websockets/test/index.test.js
  cloud-sql/mysql/mysql/server.js
  cloud-sql/postgres/knex/server.js
  cloud-sql/sqlserver/mssql/server.js
  cloud-tasks/app/index.js
  containerengine/hello-world/server.js
  endpoints/getting-started-grpc/system-test/endpoints.test.js
  endpoints/getting-started/app.js
  eventarc/audit-storage/index.js
  eventarc/generic/index.js
  eventarc/pubsub/index.js
  functions/helloworld/test/sample.integration.http.test.js
  run/hello-broken/index.js
  run/helloworld/index.js
  run/idp-sql/index.js
  run/image-processing/index.js
  run/logging-manual/index.js
  run/markdown-preview/editor/index.js
  run/markdown-preview/renderer/index.js
  run/pubsub/index.js
  run/system-package/index.js
  run/websockets/index.js
Labels: cla: yes, samples

#2484 fix cloud-tasks app package.json engines.node
  cloud-tasks/app/package.json
Labels: samples

#2517 build: move functions/scheduleinstance to GH Actions
  .github/workflows/functions-scheduleinstance.yaml
  .github/workflows/workflows.json
  .kokoro/functions/scheduleinstance.cfg
  functions/scheduleinstance/test/index.test.js
Labels: samples

#2522 build: move helloworld to GH Actions
  .github/workflows/run-helloworld.yaml
  .github/workflows/workflows.json
  .kokoro/run/helloworld.cfg
  run/helloworld/test/system.test.js
Labels: samples

#2523 build: move idp-sql to GH Actions
  .github/workflows/run-idp-sql.yaml
  .github/workflows/workflows.json
  .kokoro/run/idp-sql.cfg
  run/idp-sql/package.json
  run/idp-sql/test/app.test.js
  run/idp-sql/test/system.test.js
Labels: samples

#2524 build: move run/imageprocessing to GH Actions
  .github/workflows/run-image-processing.yaml
  .github/workflows/workflows.json
  .kokoro/run/image-processing.cfg
  run/image-processing/test/system.test.js
Labels: samples

#2333 Add Secret Manager integration to Cloud SQL sample apps
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql/package.json
  cloud-sql/mysql/mysql/server.js
  cloud-sql/postgres/knex/README.md
  cloud-sql/postgres/knex/package.json
  cloud-sql/postgres/knex/server.js
  cloud-sql/sqlserver/mssql/README.md
  cloud-sql/sqlserver/mssql/package.json
  cloud-sql/sqlserver/mssql/server.js
Labels: cla: yes, samples

#2526 build: move run/system-package to GH Actions
  .github/workflows/run-system-package.yaml
  .github/workflows/workflows.json
  .kokoro/run/system-package.cfg
  run/system-package/test/system.test.js
Labels: samples

#2527 build: move run/pubsub to GH Actions
  .github/workflows/run-pubsub.yaml
  .github/workflows/workflows.json
  .kokoro/run/pubsub.cfg
  run/pubsub/test/app.test.js
  run/pubsub/test/system.test.js
Labels: samples

#2529 build: move logging manual to GH Actions
  .github/workflows/run-logging-manual.yaml
  .github/workflows/workflows.json
  .kokoro/run/logging-manual.cfg
  run/logging-manual/test/system.test.js
Labels: samples

#2525 build: move run/jobs to GH Actions
  .github/workflows/run-jobs.yaml
  .github/workflows/workflows.json
  .kokoro/run/jobs.cfg
  run/jobs/test/index.test.js
Labels: samples

#2535 test: rename the job to match the sample
  .github/workflows/run-system-package.yaml
Labels: samples

#2537 Revert "chore(deps): update dependency got to v12"
  eventarc/audit-storage/package.json
  eventarc/generic/package.json
  eventarc/pubsub/package.json
  run/hello-broken/package.json
  run/helloworld/package.json
  run/idp-sql/package.json
  run/image-processing/package.json
  run/logging-manual/package.json
  run/markdown-preview/editor/package.json
  run/markdown-preview/renderer/package.json
  run/pubsub/package.json
  run/system-package/package.json
  run/websockets/package.json
Labels: samples

#2485 samples(scheduler): update nodejs-compute usage in scheduler
  functions/scheduleinstance/index.js
  functions/scheduleinstance/package.json
  functions/scheduleinstance/test/index.test.js
Labels: api: cloudscheduler, samples

#2539 build: remove unused opencensus config w/ no corresponding Kokoro config, add opencensus test in GH Actions
  .github/workflows/opencensus.yaml
  .kokoro/opencensus.cfg
  opencensus/system-test/metrics-quickstart.test.js
Labels: samples

#2544 fix(functions/firestore): fix incorrect function signature
  functions/firebase/index.js
  functions/firebase/test/index.test.js
Labels: kokoro:force-run, api: cloudfunctions, samples

#2532 chore: add E2E tests for Jobs
  run/jobs/.gcloudignore
  run/jobs/README.md
  run/jobs/index.js
  run/jobs/package.json
  run/jobs/test/e2e_test_cleanup.yaml
  run/jobs/test/e2e_test_setup.yaml
  run/jobs/test/retry.sh
  run/jobs/test/system.test.js
Labels: samples

#2560 feat: Streamline `Downscope` sample
  auth/downscoping.js
Labels: samples

#2558 chore(run/websockets): fix lint
  run/websockets/test/system.test.js
Labels: api: run, samples

#2543 build: migrate auth to GH Actions
  .github/workflows/auth.yaml
  .github/workflows/workflows.json
  .kokoro/auth.cfg
  auth/system-test/auth.test.js
  auth/system-test/downscoping.test.js
Labels: samples

#2547 build: migrate functions/pubsub to GH Actions
  .github/workflows/functions-pubsub.yaml
  functions/pubsub/test/index.test.js
Labels: samples

#2545 build: migrate functions/helloworld
  .github/workflows/functions-helloworld.yaml
  .github/workflows/workflows.json
  .kokoro/functions/functions-helloworld.cfg
  .kokoro/functions/functions-helloworld.sh
  .kokoro/functions/helloworld.cfg
  functions/helloworld/test/index.test.js
Labels: automerge, samples

#2550 build: migrate functions/speechtospeech to GH Actions
  .github/workflows/functions-speech-to-speech-functions.yaml
  .kokoro/functions/speech-to-speech.cfg
  functions/speech-to-speech/functions/test/index.test.js
Labels: automerge, samples

#2562 chore(scheduler): fix iterator
  functions/scheduleinstance/index.js
  functions/scheduleinstance/test/index.test.js
Labels: kokoro:force-run, api: cloudscheduler, samples

#2556 build: remove unused UUID Kokoro config
  .kokoro/functions/uuid.cfg
Labels: samples

#2564 chore(functions/http): update Busboy invocation
  functions/http/index.js
Labels: kokoro:run, api: cloudfunctions, samples
