Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-09, with the labels that each got.

#2746 Update SSL syntax in cloud sql postgres sample app.
  cloud-sql/postgres/knex/connect-tcp.js
Labels: samples

#2753 build: do not rebase renovate PRs
  .github/workflows/appengine-analytics.yaml
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/appengine-datastore.yaml
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/appengine-memcached.yaml
  .github/workflows/appengine-metadata-flexible.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/appengine-static-files.yaml
  .github/workflows/appengine-storage-flexible.yaml
  .github/workflows/appengine-storage-standard.yaml
  .github/workflows/appengine-twilio.yaml
  .github/workflows/appengine-typescript.yaml
  .github/workflows/appengine-websockets.yaml
  renovate.json
Labels: samples

#2754 build: set timeout to 60 minutes
  .github/workflows/appengine-analytics.yaml
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/appengine-datastore.yaml
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/appengine-memcached.yaml
  .github/workflows/appengine-metadata-flexible.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/appengine-static-files.yaml
  .github/workflows/appengine-storage-flexible.yaml
  .github/workflows/appengine-storage-standard.yaml
  .github/workflows/appengine-twilio.yaml
  .github/workflows/appengine-typescript.yaml
  .github/workflows/appengine-websockets.yaml
  .github/workflows/auth.yaml
  .github/workflows/ci.yaml.template
  .github/workflows/cloud-tasks-app.yaml
  .github/workflows/cloud-tasks-function.yaml
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/containerengine-hello-world.yaml
  .github/workflows/datacatalog-cloud-client.yaml
  .github/workflows/datacatalog-quickstart.yaml
  .github/workflows/datastore-functions.yaml
  .github/workflows/endpoints-getting-started-grpc.yaml
  .github/workflows/endpoints-getting-started.yaml
  .github/workflows/functions-firebase.yaml
  .github/workflows/functions-helloworld.yaml
  .github/workflows/functions-http.yaml
  .github/workflows/functions-pubsub.yaml
  .github/workflows/functions-scheduleinstance.yaml
  .github/workflows/functions-security.yaml
  .github/workflows/functions-slack.yaml
  .github/workflows/functions-spanner.yaml
  .github/workflows/functions-speech-to-speech-functions.yaml
  .github/workflows/functions-v2-autolabelinstance.yaml
  .github/workflows/functions-v2-cloudeventlogging.yaml
  .github/workflows/functions-v2-helloauditlog.yaml
  .github/workflows/functions-v2-hellobigquery.yaml
  .github/workflows/functions-v2-hellogcs.yaml
  .github/workflows/functions-v2-hellopubsub.yaml
  .github/workflows/functions-v2-httplogging.yaml
  .github/workflows/functions-v2-imagemagick.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
  .github/workflows/monitoring-opencensus.yaml
  .github/workflows/monitoring-prometheus.yaml
  .github/workflows/opencensus.yaml
Labels: samples

#2742 samples(healthcare v1): initial consent store CRUD method samples
  healthcare/consent/README.md
  healthcare/consent/createConsentStore.js
  healthcare/consent/deleteConsentStore.js
  healthcare/consent/getConsentStore.js
  healthcare/consent/getConsentStoreIamPolicy.js
  healthcare/consent/listConsentStores.js
  healthcare/consent/package.json
  healthcare/consent/patchConsentStore.js
  healthcare/consent/setConsentStoreIamPolicy.js
  healthcare/consent/system-test/consent_stores.test.js
Labels: samples

#2757 fix: Update node version to LTS because app-engine flex does not support node >= 18
  appengine/hello-world/flexible/package.json
Labels: samples

#2751 Wait for logs for Cloud Run Jobs
  run/jobs/package.json
  run/jobs/test/system.test.js
Labels: samples

#2727 feat(appengine): upgrade Node version to v16
  appengine/analytics/app.standard.yaml
  appengine/analytics/package.json
  appengine/building-an-app/build/app.yaml
  appengine/building-an-app/build/package.json
  appengine/building-an-app/update/app.yaml
  appengine/building-an-app/update/package.json
  appengine/datastore/app.standard.yaml
  appengine/datastore/package.json
  appengine/endpoints/package.json
  appengine/hello-world/standard/app.yaml
  appengine/memcached/app.standard.yaml
  appengine/memcached/package.json
  appengine/metadata/flexible/package.json
  appengine/metadata/standard/app.yaml
  appengine/metadata/standard/package.json
  appengine/pubsub/app.standard.yaml
  appengine/pubsub/package.json
  appengine/static-files/app.standard.yaml
  appengine/static-files/package.json
  appengine/storage/standard/app.yaml
  appengine/twilio/app.standard.yaml
  appengine/twilio/package.json
  appengine/typescript/app.yaml
  appengine/typescript/package.json
  appengine/websockets/package.json
  cloud-tasks/app/app.yaml
Labels: api: appengine, samples

#2761 docs: skip datastore test as they are taking long
  datastore/functions/test/index.test.js
Labels: samples

#2767 fix: github action doc failures for missing prometheus svg
  monitoring/prometheus/README.md
Labels: samples

#2763 feat(iam): add iam deny samples
  .github/workflows/iam-deny.yml
  iam/deny/createDenyPolicy.js
  iam/deny/deleteDenyPolicy.js
  iam/deny/getDenyPolicy.js
  iam/deny/listDenyPolicies.js
  iam/deny/updateDenyPolicy.js
  iam/package.json
  iam/test/deny.test.js
Labels: api: iam, samples
