Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-11, with the labels that each got.

#2790 Separate httpMethods sample, and use matrix-driven tests
  .github/workflows/functions-http.yaml
  .github/workflows/workflows.json
  functions/http/httpMethods/README.md
  functions/http/httpMethods/index.js
  functions/http/httpMethods/package.json
  functions/http/httpMethods/test/index.test.js
Labels: samples

#2795 testing: update ci.yaml.template dependency versions
  .github/workflows/ci.yaml.template
Labels: samples

#2737 chore(functions/firebase): split samples into dirs
  .github/workflows/functions-firebase.yaml
  functions/firebase/helloAnalytics/index.js
  functions/firebase/helloAnalytics/package.json
  functions/firebase/helloAnalytics/test/index.test.js
  functions/firebase/helloAuth/index.js
  functions/firebase/helloAuth/package.json
  functions/firebase/helloAuth/test/index.test.js
  functions/firebase/helloFirestore/index.js
  functions/firebase/helloFirestore/package.json
  functions/firebase/helloFirestore/test/index.test.js
  functions/firebase/helloRTDB/index.js
  functions/firebase/helloRTDB/package.json
  functions/firebase/helloRTDB/test/index.test.js
  functions/firebase/helloRemoteConfig/index.js
  functions/firebase/helloRemoteConfig/package.json
  functions/firebase/helloRemoteConfig/test/index.test.js
  functions/firebase/makeUpperCase/index.js
  functions/firebase/makeUpperCase/package.json
  functions/firebase/makeUpperCase/test/index.test.js
Labels: api: cloudfunctions, samples

#2730 chore(concepts/termination): split samples into directories
  .github/workflows/functions-concepts.yaml
  functions/concepts/backgroundTermination/index.js
  functions/concepts/backgroundTermination/package.json
  functions/concepts/httpTermination/index.js
  functions/concepts/httpTermination/package.json
Labels: samples

#2733 chore(functions/concepts/index.js): split samples into dirs
  .github/workflows/functions-concepts.yaml
  functions/concepts/afterResponse/index.js
  functions/concepts/afterResponse/package.json
  functions/concepts/afterTimeout/index.js
  functions/concepts/afterTimeout/package.json
  functions/concepts/filesystem/index.js
  functions/concepts/filesystem/package.json
  functions/concepts/requests/index.js
  functions/concepts/requests/package.json
  functions/concepts/stateless/index.js
  functions/concepts/stateless/package.json
Labels: api: cloudfunctions, samples

#2735 chore(functions/tips): split samples into dirs
  .github/workflows/functions-tips.yaml
  functions/tips/avoidInfiniteRetries/index.js
  functions/tips/avoidInfiniteRetries/package.json
  functions/tips/connectionPools/index.js
  functions/tips/connectionPools/package.json
  functions/tips/gcpApiCall/index.js
  functions/tips/gcpApiCall/package.json
  functions/tips/gcpApiCall/test/index.test.js
  functions/tips/lazyGlobals/index.js
  functions/tips/lazyGlobals/package.json
  functions/tips/retry/index.js
  functions/tips/retry/package.json
  functions/tips/retry/test/index.test.js
  functions/tips/scopeDemo/index.js
  functions/tips/scopeDemo/package.json
Labels: api: cloudfunctions, samples

#2732 chore(functions/pubsub): split samples into dirs
  .github/workflows/functions-pubsub.yaml
  functions/pubsub/README.md
  functions/pubsub/publish/index.js
  functions/pubsub/publish/package.json
  functions/pubsub/publish/test/index.test.js
  functions/pubsub/subscribe/index.js
  functions/pubsub/subscribe/package.json
  functions/pubsub/subscribe/test/index.test.js
Labels: api: cloudfunctions, samples

#2804 Move location of Cloud SQL app.standard.yaml file
  cloud-sql/sqlserver/mssql/app.standard.yaml
Labels: samples

#2805 build: run checkout before authentication
  .github/workflows/ci.yaml.njk
  .github/workflows/generate.js
Labels: samples

#2808 migrate code from googleapis/nodejs-media-translation
  .github/workflows/mediatranslation.yaml
  .github/workflows/workflows.json
  mediatranslation/package.json
  mediatranslation/quickstart.js
  mediatranslation/resources/audio.raw
  mediatranslation/test/quickstart.test.js
  mediatranslation/test/translate_from_file.test.js
  mediatranslation/translate_from_file.js
  mediatranslation/translate_from_mic.js
Labels: samples

#2809 chore: delete orgpolicy
  .github/workflows/orgpolicy.yaml
  .github/workflows/workflows.json
  orgpolicy/README.md
  orgpolicy/package.json
  orgpolicy/quickstart.js
  orgpolicy/test/quickstart.js
Labels: automerge, samples

#2817 chore(contact-center): migrate code from googleapis/nodejs-contact-center-insights
  .github/workflows/contact-center-insights.yaml
  .github/workflows/workflows.json
  CODEOWNERS
  contact-center-insights/createAnalysis.js
  contact-center-insights/createConversation.js
  contact-center-insights/createConversationWithTtl.js
  contact-center-insights/createIssueModel.js
  contact-center-insights/createPhraseMatcherAllOf.js
  contact-center-insights/createPhraseMatcherAnyOf.js
  contact-center-insights/enablePubSubNotifications.js
  contact-center-insights/exportToBigquery.js
  contact-center-insights/getOperation.js
  contact-center-insights/package.json
  contact-center-insights/setProjectTtl.js
  contact-center-insights/test/createAnalysis.test.js
  contact-center-insights/test/createConversation.test.js
  contact-center-insights/test/createConversationWithTtl.test.js
  contact-center-insights/test/createIssueModel.test.js
  contact-center-insights/test/createPhraseMatcherAllOf.test.js
  contact-center-insights/test/createPhraseMatcherAnyOf.test.js
  contact-center-insights/test/enablePubSubNotifications.test.js
  contact-center-insights/test/exportToBigquery.test.js
  contact-center-insights/test/getOperation.test.js
  contact-center-insights/test/setProjectTtl.test.js
Labels: automerge, samples

#2822 ci: add option to generate one workflow
  .github/workflows/generate.js
  CONTRIBUTING.md
Labels: samples

#2824 migrate code from googleapis/nodejs-cloudbuild
  .github/workflows/cloudbuild.yaml
  .github/workflows/workflows.json
  CODEOWNERS
  cloudbuild/listBuildTriggers.js
  cloudbuild/package.json
  cloudbuild/quickstart.js
  cloudbuild/system-test/.eslintrc.yml
  cloudbuild/system-test/samples.js
Labels: samples

#2829 chore(container-analysis): add DEEPO to CODEOWNERS
  CODEOWNERS
Labels: api: containeranalysis, samples

#2811 Update Cloud SQL sample app.flexible.yaml runtime
  cloud-sql/mysql/mysql/app.flexible.yaml
  cloud-sql/postgres/knex/app.flexible.yaml
  cloud-sql/sqlserver/mssql/app.flexible.yaml
Labels: samples

#2830 chore(CODEOWNERS): fix container != container-analysis
  CODEOWNERS
Labels: samples

#2828 ci: update workflow template
  .github/workflows/ci.yaml.njk
Labels: samples

#2838 chore: fix typo + broken link
  memorystore/redis/README.md
Labels: samples

#2834 migrate code from googleapis/nodejs-containeranalysis
  .github/workflows/container-analysis-snippets.yaml
  .github/workflows/workflows.json
  container-analysis/snippets/.eslintrc.yml
  container-analysis/snippets/createNote.js
  container-analysis/snippets/createOccurrence.js
  container-analysis/snippets/deleteNote.js
  container-analysis/snippets/deleteOccurrence.js
  container-analysis/snippets/getDiscoveryInfo.js
  container-analysis/snippets/getNote.js
  container-analysis/snippets/getOccurrence.js
  container-analysis/snippets/highVulnerabilitiesForImage.js
  container-analysis/snippets/occurrencePubSub.js
  container-analysis/snippets/occurrencesForImage.js
  container-analysis/snippets/occurrencesForNote.js
  container-analysis/snippets/package.json
  container-analysis/snippets/pollDiscoveryOccurrenceFinished.js
  container-analysis/snippets/quickstart.js
  container-analysis/snippets/test/.eslintrc.yml
  container-analysis/snippets/test/containerAnalysis.test.js
  container-analysis/snippets/test/tests.js
  container-analysis/snippets/test/util.js
  container-analysis/snippets/vulnerabilityOccurrencesForImage.js
Labels: samples

#2825 testing(cloud-tasks): Broaden path matching for test runner
  .github/workflows/cloud-tasks.yaml
Labels: api: cloudtasks, samples

#2850 chore(profiler): remove samples from hand-written library
  profiler/app.js
  profiler/package.json
  profiler/snippets.js
Labels: api: cloudprofiler, samples

#2856 migrate code from googleapis/nodejs-asset
  .github/workflows/workflows.json
  asset/snippets/analyzeIamPolicy.js
  asset/snippets/analyzeIamPolicyLongrunningBigquery.js
  asset/snippets/analyzeIamPolicyLongrunningGcs.js
  asset/snippets/createFeed.js
  asset/snippets/deleteFeed.js
  asset/snippets/exportAssets.js
  asset/snippets/exportAssetsBigquery.js
  asset/snippets/getBatchAssetHistory.js
  asset/snippets/getBatchEffectiveIamPolicies.js
  asset/snippets/getFeed.js
  asset/snippets/listAssets.js
  asset/snippets/listFeeds.js
  asset/snippets/package.json
  asset/snippets/searchAllIamPolicies.js
  asset/snippets/searchAllResources.js
  asset/snippets/test/samples.test.js
  asset/snippets/updateFeed.js
Labels: samples

#2868 Adds quickstart samples referenced in DevSite
  monitoring/snippets/quickstart.js
  monitoring/snippets/test/quickstart.test.js
Labels: samples

#2872 migrate code from googleapis/nodejs-text-to-speech
  .github/workflows/texttospeech.yaml
  .github/workflows/workflows.json
  CODEOWNERS
  texttospeech/.eslintrc.yml
  texttospeech/audioProfile.js
  texttospeech/hello.mp3
  texttospeech/listVoices.js
  texttospeech/package.json
  texttospeech/quickstart.js
  texttospeech/resources/example.ssml
  texttospeech/resources/example.txt
  texttospeech/resources/expected_example.mp3
  texttospeech/resources/hello.ssml
  texttospeech/resources/hello.txt
  texttospeech/ssmlAddresses.js
  texttospeech/synthesize.js
  texttospeech/test/.eslintrc.yml
  texttospeech/test/audioProfile.test.js
  texttospeech/test/listVoices.test.js
  texttospeech/test/quickstart.test.js
  texttospeech/test/ssmlAddresses.test.js
  texttospeech/test/synthesize.test.js
Labels: samples

#2874 migrate code from googleapis/nodejs-secret-manager
  .github/workflows/secret-manager.yaml
  .github/workflows/workflows.json
  secret-manager/accessSecretVersion.js
  secret-manager/addSecretVersion.js
  secret-manager/createSecret.js
  secret-manager/createUmmrSecret.js
  secret-manager/deleteSecret.js
  secret-manager/destroySecretVersion.js
  secret-manager/disableSecretVersion.js
  secret-manager/enableSecretVersion.js
  secret-manager/getSecret.js
  secret-manager/getSecretVersion.js
  secret-manager/iamGrantAccess.js
  secret-manager/iamRevokeAccess.js
  secret-manager/listSecretVersions.js
  secret-manager/listSecrets.js
  secret-manager/package.json
  secret-manager/quickstart.js
  secret-manager/test/.eslintrc.yml
  secret-manager/test/secretmanager.test.js
  secret-manager/updateSecret.js
  secret-manager/updateSecretWithAlias.js
Labels: samples

#2867 migrate code from googleapis/nodejs-security-center
  .github/workflows/security-center-snippets.yaml
  .github/workflows/workflows.json
  security-center/snippets/package.json
  security-center/snippets/system-test/v1/assetSecurityMarks.test.js
  security-center/snippets/system-test/v1/findings.test.js
  security-center/snippets/system-test/v1/listAllAssets.test.js
  security-center/snippets/system-test/v1/listAssetsAndChanges.test.js
  security-center/snippets/system-test/v1/listAssetsAtTime.test.js
  security-center/snippets/system-test/v1/listFilteredAssets.test.js
  security-center/snippets/system-test/v1/notifications.test.js
  security-center/snippets/system-test/v1/orgSettings.test.js
  security-center/snippets/v1/addDeleteSecurityMarks.js
  security-center/snippets/v1/addFindingSecurityMarks.js
  security-center/snippets/v1/addSecurityMarks.js
  security-center/snippets/v1/createFinding.js
  security-center/snippets/v1/createFindingSourceProperties.js
  security-center/snippets/v1/createNotificationConfig.js
  security-center/snippets/v1/createSource.js
  security-center/snippets/v1/deleteNotificationConfig.js
  security-center/snippets/v1/deleteSecurityMarks.js
  security-center/snippets/v1/enableAssetDiscovery.js
  security-center/snippets/v1/getNotificationConfig.js
  security-center/snippets/v1/getOrganizationSettings.js
  security-center/snippets/v1/getSource.js
  security-center/snippets/v1/getSourceIam.js
  security-center/snippets/v1/listAllAssets.js
  security-center/snippets/v1/listAllFindings.js
  security-center/snippets/v1/listAllSources.js
  security-center/snippets/v1/listAssetsAndChanges.js
  security-center/snippets/v1/listAssetsAtTime.js
  security-center/snippets/v1/listAssetsWithSecurityMarks.js
  security-center/snippets/v1/listFilteredAssets.js
  security-center/snippets/v1/listFilteredFindings.js
  security-center/snippets/v1/listFindingsAtTime.js
  security-center/snippets/v1/listFindingsWithSecurityMarks.js
  security-center/snippets/v1/listNotificationConfigs.js
  security-center/snippets/v1/receiveNotifications.js
  security-center/snippets/v1/setFindingState.js
  security-center/snippets/v1/setSourceIam.js
  security-center/snippets/v1/testIam.js
  security-center/snippets/v1/updateFindingSourceProperties.js
  security-center/snippets/v1/updateNotificationConfig.js
  security-center/snippets/v1/updateSource.js
Labels: samples

#2854 migrate code from googleapis/nodejs-dialogflow-cx
  .github/workflows/dialogflow-cx.yaml
  .github/workflows/workflows.json
  dialogflow-cx/configure-webhook-to-set-form-parameter-as-optional-or-required.js
  dialogflow-cx/create-agent.js
  dialogflow-cx/create-page.js
  dialogflow-cx/delete-page.js
  dialogflow-cx/detect-intent-audio.js
  dialogflow-cx/detect-intent-disabled-webhook.js
  dialogflow-cx/detect-intent-event.js
  dialogflow-cx/detect-intent-streaming.js
  dialogflow-cx/detect-intent-synthesize-tts-response.js
  dialogflow-cx/detect-intent-text.js
  dialogflow-cx/detect-intent-with-intent-input.js
  dialogflow-cx/detect-intent-with-sentiment-analysis.js
  dialogflow-cx/list-intents.js
  dialogflow-cx/list-page.js
  dialogflow-cx/list-testcase-results.js
  dialogflow-cx/long-running-operation.js
  dialogflow-cx/package.json
  dialogflow-cx/quickstart.js
  dialogflow-cx/resources/book_a_room.wav
  dialogflow-cx/resources/output.wav
  dialogflow-cx/streaming-detect-intent-partial-response.js
  dialogflow-cx/test/configure-webhook-to-set-form-parameter-as-optional-or-required.js
  dialogflow-cx/test/create-agent.test.js
  dialogflow-cx/test/detect-intent-audio.test.js
  dialogflow-cx/test/detect-intent-disabled-webhook-test.js
  dialogflow-cx/test/detect-intent-event-test.js
  dialogflow-cx/test/detect-intent-sentiment-analysis-test.js
  dialogflow-cx/test/detect-intent-synthesize-tts-response-test.js
  dialogflow-cx/test/detect-intent-text.test.js
  dialogflow-cx/test/detect-intent-with-intent-input-test.js
  dialogflow-cx/test/list-intents.test.js
  dialogflow-cx/test/list_testcase-results.test.js
  dialogflow-cx/test/long-running-operation.test.js
  dialogflow-cx/test/page-management.test.js
  dialogflow-cx/test/quickstart.js
  dialogflow-cx/test/streaming-detect-intent-partial-response-test.js
  dialogflow-cx/test/update-intent.test.js
  dialogflow-cx/test/webhook-configure-session-parameters-test.js
  dialogflow-cx/test/webhook-validate-form-parameter-test.js
  dialogflow-cx/test/webhook.test.js
  dialogflow-cx/update-intent.js
  dialogflow-cx/webhook-configure-session-parameters.js
  dialogflow-cx/webhook-validate-form-parameter.js
  dialogflow-cx/webhooks.js
Labels: samples

#2861 chore(debundle-samples): clean up now redundant samples + tests
  .kokoro/build.sh
  functions/concepts/index.js
  functions/concepts/package.json
  functions/concepts/termination.js
  functions/firebase/index.js
  functions/firebase/package.json
  functions/firebase/test/index.test.js
  functions/helloworld/index.js
  functions/helloworld/package.json
  functions/helloworld/test/index.test.js
  functions/helloworld/test/sample.integration.http.test.js
  functions/helloworld/test/sample.integration.pubsub.test.js
  functions/helloworld/test/sample.integration.storage.test.js
  functions/helloworld/test/sample.system.http.test.js
  functions/helloworld/test/sample.system.pubsub.test.js
  functions/helloworld/test/sample.system.storage.test.js
  functions/helloworld/test/sample.unit.http.test.js
  functions/helloworld/test/sample.unit.pubsub.test.js
  functions/helloworld/test/sample.unit.storage.test.js
  functions/helloworld/test/test.txt
  functions/http/index.js
  functions/http/package.json
  functions/http/test/index.test.js
  functions/log/index.js
  functions/log/package.json
  functions/log/test/index.test.js
  functions/pubsub/index.js
  functions/pubsub/package.json
  functions/pubsub/test/index.test.js
  functions/tips/index.js
  functions/tips/package.json
  functions/tips/test/index.test.js
Labels: type: cleanup, samples

#2871 Filter by image digest rather than image tag
  container-analysis/snippets/occurrencesForImage.js
Labels: samples

#2882 feat(gcfv2): migrate OCR to Cloud Functions v2
  functions/v2/ocr/README.md
  functions/v2/ocr/app/.gcloudignore
  functions/v2/ocr/app/index.js
  functions/v2/ocr/app/package.json
  functions/v2/ocr/app/test/index.test.js
  functions/v2/ocr/images/menu.jpg
  functions/v2/ocr/images/sign.png
Labels: samples

#2870 testing: skip unrelated Cloud Run testing on PR checks
  .kokoro/build-with-run.sh
Labels: samples

#2766 Update busboy sample to use on('close')
  functions/http/package.json
  functions/http/uploadFile/index.js
Labels: samples

#2890 fix(functions/background-termination): fix incorrect comments
  functions/concepts/backgroundTermination/index.js
Labels: api: cloudfunctions, samples
