Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2022-12, with the labels that each got.

#2893 Update CODEOWNERS
  CODEOWNERS
Labels: samples

#2883 chore: fix GH Actions triggering on any change
  .github/workflows/iam-deny.yml
Labels: samples

#2902 ci: Cleanup dependencies
  appengine/endpoints/package.json
  appengine/typescript/package.json
  asset/snippets/package.json
  cloud-language/package.json
  cloud-sql/mysql/mysql/package.json
  cloud-sql/sqlserver/mssql/package.json
  container/snippets/package.json
  datacatalog/snippets/package.json
  dialogflow-cx/package.json
  dialogflow/package.json
  document-ai/package.json
  healthcare/datasets/package.json
  healthcare/dicom/package.json
  healthcare/fhir/package.json
  healthcare/hl7v2/package.json
  kms/package.json
  monitoring/prometheus/package.json
  service-directory/snippets/package.json
  talent/package.json
Labels: samples

#2886 docs(assets): added sample code for saved queries
  asset/snippets/createSavedQuery.js
  asset/snippets/deleteSavedQuery.js
  asset/snippets/getSavedQuery.js
  asset/snippets/listSavedQueries.js
  asset/snippets/package.json
  asset/snippets/test/samples.test.js
  asset/snippets/updateSavedQuery.js
  package.json
Labels: samples

#2913 fix(healthcare-api): fix 'google-auth-library' is extraneous error
  healthcare/fhir/package.json
Labels: samples

#2923 fix(run/logging): make tests more robust
  run/logging-manual/package.json
  run/logging-manual/test/system.test.js
Labels: api: run, samples

#2888 feat(speech): adds V2 samples
  speech/package.json
  speech/quickstart.v2.js
  speech/system-test/quickstart.v2.test.js
  speech/system-test/transcribeFile.v2.test.js
  speech/transcribeFile.v2.js
Labels: automerge, api: speech, samples

#2929 chore(functions/v2): Migrate parseXML sample to gen2
  functions/http/parseXML/index.js
  functions/http/parseXML/package.json
Labels: api: cloudfunctions, samples

#2938 chore(functions/v2): migrate CORS enabled function sample to gen2
  functions/http/corsEnabledFunction/index.js
  functions/http/corsEnabledFunction/package.json
  functions/http/corsEnabledFunction/test/index.test.js
Labels: api: cloudfunctions, samples

#2940 chore(functions/connectionPooling): Update connectionPooling sample to use gen 2 signature
  functions/tips/connectionPools/index.js
  functions/tips/connectionPools/package.json
Labels: api: cloudfunctions, samples

#2943 chore(functions/httpContent): using gen2 declarative signature
  functions/http/httpContent/index.js
  functions/http/httpContent/package.json
  functions/http/httpContent/test/index.test.js
Labels: api: cloudfunctions, samples

#2945 fix: update security center snippets to v7
  security-center/snippets/package.json
  security-center/snippets/system-test/v1/notifications.test.js
  security-center/snippets/v1/deleteNotificationConfig.js
  security-center/snippets/v1/getNotificationConfig.js
  security-center/snippets/v1/updateNotificationConfig.js
Labels: samples

#2948 fix(healthcare-api): add comment description for hl7v2MessageId
  healthcare/hl7v2/deleteHl7v2Message.js
  healthcare/hl7v2/getHl7v2Message.js
  healthcare/hl7v2/patchHl7v2Message.js
Labels: samples

#2942 fix(run/logging): throw error if stdout is empty
  run/logging-manual/test/system.test.js
Labels: api: run, samples

#2946 test: fix skipped datacatalog test
  datacatalog/snippets/searchAssets.js
  datacatalog/snippets/test/samples.test.js
Labels: samples

#2949 Update region tag coverage
  functions/helloworld/helloworldHttp/test/sample.integration.http.test.js
Labels: api: cloudfunctions, samples

#2950 chore: Revert logging manual test changes
  run/logging-manual/package.json
  run/logging-manual/test/system.test.js
Labels: api: logging, samples
