Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-12, with the labels that each got.

#3587 feat: genai sample base
  .github/auto-label.yaml
  .github/workflows/generative-ai-snippets.yaml
  .github/workflows/utils/workflows-secrets.json
  CODEOWNERS
  generative-ai/snippets/countTokens.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/package.json
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
  generative-ai/snippets/test/countTokens.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/nonStreamingMultipartContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
  generative-ai/snippets/test/streamMultipartContent.test.js
Labels: samples, api: workflows

#3586 fix: configure express to know about Cloud Run's proxy
  run/filesystem/index.js
Labels: api: run, samples, asset: pattern

#3588 refactor: update genai samples
  generative-ai/snippets/countTokens.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/package.json
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
  generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
Labels: samples, api: genai

#3585 fix: Add endpoint override for Document AI Warehouse samples
  document-warehouse/create-document-schema.js
  document-warehouse/delete-document-schema.js
  document-warehouse/fetch-acl.js
  document-warehouse/get-document-schema.js
  document-warehouse/get-document.js
  document-warehouse/quickstart.js
  document-warehouse/search-document.js
  document-warehouse/set-acl.js
Labels: samples

#3589 fix: resolve small bug (repeated image), and moving region tag
  generative-ai/snippets/sendMultiModalPromptWithImage.js
Labels: samples, api: genai

#3591 fix: resolve typo in genai sample
  generative-ai/snippets/nonStreamingMultipartContent.js
Labels: samples, api: genai

#3595 chore: move image part before text part in vertex requests
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamMultipartContent.js
Labels: samples, api: genai

#3598 add model to each function
  generative-ai/snippets/countTokens.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
Labels: samples, api: genai
