Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-01, with the labels that each got.

#2931 fix(functions): add tests for parseXML sample
  functions/http/parseXML/package.json
  functions/http/parseXML/test/index.test.js
Labels: api: cloudfunctions, samples

#2956 chore(functions/concepts): Migrate stateless sample to gen2
  functions/concepts/stateless/index.js
  functions/concepts/stateless/package.json
Labels: api: cloudfunctions, samples

#2941 chore(functions/http): migrate HTTP Auth with CORS sample to gen2
  functions/http/corsEnabledFunctionAuth/index.js
  functions/http/corsEnabledFunctionAuth/package.json
  functions/http/corsEnabledFunctionAuth/test/index.test.js
Labels: api: cloudfunctions, samples

#2944 chore(functions/tips/scopeDemo): use gen2 declarative signature, add tests
  functions/tips/scopeDemo/computations.js
  functions/tips/scopeDemo/index.js
  functions/tips/scopeDemo/package.json
  functions/tips/scopeDemo/test/index.test.js
Labels: kokoro:force-run, api: cloudfunctions, samples

#2960 fix(functions): fix CI failures
  functions/http/parseXML/test/index.test.js
  functions/tips/scopeDemo/test/index.test.js
Labels: api: cloudfunctions, samples

#2957 chore(functions/concepts): Migrate Send HTTP requests Sample to gen2
  functions/concepts/requests/index.js
  functions/concepts/requests/package.json
Labels: api: cloudfunctions, samples

#2953 chore(functions/tips/gcpApiCalls): update gen2 declarative signature
  .github/workflows/functions-tips.yaml
  functions/tips/gcpApiCall/index.js
  functions/tips/gcpApiCall/package.json
  functions/tips/gcpApiCall/test/index.test.js
Labels: api: cloudfunctions, samples

#2964 ci: test auto-label configuration
  .github/auto-label.yaml
Labels: samples

#2965 chore(functions/v2): Migrate uploadFile sample to gen2
  functions/http/uploadFile/index.js
  functions/http/uploadFile/package.json
Labels: api: cloudfunctions, samples

#2967 ci: Update auto-label.yaml
  .github/auto-label.yaml
Labels: samples

#2968 Move recaptcha demosite to nodejs-docs-samples
  .eslintignore
  CODEOWNERS
  recaptcha/demosite/.docker-compose.yml
  recaptcha/demosite/README.md
  recaptcha/demosite/app/Dockerfile
  recaptcha/demosite/app/controllers/assessmentController.js
  recaptcha/demosite/app/controllers/loginController.js
  recaptcha/demosite/app/controllers/signupController.js
  recaptcha/demosite/app/index.js
  recaptcha/demosite/app/init.sh
  recaptcha/demosite/app/package.json
  recaptcha/demosite/app/recaptcha/createAssessment.js
  recaptcha/demosite/app/routes.js
  recaptcha/demosite/app/static/assessment.js
  recaptcha/demosite/app/static/home.css
  recaptcha/demosite/app/static/recaptcha.png
  recaptcha/demosite/app/templates/login.html
  recaptcha/demosite/app/templates/signup.html
Labels: samples

#2798 Delete `/containerengine/` folder
  .github/workflows/containerengine-hello-world.yaml
  containerengine/README.md
  containerengine/hello-world/Dockerfile
  containerengine/hello-world/README.md
  containerengine/hello-world/package.json
  containerengine/hello-world/server.js
  containerengine/hello-world/test/server.test.js
Labels: samples

#2969 feat(speech): adds streaming transcribe, create recognizer v2 samples
  speech/createRecognizer.v2.js
  speech/system-test/createRecognizer.v2.test.js
  speech/system-test/transcribeStreaming.v2.test.js
  speech/transcribeStreaming.v2.js
Labels: automerge, api: speech, samples

#2979 chore: Add auth and recaptcha to auto-labeling
  .github/auto-label.yaml
Labels: samples

#2973 chore(functions/tips): Migrate lazyGlobals sample to gen2
  functions/tips/lazyGlobals/index.js
  functions/tips/lazyGlobals/package.json
Labels: api: cloudfunctions, samples

#2972 chore(functions/concepts): Migrate afterTimeout sample to gen2
  functions/concepts/afterTimeout/index.js
  functions/concepts/afterTimeout/package.json
Labels: api: cloudfunctions, samples

#2981 test: enable video-intelligence tests
  video-intelligence/system-test/analyze-face-detection-gcs.test.js
  video-intelligence/system-test/analyze-face-detection.test.js
  video-intelligence/system-test/analyze-person-detection-gcs.test.js
  video-intelligence/system-test/analyze-person-detection.test.js
  video-intelligence/system-test/analyze-streaming-annotation-to-storage.test.js
  video-intelligence/system-test/analyze-streaming-automl-classification.test.js
  video-intelligence/system-test/analyze-streaming-automl-object-tracking.test.js
  video-intelligence/system-test/analyze-streaming-labels.test.js
  video-intelligence/system-test/analyze-streaming-object.test.js
  video-intelligence/system-test/analyze-streaming-safe-search.test.js
  video-intelligence/system-test/analyze-streaming-shot-change.test.js
  video-intelligence/system-test/analyze.test.js
  video-intelligence/system-test/analyze.v1p2beta1.test.js
  video-intelligence/system-test/detect_logo.test.js
  video-intelligence/system-test/detect_logo_gcs.test.js
  video-intelligence/system-test/quickstart.test.js
Labels: api: videointelligence, samples

#2978 Rename docker-compose.yaml to remove leading dot.
  recaptcha/demosite/docker-compose.yml
Labels: samples

#2982 chore(functions/concepts): Migrate afterResponse sample to gen2
  functions/concepts/afterResponse/index.js
  functions/concepts/afterResponse/package.json
Labels: api: cloudfunctions, samples

#2983 chore(functions/concepts): Migrate httpTermination sample to gen2
  functions/concepts/httpTermination/index.js
  functions/concepts/httpTermination/package.json
Labels: api: cloudfunctions, samples

#2985 fix: update retail paths
  retail/interactive-tutorials/README.md
  retail/interactive-tutorials/user_environment_setup.sh
  retail/interactive-tutorials/user_import_data_to_catalog.sh
Labels: samples, api: retail

#2993 Fix datastore/functions test timing out
  datastore/functions/package.json
  datastore/functions/test/index.test.js
Labels: api: cloudfunctions, samples

#2995 test: update mocha dependency in retail
  retail/package.json
Labels: samples, api: retail

#2996 Fix docker-compose build issues for the reCAPTCHA demosite.
  recaptcha/demosite/app/index.js
  recaptcha/demosite/app/routes.js
  recaptcha/demosite/docker-compose.yaml
Labels: api: recaptchaenterprise, samples

#2997 migrate code from googleapis/nodejs-storage-transfer
  .github/workflows/storagetransfer.yaml
  .github/workflows/workflows.json
  CODEOWNERS
  storagetransfer/aws-request.js
  storagetransfer/aws-s3-compatible-source-request.js
  storagetransfer/azure-request.js
  storagetransfer/check-latest-transfer-operation.js
  storagetransfer/get-transfer-job-with-retries.js
  storagetransfer/manifest-request.js
  storagetransfer/nearline-request.js
  storagetransfer/package.json
  storagetransfer/posix-download.js
  storagetransfer/posix-request.js
  storagetransfer/posix-to-posix-request.js
  storagetransfer/quickstart.js
  storagetransfer/test/aws-request.test.js
  storagetransfer/test/aws-s3-compatible-source-request.test.js
  storagetransfer/test/azure-request.test.js
  storagetransfer/test/check-latest-transfer-operation.test.js
  storagetransfer/test/get-transfer-job-with-retries.test.js
  storagetransfer/test/manifest-request.test.js
  storagetransfer/test/nearline-request.test.js
  storagetransfer/test/posix-download.test.js
  storagetransfer/test/posix-request.test.js
  storagetransfer/test/posix-to-posix-request.test.js
  storagetransfer/test/quickstart.test.js
  storagetransfer/test/transfer-check.test.js
  storagetransfer/test/utils/bucket.js
  storagetransfer/test/utils/index.js
  storagetransfer/test/utils/sample.js
  storagetransfer/test/utils/transfer.js
  storagetransfer/transfer-check.js
Labels: samples

#2999 ci: Add header checker
  .github/header-checker-lint.yml
  .github/workflows/ci.yaml.njk
Labels: samples, api: workflows

#3002 docs: update Mocha version
  media/livestream/package.json
  media/transcoder/package.json
  media/video-stitcher/package.json
Labels: samples
