Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-02, with the labels that each got.

#3013 fix: migrate to wait-port 1.0.4
  appengine/endpoints/package.json
  appengine/endpoints/test/appListening.test.js
  appengine/memcached/package.json
  appengine/memcached/test/app.test.js
  appengine/pubsub/package.json
  appengine/pubsub/test/appListening.test.js
  appengine/typescript/package.json
  appengine/typescript/test/app.test.js
  endpoints/getting-started-grpc/package.json
  endpoints/getting-started-grpc/system-test/endpoints.test.js
  functions/billing/package.json
  functions/helloworld/helloGCS/package.json
  functions/helloworld/helloPubSub/package.json
  functions/helloworld/helloworldGet/package.json
  functions/helloworld/helloworldHttp/package.json
  functions/helloworld/package.json
  functions/imagemagick/package.json
  functions/pubsub/package.json
  functions/pubsub/publish/package.json
  functions/speech-to-speech/functions/package.json
Labels: api: appengine, samples

#3016 chore: include ff google team as functions samples owners
  CODEOWNERS
Labels: samples

#2990 docs(speech): migrate samples
  speech/export-to-storage.v1p1beta1.js
  speech/modelAdaptation.js
Labels: api: speech, samples

#3005 fix: refactor asset tests
  .github/workflows/asset.yaml
  .github/workflows/workflows.json
  asset/snippets/package.json
  asset/snippets/test/asset.test.js
  asset/snippets/test/iamPolicy.test.js
  asset/snippets/test/samples.test.js
  asset/snippets/test/savedQuery.test.js
Labels: api: cloudasset, samples

#3017 chore: remove duplicate document-ai in CODEOWNERS
  CODEOWNERS
Labels: samples

#3004 fix: migrate deprecated use of topic.publish()
  appengine/pubsub/app.js
  functions/helloworld/helloPubSub/test/sample.system.pubsub.test.js
  functions/ocr/app/index.js
  functions/pubsub/publish/index.js
  functions/v2/ocr/app/index.js
Labels: api: cloudfunctions, samples

#3028 Convert the score to a string with one decimal
  recaptcha/demosite/app/recaptcha/createAssessment.js
Labels: api: recaptchaenterprise, samples

#3030 fix: making unique region tags for helloerror samples for functions
  functions/helloworld/helloError/index.js
  functions/helloworld/helloError/test/index.test.js
Labels: api: cloudfunctions, samples

#3034 Add an optional DOCKER_COMPOSE_USER environment variable.
  recaptcha/demosite/docker-compose.yaml
Labels: api: recaptchaenterprise, samples

#3035 samples: migrate code from googleapis/nodejs-dlp
  .github/workflows/dlp.yaml
  .github/workflows/workflows.json
  CODEOWNERS
  dlp/.eslintrc.yml
  dlp/.gitignore
  dlp/categoricalRiskAnalysis.js
  dlp/createInspectTemplate.js
  dlp/createTrigger.js
  dlp/deidentifyWithDateShift.js
  dlp/deidentifyWithFpe.js
  dlp/deidentifyWithMask.js
  dlp/deidentifyWithReplacement.js
  dlp/deleteInspectTemplate.js
  dlp/deleteJob.js
  dlp/deleteTrigger.js
  dlp/inspectBigQuery.js
  dlp/inspectDatastore.js
  dlp/inspectFile.js
  dlp/inspectGCSFile.js
  dlp/inspectString.js
  dlp/kAnonymityAnalysis.js
  dlp/kMapEstimationAnalysis.js
  dlp/lDiversityAnalysis.js
  dlp/listInspectTemplates.js
  dlp/listJobs.js
  dlp/listTriggers.js
  dlp/metadata.js
  dlp/numericalRiskAnalysis.js
  dlp/package.json
  dlp/quickstart.js
  dlp/redactImage.js
  dlp/reidentifyWithFpe.js
  dlp/resources/accounts.txt
  dlp/resources/dates.csv
  dlp/resources/harmless.txt
  dlp/resources/test.png
  dlp/resources/test.txt
  dlp/system-test/deid.test.js
  dlp/system-test/inspect.test.js
  dlp/system-test/jobs.test.js
  dlp/system-test/metadata.test.js
  dlp/system-test/quickstart.test.js
  dlp/system-test/resources/date-shift-context.expected.csv
  dlp/system-test/risk.test.js
  dlp/system-test/temp.result.csv
  dlp/system-test/templates.test.js
  dlp/system-test/triggers.test.js
Labels: samples

#3038 chore: migrate assessed sample as requested by techwriting
  dlp/redactText.js
  dlp/system-test/redact.test.js
  dlp/system-test/resources/redact-multiple-types.expected.png
  dlp/system-test/resources/redact-single-type.expected.png
Labels: samples

#3049 Demosite app recaptcha
  recaptcha/demosite/app/static/scripts/component.js
  recaptcha/demosite/docker-compose.yaml
Labels: api: recaptchaenterprise, samples

#3047 chore: upgrade base image to node 14
  .kokoro/common.cfg
  .kokoro/run/websockets.cfg
  package.json
  renovate.json
  run/websockets/package.json
Labels: api: run, samples

#3057 fix: update Cloud SQL service account instructions
  cloud-sql/mysql/mysql/README.md
  cloud-sql/postgres/knex/README.md
  cloud-sql/sqlserver/mssql/README.md
Labels: api: cloudsql, samples

#3054 fix: update vision tests
  .github/workflows/vision.yaml
  vision/detect.v1p1beta1.js
  vision/package.json
  vision/system-test/detect.v1p1beta1.test.js
  vision/system-test/productSearch.test.js
  vision/system-test/similarProducts.test.js
  vision/system-test/textDetection.test.js
  vision/textDetection.js
Labels: api: vision, samples

#3061 chore: add CODEOWNERS for DLP samples
  CODEOWNERS
Labels: samples
