Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-09, with the labels that each got.

#3483 chore(aiplatform): readd skipped tests after tests are stabilized
  ai-platform/snippets/test/create-custom-job.test.js
  ai-platform/snippets/test/create-dataset-image.test.js
  ai-platform/snippets/test/create-dataset-tabular-bigquery.test.js
  ai-platform/snippets/test/create-featurestore-fixed-nodes-sample.test.js
  ai-platform/snippets/test/create-featurestore-sample.test.js
  ai-platform/snippets/test/create-training-pipeline-tabular-regression.test.js
  ai-platform/snippets/test/deploy-model-custom-trained-model.test.js
  ai-platform/snippets/test/deploy-model.test.js
Labels: samples, api: aiplatform, owlbot:ignore

#3482 fix(aiplatform): set appropriate maxOutputTokens
  .github/workflows/ci.yaml
  ai-platform/snippets/predict-text-prompt.js
Labels: samples, api: aiplatform, owlbot:ignore

#3423 feat: add sample code for create and delete document schema
  document-warehouse/create-document-schema.js
  document-warehouse/delete-document-schema.js
  document-warehouse/package.json
  document-warehouse/test/document-schema.test.js
  document-warehouse/test/fetch-acl.test.js
  document-warehouse/test/set-acl.test.js
Labels: samples

#3476 feat(language): update code samples for Cloud NL v2
  cloud-language/analyze_entities_v2_file.js
  cloud-language/analyze_entities_v2_text.js
  cloud-language/analyze_sentiment_v2_file.js
  cloud-language/analyze_sentiment_v2_text.js
  cloud-language/classify_text_v2_file.js
  cloud-language/classify_text_v2_text.js
  cloud-language/package.json
  cloud-language/test/analyze.v2.test.js
Labels: api: language, samples

#3494 feat: add sample code for get document schema
  document-warehouse/get-document-schema.js
  document-warehouse/test/document-schema.test.js
  package.json
Labels: samples

#3505 fix: refactor error reporting code sample
  error-reporting/quickstart.js
Labels: api: clouderrorreporting, samples

#3500 chore(discoveryengine): update search sample to disable auto paginate
  discoveryengine/search.js
Labels: samples, api: discoveryengine

#3510 feat(storagetransfer): add event driven transfer samples and tests
  storagetransfer/event-driven-aws-transfer.js
  storagetransfer/event-driven-gcs-transfer.js
  storagetransfer/package.json
  storagetransfer/test/event-driven-aws-transfer.test.js
  storagetransfer/test/event-driven-gcs-transfer.test.js
  storagetransfer/test/utils/index.js
  storagetransfer/test/utils/queue.js
Labels: api: storagetransfer, samples
