Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-06, with the labels that each got.

#3241 DLP: Add response streaming sample in nodejs
  functions/v2/responseStreaming/index.js
  functions/v2/responseStreaming/package.json
  functions/v2/responseStreaming/test/index.test.js
Labels: api: dlp, samples

#3245 feat(aiplatform): text prompt sample for LLMs
  ai-platform/snippets/predict-text-prompt.js
  ai-platform/snippets/test/predict-text-prompt.test.js
Labels: samples, api: aiplatform

#3246 feat: chat prompt sample for Vertex LLMs
  ai-platform/snippets/predict-chat-prompt.js
  ai-platform/snippets/test/predict-chat-prompt.test.js
Labels: samples, api: aiplatform

#3250 feat: sentiment analysis sample for Vertex LLMs
  ai-platform/snippets/predict-text-sentiment.js
  ai-platform/snippets/test/predict-text-sentiment.test.js
Labels: samples, api: aiplatform

#3249 feat: text extraction sample for Vertex LLMs
  ai-platform/snippets/predict-text-extraction.js
  ai-platform/snippets/test/predict-text-extraction.test.js
Labels: samples, api: aiplatform

#3251 feat: text summarization sample for Vertex LLMs
  ai-platform/snippets/predict-text-summarization.js
  ai-platform/snippets/test/predict-text-summarization.test.js
Labels: samples, api: aiplatform

#3248 feat: text classification sample for Vertex LLMs
  ai-platform/snippets/predict-text-news-classification.js
  ai-platform/snippets/test/predict-text-news-classification.test.js
Labels: samples, api: aiplatform

#3262 feat(aiplatform): code generation unit test sample for Vertex LLMs
  ai-platform/snippets/predict-code-generation-unittest.js
  ai-platform/snippets/test/predict-code-generation-unittest.test.js
Labels: samples, api: aiplatform

#3261 feat(aiplatform): code generation function sample for Vertex LLMs
  ai-platform/snippets/predict-code-generation-function.js
  ai-platform/snippets/test/predict-code-generation-function.test.js
Labels: samples, api: aiplatform

#3260 feat(aiplatform): code completion test function for Vertex LLMs
  ai-platform/snippets/predict-code-completion-test-function.js
  ai-platform/snippets/test/predict-code-completion-test-function.test.js
Labels: samples, api: aiplatform

#3259 feat(aiplatform): code completion comment sample for Vertex LLMs
  ai-platform/snippets/predict-code-completion-comment.js
  ai-platform/snippets/test/predict-code-completion-comment.test.js
Labels: samples, api: aiplatform

#3258 feat(aiplatform): code chat sample for Vertex LLMs
  ai-platform/snippets/predict-code-chat.js
  ai-platform/snippets/test/predict-code-chat.test.js
Labels: samples, api: aiplatform

#3263 fix(aiplatform): update model parameters and instances
  ai-platform/snippets/predict-code-chat.js
  ai-platform/snippets/predict-code-completion-comment.js
  ai-platform/snippets/predict-code-completion-test-function.js
  ai-platform/snippets/predict-code-generation-function.js
  ai-platform/snippets/predict-code-generation-unittest.js
Labels: samples, api: aiplatform

#3239 DLP: Added sample for inspect string using multiple rules
  dlp/inspectStringMultipleRules.js
  dlp/system-test/inspect.test.js
Labels: api: dlp, samples

#3272 fix: Update CODEOWNERS
  CODEOWNERS
Labels: samples

#3274 chore: update iam deny test
  .github/workflows/iam-deny.yaml
  .github/workflows/iam.yaml
  .github/workflows/utils/workflows-secrets.json
  .github/workflows/utils/workflows.json
  iam/deny/package.json
  iam/deny/test/deny.test.js
Labels: samples, api: workflows

#3278 fix: add missing dialogflow-cx test resource
  dialogflow-cx/resources/audio.raw
  dialogflow-cx/test/detect-intent-sentiment-analysis-test.js
  dialogflow-cx/test/quickstart.test.js
Labels: api: dialogflow, samples

#3233 DLP: Added sample for create stored infotype
  dlp/createStoredInfoType.js
  dlp/system-test/metadata.test.js
Labels: api: dlp, samples, actions:force-run

#3240 DLP: Added sample for de-identify using time extract
  dlp/deidentifyWithTimeExtraction.js
  dlp/system-test/deid.test.js
Labels: api: dlp, samples, actions:force-run

#3268 fix: incorrect audience when creating cloud task
  cloud-tasks/tutorial-gcf/app/createTask.js
Labels: api: tasks, samples

#3234 DLP: Added sample for de-identify table with FPE
  dlp/deIdentifyTableWithFpe.js
  dlp/system-test/deid.test.js
  dlp/system-test/mockdata.js
Labels: api: dlp, samples

#3289 feat(aiplatform): adds list tuned models
  ai-platform/snippets/list-tuned-models.js
  ai-platform/snippets/package.json
  ai-platform/snippets/test/list-tuned-models.test.js
Labels: samples, api: aiplatform

#3290 fix(aiplatform): list tuned models test
  ai-platform/snippets/list-tuned-models.js
  ai-platform/snippets/test/list-tuned-models.test.js
Labels: samples, api: aiplatform

#3270 docs: Add sample app for invoking private endpoint documentation
  .github/workflows/utils/workflows.json
  workflows/invoke-private-endpoint/README.md
  workflows/invoke-private-endpoint/app.js
  workflows/invoke-private-endpoint/package.json
  workflows/invoke-private-endpoint/test/app.test.js
Labels: samples, api: workflows, actions:force-run

#3287 feat: add fetch acl sample code for content warehouse
  .github/blunderbuss.yml
  .github/workflows/document-warehouse.yaml
  .github/workflows/utils/workflows.json
  CODEOWNERS
  document-warehouse/.eslintrc.yml
  document-warehouse/fetch-acl.js
  document-warehouse/package.json
  document-warehouse/test/.eslintrc.yml
  document-warehouse/test/fetch-acl.test.js
  package.json
Labels: samples, actions:force-run

#3291 fix: replace deprecated repo with active docker repo for trampoline image
  .kokoro/appengine/test-deployment/common.cfg
Labels: type: bug, api: appengine, samples, release blocking, actions:force-run

#3273 feat: adds tune LLM sample
  ai-platform/snippets/test/tuning.test.js
  ai-platform/snippets/tuning.js
Labels: samples, api: aiplatform

#3285 DLP: Added sample for deidentify with FPE surrogate
  dlp/deidentifyWithFpeSurrogate.js
  dlp/reidentifyWithFpeSurrogate.js
  dlp/system-test/deid.test.js
Labels: api: dlp, samples

#3299 chore(cloud-sql): cleanup pg/knex example comments
  cloud-sql/postgres/knex/connect-connector-with-iam-authn.js
  cloud-sql/postgres/knex/index.js
Labels: api: cloudsql, samples

#3301 fix(cloud-sql): update region tag and logic for IAM Authn
  cloud-sql/postgres/knex/connect-connector-with-iam-authn.js
  cloud-sql/postgres/knex/index.js
Labels: api: cloudsql, samples

#3297 fix: update publishMessage argument
  functions/ocr/app/index.js
Labels: api: cloudfunctions, samples

#3303 chore(aiplatform): temporarily skip featurestore tests
  ai-platform/snippets/test/create-featurestore-fixed-nodes-sample.test.js
  ai-platform/snippets/test/create-featurestore-sample.test.js
Labels: samples, api: aiplatform

#3292 feat: add sample code for set acl
  document-warehouse/package.json
  document-warehouse/set-acl.js
  document-warehouse/test/set-acl.test.js
Labels: samples, actions:force-run

#3284 DLP: Added sample for inspect GCS file
  dlp/inspectGcsFileWithSampling.js
  dlp/inspectImageFileAllInfoTypes.js
  dlp/system-test/inspect.test.js
  dlp/system-test/mockdata.js
Labels: automerge, api: dlp, samples

#3304 fix(aiplatform): Temporarily increase the CI tests timeout
  .github/workflows/ai-platform-snippets.yaml
Labels: samples, api: workflows, api: aiplatform

#3283 fix: adding in permissions to workflows
  .github/workflows/ai-platform-snippets.yaml
  .github/workflows/automl.yaml
  .github/workflows/functions-slack.yaml
  .github/workflows/iam-deny.yaml
  .github/workflows/security-center-snippets.yaml
  .github/workflows/storagetransfer.yaml
  .github/workflows/utils/ci-matrix.yaml.njk
  .github/workflows/utils/ci-secrets.yaml.njk
  .github/workflows/vision.yaml
Labels: samples, api: workflows

#3295 DLP: Added sample for inspect string with custom hotword
  dlp/inspectStringCustomExcludingSubstring.js
  dlp/inspectStringCustomHotword.js
  dlp/system-test/inspect.test.js
Labels: api: dlp, samples, actions:force-run

#3293 feat(aiplatform): add sample to generate image from text prompt
  ai-platform/snippets/predict-image-from-text.js
  ai-platform/snippets/test/predict-image-from-text.test.js
Labels: samples, api: aiplatform

#3294 feat(aiplatform): add sample to generate image from base image and text prompt
  ai-platform/snippets/predict-image-from-image-and-text.js
  ai-platform/snippets/test/predict-image-from-image-and-text.test.js
Labels: samples, api: aiplatform

#3311 fix(aiplatform): reset timeout and skip deploy model test
  .github/workflows/ai-platform-snippets.yaml
  ai-platform/snippets/test/deploy-model-custom-trained-model.test.js
Labels: automerge, samples, api: aiplatform

#3264 feat(cloud-sql): add mysql2 connector sample
  cloud-sql/mysql/mysql2/Dockerfile
  cloud-sql/mysql/mysql2/README.md
  cloud-sql/mysql/mysql2/app.flexible.yaml
  cloud-sql/mysql/mysql2/app.standard.yaml
  cloud-sql/mysql/mysql2/connect-connector-auto-iam-authn.js
  cloud-sql/mysql/mysql2/connect-connector.js
  cloud-sql/mysql/mysql2/connect-tcp.js
  cloud-sql/mysql/mysql2/connect-unix.js
  cloud-sql/mysql/mysql2/deployment.yaml
  cloud-sql/mysql/mysql2/functions.js
  cloud-sql/mysql/mysql2/index.js
  cloud-sql/mysql/mysql2/package.json
  cloud-sql/mysql/mysql2/server/server.js
  cloud-sql/mysql/mysql2/service-account.yaml
  cloud-sql/mysql/mysql2/service.yaml
  cloud-sql/mysql/mysql2/test/server.test.js
  cloud-sql/mysql/mysql2/views/index.pug
Labels: api: cloudsql, samples

#3314 fix(aiplatform): temporarily increase test timeout to diagnose flaky tests
  ai-platform/snippets/package.json
Labels: samples, api: aiplatform

#3310 DLP: Added sample for de-identify and re-identify with deterministic encryption
  dlp/deidentifyWithDeterministic.js
  dlp/reidentifyWithDeterministic.js
  dlp/system-test/deid.test.js
  dlp/system-test/mockdata.js
Labels: api: dlp, samples, actions:force-run
