Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-03, with the labels that each got.

#3064 fix: delete test DLP jobs created in snippets
  dlp/categoricalRiskAnalysis.js
  dlp/kAnonymityAnalysis.js
  dlp/kMapEstimationAnalysis.js
  dlp/lDiversityAnalysis.js
  dlp/numericalRiskAnalysis.js
  dlp/system-test/inspect.test.js
  dlp/system-test/risk.test.js
Labels: samples

#3065 chore: rename recaptcha folder and update CODEOWNERS
  .github/auto-label.yaml
  CODEOWNERS
  recaptcha_enterprise/demosite/README.md
  recaptcha_enterprise/demosite/app/Dockerfile
  recaptcha_enterprise/demosite/app/controllers/controller.js
  recaptcha_enterprise/demosite/app/index.js
  recaptcha_enterprise/demosite/app/init.sh
  recaptcha_enterprise/demosite/app/package.json
  recaptcha_enterprise/demosite/app/recaptcha/createAssessment.js
  recaptcha_enterprise/demosite/app/routes.js
  recaptcha_enterprise/demosite/app/static/browserconfig.xml
  recaptcha_enterprise/demosite/app/static/images/bot-color-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/images/castle-alternate-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/images/human-color-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-120px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-128px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-144px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-150px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-152px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-16px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-180px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-192px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-196px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-310px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-32px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-512px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-64px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-70px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon-96px.png
  recaptcha_enterprise/demosite/app/static/images/icons/favicon.ico
  recaptcha_enterprise/demosite/app/static/images/icons/favicon.svg
  recaptcha_enterprise/demosite/app/static/images/item-hydrant-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/images/item-stoplight-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/images/land-unoptimized.svg
  recaptcha_enterprise/demosite/app/static/manifest.webmanifest
  recaptcha_enterprise/demosite/app/static/scripts/component.js
  recaptcha_enterprise/demosite/app/static/scripts/global.js
  recaptcha_enterprise/demosite/app/static/styles/global.css
  recaptcha_enterprise/demosite/app/static/styles/local.css
  recaptcha_enterprise/demosite/app/templates/comment.html
  recaptcha_enterprise/demosite/app/templates/game.html
  recaptcha_enterprise/demosite/app/templates/home.html
  recaptcha_enterprise/demosite/app/templates/login.html
  recaptcha_enterprise/demosite/app/templates/signup.html
  recaptcha_enterprise/demosite/app/templates/store.html
  recaptcha_enterprise/demosite/docker-compose.yaml
Labels: api: recaptchaenterprise, samples

#3053 chore: upgrade to node-redis 4
  run/websockets/README.md
  run/websockets/app.js
  run/websockets/package.json
  run/websockets/redis.js
Labels: api: run, samples

#3074 chore: update auto label and blunderbuss config for dlp
  .github/auto-label.yaml
  .github/blunderbuss.yml
Labels: samples

#3075 fix: add closing bracket in functions_http_system_test
  functions/helloworld/helloworldHttp/test/sample.system.http.test.js
Labels: api: cloudfunctions, samples

#3076 ci: skip typeless bot when no typescript files found
  owlbot.py
Labels: api: cloudfunctions, samples

#3085 fix: add back gcp-build script
  appengine/typescript/package.json
Labels: api: appengine, samples

#3092 Restore changes lost to the merge into main
  recaptcha_enterprise/demosite/app/static/scripts/component.js
  recaptcha_enterprise/demosite/docker-compose.yaml
Labels: api: recaptchaenterprise, samples

#3089 chore(functions/v2/log/processEntry): Update sample to use cloud event signature
  functions/v2/log/processEntry/index.js
  functions/v2/log/processEntry/package.json
  functions/v2/log/processEntry/test/index.test.js
Labels: api: cloudfunctions, samples

#3080 chore(functions/v2/tips/retry): create new cloud event sample from background function sample
  functions/v2/tips/retry/index.js
  functions/v2/tips/retry/package.json
  functions/v2/tips/retry/test/integration.test.js
  functions/v2/tips/retry/test/unit.test.js
Labels: api: cloudfunctions, samples

#3087 chore(functions/v2/tips/avoidInfiniteRetries): New cloud event sample from background function sample
  functions/v2/tips/avoidInfiniteRetries/index.js
  functions/v2/tips/avoidInfiniteRetries/package.json
  functions/v2/tips/avoidInfiniteRetries/test/unit.test.js
Labels: api: cloudfunctions, samples
