Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2023-11, with the labels that each got.

#3561 chore(deps): update actions/checkout, setup-node in template
  .github/workflows/utils/ci-secrets.yaml.njk
Labels: samples, api: workflows

#3558 fix(batch): Fixing wrong parameter name
  batch/create/create_script_job_with_template.js
  batch/test/advanced_creation.js
Labels: samples, api: batch

#3562 chore: Fix --set-env-var to --set-env-vars
  run/README.md
Labels: api: run, samples, asset: pattern

#3564 fix(functions): Functions Slack sample test errors
  .github/workflows/functions-slack.yaml
  functions/slack/test/integration.test.js
  functions/slack/test/unit.test.js
Labels: api: cloudfunctions, samples, asset: pattern

#3565 chore(deps): update actions/checkout action to v4 (functions-slack)
  .github/workflows/functions-slack.yaml
Labels: samples, api: workflows

#3560 chore(deps): update actions/checkout action to v4 (non-fork)
  .github/workflows/ai-platform-snippets.yaml
  .github/workflows/ci.yaml
  .github/workflows/dialogflow-cx.yaml
  .github/workflows/iam-deny.yaml
  .github/workflows/security-center-snippets.yaml
  .github/workflows/storagetransfer.yaml
  .github/workflows/test.yaml
  .github/workflows/vision.yaml
Labels: samples, api: workflows, actions:force-run

#3539 refactor: preserving semver ranges
  owlbot.py
  renovate.json
  run/logging-manual/app.js
Labels: samples

#3575 fix(docs): runnable example sample
  CONTRIBUTING.md
  README.md
Labels: samples

#3574 feat(kms): add import sample
  kms/checkStateImportJob.js
  kms/checkStateImportedKey.js
  kms/createImportJob.js
  kms/createKeyForImport.js
  kms/importManuallyWrappedKey.js
  kms/test/kms.test.js
Labels: api: cloudkms, samples

#3576 feat: add new optional accelerator_type parameter
  ai-platform/snippets/tuning.js
Labels: samples, api: aiplatform

#3563 feat: add Makefile for consistent behavior across samples
  Makefile
  package.json
Labels: samples
