Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-06, with the labels that each got.

#3700 chore: add text-embedding team to CODEOWNERS
  CODEOWNERS
Labels: samples

#3709 feat: update quickstart samples to use the Gemini Flash model
  generative-ai/snippets/gemini-video-audio.js
  generative-ai/snippets/nonStreamingMultipartContent.js
Labels: samples, api: genai

#3710 fix: invalid yaml that was breaking this workflow dialogflow-cx.yaml
  .github/workflows/dialogflow-cx.yaml
Labels: samples, api: workflows

#3708 chore: Update CODEOWNERS
  CODEOWNERS
Labels: samples

#3719 chore: pin gts version to fix errors in lint ci
  package.json
Labels: samples

#3716 feat(generative-ai): update samples to Gemini Flash; add updated regi…
  generative-ai/snippets/function-calling/functionCallingStreamChat.js
  generative-ai/snippets/gemini-all-modalities.js
  generative-ai/snippets/gemini-audio-summarization.js
  generative-ai/snippets/gemini-audio-transcription.js
  generative-ai/snippets/gemini-pdf.js
  generative-ai/snippets/gemini-system-instruction.js
  generative-ai/snippets/grounding/groundingPrivateDataBasic.js
  generative-ai/snippets/grounding/groundingPublicDataBasic.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
  generative-ai/snippets/test/grounding/groundingPrivateDataBasic.test.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
  generative-ai/snippets/test/inference/nonStreamMultiModalityBasic.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/nonStreamingMultipartContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
  generative-ai/snippets/test/streamMultipartContent.test.js
Labels: samples

#3720 chore(CODEOWNERS): Add cloud-samples-reviewers as a global sample owner
  CODEOWNERS
Labels: samples

#3727 chore: Remove extraneous safety settings in grounding sample
  generative-ai/snippets/grounding/groundingPublicDataBasic.js
Labels: samples, api: genai
