Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-07, with the labels that each got.

#3731 fix: Getting text-embeddings demo.
  ai-platform/snippets/predict-text-embeddings-preview.js
  ai-platform/snippets/predict-text-embeddings.js
Labels: samples, api: aiplatform

#3732 fix: Specify outputDimensionality properly.
  ai-platform/snippets/predict-text-embeddings-preview.js
  ai-platform/snippets/predict-text-embeddings.js
Labels: samples, api: aiplatform

#3735 chore: update node version
  package.json
Labels: samples

#3706 fix(generative-ai): Use the non stream method instead
  generative-ai/snippets/grounding/groundingPublicDataBasic.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
Labels: samples, api: genai

#3737 fix: Update non-streaming example
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/streamMultipartContent.js
Labels: samples, api: genai

#3744 test: pin security center path to version (v1)
  .github/workflows/security-center-snippets.yaml
Labels: samples, api: workflows

#3747 ci: remove use of pull_request_target (part 1)
  .github/workflows/functions-env_vars.yaml
  .github/workflows/remove-label.yaml
  .github/workflows/utils/ci-matrix.yaml.njk
  .github/workflows/utils/ci-secrets.yaml.njk
  .github/workflows/utils/ci.yaml.njk
  CONTRIBUTING.md
Labels: samples, actions:force-run

#3748 ci(functions): update tests to use labeled on pull_request trigger
  .github/workflows/functions-concepts.yaml
  .github/workflows/functions-firebase.yaml
  .github/workflows/functions-helloworld.yaml
  .github/workflows/functions-http.yaml
  .github/workflows/functions-log-helloWorld.yaml
  .github/workflows/functions-log-processEntry.yaml
  .github/workflows/functions-memorystore-redis.yaml
  .github/workflows/functions-pubsub.yaml
  .github/workflows/functions-scheduleinstance.yaml
  .github/workflows/functions-security.yaml
  .github/workflows/functions-slack.yaml
  .github/workflows/functions-spanner.yaml
  .github/workflows/functions-speech-to-speech-functions.yaml
  .github/workflows/functions-tips.yaml
  .github/workflows/functions-v2-autolabelinstance.yaml
  .github/workflows/functions-v2-cloudeventlogging.yaml
  .github/workflows/functions-v2-firebase-firestore-helloFirestore.yaml
  .github/workflows/functions-v2-firebase-firestore-makeUpperCase.yaml
  .github/workflows/functions-v2-firebase-remote-config-helloRemoteConfig.yaml
  .github/workflows/functions-v2-firebase-rtdb-helloRTDB.yaml
  .github/workflows/functions-v2-helloauditlog.yaml
  .github/workflows/functions-v2-hellobigquery.yaml
  .github/workflows/functions-v2-hellogcs.yaml
  .github/workflows/functions-v2-hellopubsub.yaml
  .github/workflows/functions-v2-httplogging.yaml
  .github/workflows/functions-v2-log-processEntry.yaml
  .github/workflows/functions-v2-ocr-app.yaml
  .github/workflows/functions-v2-tips-avoidInfiniteRetries.yaml
  .github/workflows/functions-v2-tips-retry.yaml
  .github/workflows/functions-v2-typed-googlechatbot.yaml
  .github/workflows/functions-v2-typed-greeting.yaml
Labels: api: cloudfunctions, samples

#3749 ci(appengine): update tests to use labeled on pull_request trigger
  .github/workflows/appengine-analytics.yaml
  .github/workflows/appengine-building-an-app-build.yaml
  .github/workflows/appengine-building-an-app-update.yaml
  .github/workflows/appengine-datastore.yaml
  .github/workflows/appengine-endpoints.yaml
  .github/workflows/appengine-hello-world-flexible.yaml
  .github/workflows/appengine-hello-world-standard.yaml
  .github/workflows/appengine-memcached.yaml
  .github/workflows/appengine-metadata-flexible.yaml
  .github/workflows/appengine-metadata-standard.yaml
  .github/workflows/appengine-pubsub.yaml
  .github/workflows/appengine-static-files.yaml
  .github/workflows/appengine-storage-flexible.yaml
  .github/workflows/appengine-storage-standard.yaml
  .github/workflows/appengine-typescript.yaml
  .github/workflows/appengine-websockets.yaml
Labels: api: appengine, samples

#3750 ci: update h-k workflows to use labeled on pull_request trigger
  .github/workflows/healthcare-consent.yaml
  .github/workflows/healthcare-datasets.yaml
  .github/workflows/healthcare-dicom.yaml
  .github/workflows/healthcare-fhir.yaml
  .github/workflows/healthcare-hl7v2.yaml
  .github/workflows/iam-deny.yaml
  .github/workflows/kms.yaml
Labels: samples, actions:force-run

#3751 ci: update m-r workflows to use labeled on pull_request trigger
  .github/workflows/media-livestream.yaml
  .github/workflows/media-transcoder.yaml
  .github/workflows/media-video-stitcher.yaml
  .github/workflows/mediatranslation.yaml
  .github/workflows/monitoring-opencensus.yaml
  .github/workflows/monitoring-prometheus.yaml
  .github/workflows/monitoring-snippets.yaml
  .github/workflows/opencensus.yaml
  .github/workflows/recaptcha-enterprise.yaml
  .github/workflows/retail.yaml
Labels: samples, actions:force-run

#3752 ci: update s-z workflows to use labeled on pull_request trigger
  .github/workflows/scheduler.yaml
  .github/workflows/secret-manager.yaml
  .github/workflows/security-center-snippets.yaml
  .github/workflows/service-directory-snippets.yaml
  .github/workflows/speech.yaml
  .github/workflows/storagetransfer.yaml
  .github/workflows/talent.yaml
  .github/workflows/texttospeech.yaml
  .github/workflows/translate.yaml
  .github/workflows/video-intelligence.yaml
  .github/workflows/vision-productSearch.yaml
  .github/workflows/vision.yaml
  .github/workflows/workflows.yaml
Labels: samples, api: workflows, actions:force-run

#3756 docs(generativeai): add region tags for code samples
  ai-platform/snippets/embedding-model-tuning.js
  ai-platform/snippets/predict-chat-prompt.js
  ai-platform/snippets/predict-code-chat.js
  ai-platform/snippets/predict-code-completion-comment.js
  ai-platform/snippets/predict-code-generation-function.js
  ai-platform/snippets/predict-image-from-image-and-text.js
  ai-platform/snippets/predict-text-embeddings.js
  ai-platform/snippets/predict-text-prompt.js
  ai-platform/snippets/tuning.js
  generative-ai/snippets/function-calling/functionCallingStreamContent.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
Labels: samples, api: aiplatform, api: genai

#3757 fix: failing groundingPublicDataBasic.test.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
Labels: samples, api: genai

#3755 ci: update d-e workflows for labeled on pull_request trigger
  .github/workflows/datastore-functions.yaml
  .github/workflows/dialogflow-cx.yaml
  .github/workflows/dialogflow.yaml
  .github/workflows/discoveryengine.yaml
  .github/workflows/document-ai.yaml
  .github/workflows/document-warehouse.yaml
  .github/workflows/endpoints-getting-started-grpc.yaml
  .github/workflows/endpoints-getting-started.yaml
  .github/workflows/error-reporting.yaml
  .github/workflows/eventarc-generic.yaml
Labels: samples, actions:force-run

#3753 ci: Update workflows for ai/ml/data to use labeled on pull_request trigger
  .github/workflows/ai-platform-snippets.yaml
  .github/workflows/datacatalog-cloud-client.yaml
  .github/workflows/datacatalog-quickstart.yaml
  .github/workflows/datacatalog-snippets.yaml
  .github/workflows/datalabeling.yaml
  .github/workflows/dataproc.yaml
  .github/workflows/dlp.yaml
  .github/workflows/generative-ai-snippets.yaml
Labels: samples, actions:force-run

#3754 ci: Update a-c workflows for labeled on pull_request trigger
  .github/workflows/asset-snippets.yaml
  .github/workflows/auth.yaml
  .github/workflows/batch.yaml
  .github/workflows/cloud-language.yaml
  .github/workflows/cloud-tasks-snippets.yaml
  .github/workflows/cloud-tasks-tutorial-gcf-app.yaml
  .github/workflows/cloud-tasks-tutorial-gcf-function.yaml
  .github/workflows/cloudbuild.yaml
  .github/workflows/composer-functions-composer-storage-trigger.yaml
  .github/workflows/composer.yaml
  .github/workflows/compute.yaml
  .github/workflows/contact-center-insights.yaml
  .github/workflows/container-analysis-snippets.yaml
  .github/workflows/container.yaml
Labels: samples, api: workflows

#3761 feat: add storage control folder and managed folder samples
  .github/workflows/storage-control.yaml
  storage-control/createFolder.js
  storage-control/createManagedFolder.js
  storage-control/deleteFolder.js
  storage-control/deleteManagedFolder.js
  storage-control/getFolder.js
  storage-control/getManagedFolder.js
  storage-control/listFolders.js
  storage-control/listManagedFolders.js
  storage-control/package.json
  storage-control/quickstart.js
  storage-control/renameFolder.js
  storage-control/system-test/folders.test.js
  storage-control/system-test/managedFolders.test.js
Labels: samples, api: workflows

#3763 feat: added secret manager team in codeowners
  CODEOWNERS
Labels: samples

#3765 refactor: adjust samples to use global variables
  ai-platform/snippets/predict-code-completion-comment.js
  ai-platform/snippets/predict-code-completion-test-function.js
  ai-platform/snippets/predict-text-prompt.js
  ai-platform/snippets/test/predict-code-completion-comment.test.js
  ai-platform/snippets/test/predict-code-completion-test-function.test.js
  ai-platform/snippets/test/predict-text-prompt.test.js
  generative-ai/snippets/inference/nonStreamMultiModalityBasic.js
  generative-ai/snippets/inference/nonStreamTextBasic.js
  generative-ai/snippets/inference/streamMultiModalityBasic.js
  generative-ai/snippets/inference/streamTextBasic.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/test/inference/nonStreamMultiModalityBasic.test.js
  generative-ai/snippets/test/inference/nonStreamTextBasic.test.js
  generative-ai/snippets/test/inference/streamMultiModalityBasic.test.js
  generative-ai/snippets/test/inference/streamTextBasic.test.js
Labels: samples, flakybot: flaky, api: aiplatform, api: genai

#3766 refactor(media): update other Video Stitcher samples with feedback fr…
  media/video-stitcher/createCdnKey.js
  media/video-stitcher/createCdnKeyAkamai.js
  media/video-stitcher/createLiveConfig.js
  media/video-stitcher/createLiveSession.js
  media/video-stitcher/createSlate.js
  media/video-stitcher/deleteCdnKey.js
  media/video-stitcher/deleteLiveConfig.js
  media/video-stitcher/deleteSlate.js
  media/video-stitcher/getCdnKey.js
  media/video-stitcher/getLiveAdTagDetail.js
  media/video-stitcher/getLiveConfig.js
  media/video-stitcher/getLiveSession.js
  media/video-stitcher/getSlate.js
  media/video-stitcher/listCdnKeys.js
  media/video-stitcher/listLiveAdTagDetails.js
  media/video-stitcher/listLiveConfigs.js
  media/video-stitcher/listSlates.js
  media/video-stitcher/updateCdnKey.js
  media/video-stitcher/updateCdnKeyAkamai.js
  media/video-stitcher/updateSlate.js
Labels: samples, api: mediatranslation

#3728 feat: Added samples for secrets with labels
  secret-manager/createSecretWithLabels.js
  secret-manager/createUpdateSecretLabel.js
  secret-manager/deleteSecretLabel.js
  secret-manager/test/secretmanager.test.js
  secret-manager/viewSecretLabels.js
Labels: api: secretmanager, samples

#3729 feat: added samples for regional SM
  secret-manager/package.json
  secret-manager/regional_samples/accessRegionalSecretVersion.js
  secret-manager/regional_samples/addRegionalSecretVersion.js
  secret-manager/regional_samples/createRegionalSecret.js
  secret-manager/regional_samples/deleteRegionalSecret.js
  secret-manager/regional_samples/destroyRegionalSecretVersion.js
  secret-manager/regional_samples/disableRegionalSecretVersion.js
  secret-manager/regional_samples/enableRegionalSecretVersion.js
  secret-manager/regional_samples/getRegionalSecret.js
  secret-manager/regional_samples/getRegionalSecretVersion.js
  secret-manager/regional_samples/iamGrantAccessWithRegionalSecret.js
  secret-manager/regional_samples/iamRevokeAccessWithRegionalSecret.js
  secret-manager/regional_samples/listRegionalSecretVersions.js
  secret-manager/regional_samples/listRegionalSecrets.js
  secret-manager/regional_samples/regionalQuickstart.js
  secret-manager/regional_samples/updateRegionalSecret.js
  secret-manager/regional_samples/updateRegionalSecretWithAlias.js
  secret-manager/test/secretmanager.test.js
Labels: api: secretmanager, samples
