Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-10, with the labels that each got.

#3830 feat(security-center): Add Resource v2 API Mute Rule Samples
  security-center/snippets/package.json
  security-center/snippets/system-test/v2/muterule.test.js
  security-center/snippets/system-test/v2/notifications.test.js
  security-center/snippets/v2/createMuteRule.js
  security-center/snippets/v2/deleteMuteRule.js
  security-center/snippets/v2/getMuteRule.js
  security-center/snippets/v2/listAllMuteRules.js
  security-center/snippets/v2/updateMuteRule.js
Labels: api: securitycenter, samples, api: workflows

#3868 improvement: Refactor for compute samples and their tests
  compute/disks/createComputeHyperdisk.js
  compute/disks/createComputeHyperdiskFromPool.js
  compute/disks/createComputeHyperdiskPool.js
  compute/reservations/createReservationFromProperties.js
  compute/reservations/createReservationInstanceTemplate.js
  compute/reservations/deleteReservation.js
  compute/reservations/getReservation.js
  compute/reservations/reservationVmsUpdate.js
  compute/test/createComputeHyperdisk.test.js
  compute/test/createComputeHyperdiskFromPool.test.js
  compute/test/createReservationGlobalInstanceTemplate.test.js
  compute/test/createReservationRegionalInstanceTemplate.test.js
  compute/test/reservations.test.js
Labels: api: compute, samples

#3892 docs: update contributing guide
  CONTRIBUTING.md
Labels: samples

#3835 feat(security-center): Add Resource v2 API Security Marks Samples
  security-center/snippets/system-test/v2/securityMarks.test.js
  security-center/snippets/v2/addFindingSecurityMarks.js
  security-center/snippets/v2/deleteAndUpdateSecurityMarks.js
  security-center/snippets/v2/deleteSecurityMarks.js
  security-center/snippets/v2/listFindingsWithSecurityMarks.js
Labels: api: securitycenter, samples

#3874 feat: add inpainting and outpainting samples and tests
  ai-platform/snippets/imagen-edit-image-inpainting-insert-mask.js
  ai-platform/snippets/imagen-edit-image-inpainting-remove-mask.js
  ai-platform/snippets/imagen-edit-image-mask-free.js
  ai-platform/snippets/imagen-edit-image-outpainting-mask.js
  ai-platform/snippets/imagen-generate-image.js
  ai-platform/snippets/package.json
  ai-platform/snippets/resources/cat.png
  ai-platform/snippets/resources/roller_skaters.png
  ai-platform/snippets/resources/roller_skaters_mask.png
  ai-platform/snippets/resources/volleyball_game.png
  ai-platform/snippets/resources/volleyball_game_inpainting_remove_mask.png
  ai-platform/snippets/resources/woman.png
  ai-platform/snippets/resources/woman_inpainting_insert_mask.png
  ai-platform/snippets/test/imagen.test.js
  ai-platform/snippets/test/imagen/generateImage.test.js
Labels: samples, api: aiplatform

#3877 feat: consume reservations samples
  compute/reservations/createInstanceToConsumeAnyReservation.js
  compute/reservations/createInstanceToConsumeSingleProjectReservation.js
  compute/reservations/createInstanceToNotConsumeReservation.js
  compute/reservations/createReservationFromProperties.js
  compute/reservations/createReservationInstanceTemplate.js
  compute/reservations/createTemplateToNotConsumeReservation.js
  compute/test/consumeReservations.test.js
  compute/test/reservations.test.js
  compute/test/util.js
Labels: api: compute, samples

#3847 feat(security-center): Adding SCC's BigQueryExport resource
  security-center/snippets/package.json
  security-center/snippets/system-test/v2/bigQueryExport.test.js
  security-center/snippets/system-test/v2/notifications.test.js
  security-center/snippets/v2/createBigQueryExport.js
  security-center/snippets/v2/deleteBigQueryExport.js
  security-center/snippets/v2/deleteSecurityMarks.js
  security-center/snippets/v2/getBigQueryExport.js
  security-center/snippets/v2/listAllBigQueryExports.js
  security-center/snippets/v2/updateBigQueryExport.js
Labels: api: bigquery, samples

#3895 feat: add Imagen samples and tests for getting image captions, respon…
  ai-platform/snippets/imagen-get-short-form-image-captions.js
  ai-platform/snippets/imagen-get-short-form-image-responses.js
  ai-platform/snippets/imagen-verify-image-watermark.js
  ai-platform/snippets/resources/dog_newspaper.png
  ai-platform/snippets/test/imagen.test.js
Labels: samples, api: aiplatform

#3833 feat: add compute_regional_template_create/get/delete
  compute/create-instance-templates/createRegionalTemplate.js
  compute/create-instance-templates/deleteRegionalTemplate.js
  compute/create-instance-templates/getRegionalTemplate.js
  compute/test/regionalTemplate.test.js
Labels: api: compute, samples

#3826 improvement: extend compute_hyperdisk_pool_create
  compute/disks/createComputeHyperdiskPool.js
Labels: api: compute, samples

#3901 chore: Update gemma2PredictGpu.js
  ai-platform/snippets/gemma2PredictGpu.js
Labels: samples, api: aiplatform

#3896 feat: add annotations samples for regional SM
  secret-manager/regional_samples/createRegionalSecretWithAnnotations.js
  secret-manager/regional_samples/editRegionalSecretAnnotations.js
  secret-manager/regional_samples/viewRegionalSecretAnnotations.js
  secret-manager/test/secretmanager.test.js
Labels: kokoro:run, api: secretmanager, samples

#3825 feat(secretmanager): add samples for secret annotations and regional labels
  secret-manager/createSecretWithAnnotations.js
  secret-manager/editSecretAnnotations.js
  secret-manager/regional_samples/createRegionalSecretWithLabels.js
  secret-manager/regional_samples/deleteRegionalSecretLabel.js
  secret-manager/regional_samples/editRegionalSecretLabel.js
  secret-manager/regional_samples/viewRegionalSecretLabels.js
  secret-manager/test/secretmanager.test.js
  secret-manager/viewSecretAnnotations.js
Labels: api: secretmanager, samples

#3905 feat(genai): add Gemini batch prediction samples
  ai-platform/snippets/batch-prediction/batch-predict-bq.js
  ai-platform/snippets/batch-prediction/batch-predict-gcs.js
  ai-platform/snippets/test/batch-prediction-gemini.test.js
Labels: samples, api: aiplatform

#3909 fix(functions): remove invalid parameter for gcloud functions
  functions/pubsub/publish/index.js
Labels: api: cloudfunctions, samples, asset: pattern

#3910 fix: Getting embeddings using text-embedding-005.
  ai-platform/snippets/embedding-model-tuning.js
  ai-platform/snippets/predict-text-embeddings-preview.js
  ai-platform/snippets/predict-text-embeddings.js
Labels: samples, api: aiplatform
