Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-11, with the labels that each got.

#3915 fix: Use USER and ASSISTANT in functionCallingStreamContent.js
  generative-ai/snippets/function-calling/functionCallingStreamContent.js
Labels: samples, api: genai

#3872 feat: testing isolation
  .github/cloud-samples-tools/.gitignore
  .github/cloud-samples-tools/README.md
  .github/cloud-samples-tools/cmd/main.go
  .github/cloud-samples-tools/go.mod
  .github/cloud-samples-tools/pkg/config/config.go
  .github/cloud-samples-tools/pkg/config/config_test.go
  .github/cloud-samples-tools/pkg/config/testdata/config/comments.jsonc
  .github/cloud-samples-tools/pkg/config/testdata/config/default-values.json
  .github/cloud-samples-tools/pkg/config/testdata/config/empty.json
  .github/cloud-samples-tools/pkg/config/testdata/my-package/package.json
  .github/cloud-samples-tools/pkg/config/testdata/my-package/subpackage/package.json
  .github/cloud-samples-tools/pkg/config/utils.go
  .github/config/nodejs.jsonc
  .github/scripts/nodejs-test.sh
  .github/workflows/cloud-samples-tools-test.yaml
  .github/workflows/experimental.yaml
  Makefile
Labels: api: language, samples, api: workflows

#3921 Update README.md to reflect Cloud Run functions rebrand
  functions/README.md
Labels: api: cloudfunctions, samples, asset: pattern

#3923 fix(generative-ai): Fix field names
  generative-ai/snippets/gemini-pdf.js
Labels: samples, api: genai
