Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-02, with the labels that each got.

#3619 fix(docs): Set the assessment.event.expected_action when sending a CreateAssessm…
  recaptcha_enterprise/demosite/app/controllers/controller.js
  recaptcha_enterprise/demosite/app/recaptcha/createAssessment.js
Labels: api: recaptchaenterprise, samples, asset: flagship

#3616 feat: re-add GenAI embedding code samples
  ai-platform/snippets/predict-image-from-image-and-text.js
  ai-platform/snippets/predict-image-from-text.js
  ai-platform/snippets/test/predict-image-from-image-and-text.test.js
  ai-platform/snippets/test/predict-image-from-text.test.js
Labels: samples, api: aiplatform

#3624 fix(run-helloworld): updating type in package.docs.json
  run/helloworld/package.docs.json
Labels: api: run, samples, asset: pattern

#3626 fix(aiplatform): update Gemini model names
  generative-ai/snippets/countTokens.js
  generative-ai/snippets/functionCallingStreamChat.js
  generative-ai/snippets/functionCallingStreamContent.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
  generative-ai/snippets/test/countTokens.test.js
  generative-ai/snippets/test/functionCallingStreamChat.test.js
  generative-ai/snippets/test/functionCallingStreamContent.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/nonStreamingMultipartContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
  generative-ai/snippets/test/streamMultipartContent.test.js
Labels: samples, api: aiplatform, api: genai

#3596 fix: updating genai tests to run on same gcp project as ai platform samples
  generative-ai/snippets/test/countTokens.test.js
  generative-ai/snippets/test/functionCallingStreamChat.test.js
  generative-ai/snippets/test/functionCallingStreamContent.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/nonStreamingMultipartContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
  generative-ai/snippets/test/streamMultipartContent.test.js
Labels: samples, actions:force-run, api: genai
