Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-09, with the labels that each got.

#3808 fix: compute_hyperdisk_create_from_pool
  compute/disks/createComputeHyperdiskFromPool.js
  compute/disks/createComputeHyperdiskPool.js
  compute/test/createComputeHyperdiskFromPool.test.js
  compute/test/createComputeHyperdiskPool.test.js
Labels: api: compute, samples

#3807 feat: compute reservation create
  compute/disks/createComputeHyperdiskFromPool.js
  compute/disks/createComputeHyperdiskPool.js
  compute/reservations/createReservationFromProperties.js
  compute/test/createComputeHyperdiskFromPool.test.js
  compute/test/createReservationFromProperties.test.js
Labels: api: compute, samples

#3834 feat: add compute_reservations_delete/get/list
  compute/reservations/createReservationFromProperties.js
  compute/reservations/deleteReservation.js
  compute/reservations/getReservation.js
  compute/reservations/getReservations.js
  compute/test/reservations.test.js
Labels: api: compute, samples

#3811 feat: compute_reservation_create_template
  compute/reservations/createReservationInstanceTemplate.js
  compute/test/createReservationGlobalInstanceTemplate.test.js
  compute/test/createReservationRegionalInstanceTemplate.test.js
  compute/test/reservations.test.js
Labels: api: compute, samples

#3848 fix: update deprecated notificationConfig in healthcare API
  healthcare/fhir/patchFhirStore.js
Labels: samples, api: healhcare

#3844 feat: modify reservation
  compute/reservations/reservationVmsUpdate.js
Labels: api: compute, samples

#3853 chore(run/websockets): temporarily disable run/websockets on kokoro
  run/websockets/package.json
Labels: api: run, samples, asset: pattern

#3865 chore: Remove torus-dpe team from blunderbuss routing
  .github/blunderbuss.yml
Labels: samples

#3861 feat: add a generate image sample and test for Imagen
  ai-platform/snippets/imagen/generateImage.js
  ai-platform/snippets/package.json
  ai-platform/snippets/test/imagen/generateImage.test.js
Labels: samples, api: aiplatform

#3870 chore(CODEOWNERS): Add cloud-samples-infra as a repo config owner
  CODEOWNERS
Labels: automerge, samples

#3881 chore(blunderbuss): Update configuration to remove unused teams
  .github/blunderbuss.yml
Labels: samples

#3880 chore(CODEOWNERS): Remove unused teams
  CODEOWNERS
Labels: samples

#3878 improvement: generativeaionvertexai_gemini_safety_settings and generativeaionvertexai_gemini_token_count
  generative-ai/snippets/count-tokens/countTokens.js
  generative-ai/snippets/safetySettings.js
Labels: samples, api: genai

#3869 feat: gemma2 models samples
  ai-platform/snippets/gemma2PredictGpu.js
  ai-platform/snippets/gemma2PredictTpu.js
  ai-platform/snippets/test/gemma2Prediction.test.js
Labels: samples, aiplatform

#3822 build: disable test log reporting to flaky-bot
  .github/workflows/flakybot.yaml
  .kokoro/build-with-appengine.sh
  .kokoro/build-with-run.sh
  .kokoro/build.sh
Labels: samples, api: workflows

#3885 test: disable stop billing test
  functions/billing/test/index.test.js
Labels: api: cloudfunctions, samples, asset: pattern

#3883 chore(security-center): update workflow security center path (include v2)
  .github/workflows/security-center-snippets.yaml
Labels: api: securitycenter, samples

#3886 fix: typo in gemma2 samples
  ai-platform/snippets/test/gemma2Prediction.test.js
Labels: samples, api: aiplatform

#3884 feat: batch prediction samples
  ai-platform/snippets/batch-code-predict.js
  ai-platform/snippets/batch-text-predict.js
  ai-platform/snippets/test/batch-code-predict.test.js
  ai-platform/snippets/test/batch-text-predict.test.js
Labels: samples, api: aiplatform
