Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-04, with the labels that each got.

#3651 feat: Text-Embedding Model Tuning demo.
  ai-platform/snippets/embedding-model-tuning.js
  ai-platform/snippets/test/embedding-model-tuning.test.js
Labels: samples, api: aiplatform

#3652 fix: Typos in samples for tuning text embedding models.
  ai-platform/snippets/embedding-model-tuning.js
  ai-platform/snippets/test/embedding-model-tuning.test.js
Labels: samples, api: aiplatform

#3654 chore: cleanup README.md
  README.md
Labels: samples

#3655 chore: use Cloud SQL Proxy v2 in README
  cloud-sql/mysql/mysql/README.md
  cloud-sql/mysql/mysql2/README.md
  cloud-sql/postgres/knex/README.md
  cloud-sql/sqlserver/mssql/README.md
  cloud-sql/sqlserver/tedious/README.md
Labels: api: cloudsql, samples, asset: pattern

#3656 fix: don't have auto-updates running on app engine flex samples
  renovate.json
Labels: samples

#3617 fix: Updating the node environment to Node.js 20
  .github/workflows/appengine-twilio.yaml
  .github/workflows/utils/workflows.json
  appengine/building-an-app/build/app.yaml
  appengine/building-an-app/build/package.json
  appengine/building-an-app/build/server.js
  appengine/building-an-app/build/test/server.test.js
  appengine/building-an-app/update/app.yaml
  appengine/building-an-app/update/package.json
  appengine/building-an-app/update/server.js
  appengine/building-an-app/update/test/server.test.js
  appengine/twilio/README.md
  appengine/twilio/app.flexible.yaml
  appengine/twilio/app.js
  appengine/twilio/app.standard.yaml
  appengine/twilio/package.json
  appengine/twilio/test/app.test.js
Labels: api: appengine, samples, asset: pattern

#3657 chore: Update runtimes for App Engine standard
  appengine/analytics/app.standard.yaml
  appengine/datastore/app.standard.yaml
  appengine/hello-world/standard/app.yaml
  appengine/memcached/app.standard.yaml
  appengine/metadata/standard/app.yaml
  appengine/pubsub/app.standard.yaml
  appengine/static-files/app.standard.yaml
  appengine/storage/standard/app.yaml
Labels: automerge, api: appengine, samples, asset: pattern

#3658 fix: resolve WARNs and Update version of Node.js used
  run/helloworld/Dockerfile
Labels: api: run, samples, asset: pattern

#3659 chore: update Dockerfiles to use modern images
  cloud-sql/mysql/mysql/Dockerfile
  cloud-sql/mysql/mysql2/Dockerfile
  cloud-sql/postgres/knex/Dockerfile
  cloud-sql/sqlserver/mssql/Dockerfile
  cloud-sql/sqlserver/tedious/Dockerfile
  cloud-tasks/snippets/Dockerfile
  eventarc/audit-storage/Dockerfile
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
  memorystore/redis/cloud_run_deployment/Dockerfile
  run/hello-broken/Dockerfile
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/pubsub/Dockerfile
Labels: api: cloudsql, api: run, api: tasks, samples, api: eventarc, api: memorystore, asset: pattern

#3660 chore: remove community samples from README.md
  appengine/README.md
Labels: automerge

#3661 feat(generative-ai): Add audio summarization sample for Gemini 1.5
  .github/workflows/generative-ai-snippets.yaml
  generative-ai/snippets/gemini-audio-summarization.js
  generative-ai/snippets/test/gemini-audio-summarization.test.js
Labels: samples, api: genai

#3666 feat(generative-ai): Add system instruction sample for Gemini 1.5
  generative-ai/snippets/gemini-system-instruction.js
  generative-ai/snippets/test/gemini-system-instruction.test.js
Labels: samples, api: genai

#3663 feat(generative-ai): Add video with audio sample for Gemini 1.5
  generative-ai/snippets/gemini-video-audio.js
  generative-ai/snippets/test/gemini-video-audio.test.js
Labels: samples, api: genai

#3664 feat(generative-ai): Add all modalities sample for Gemini 1.5
  generative-ai/snippets/gemini-all-modalities.js
  generative-ai/snippets/test/gemini-all-modalities.test.js
Labels: samples, api: genai

#3665 feat(generative-ai): Add PDF sample for Gemini 1.5
  generative-ai/snippets/gemini-pdf.js
  generative-ai/snippets/test/gemini-pdf.test.js
Labels: samples, api: genai

#3667 fix(generative-ai): Fix integration test errors
  generative-ai/snippets/functionCallingStreamContent.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/test/functionCallingStreamContent.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/safetySettings.test.js
Labels: samples, actions:force-run, api: genai
