Repository GoogleCloudPlatform/nodejs-docs-samples, pull requests merged in 2024-05, with the labels that each got.

#3669 fix: remove unused error concepts function snippets
  functions/helloworld/helloError/index.js
  functions/helloworld/helloError/test/index.test.js
Labels: api: cloudfunctions, samples, asset: pattern

#3668 fix: remove unused game-servers snippets
  .github/auto-label.yaml
  .github/workflows/game-servers-snippets.yaml
  .github/workflows/utils/workflows.json
  game-servers/snippets/create_cluster.js
  game-servers/snippets/create_config.js
  game-servers/snippets/create_deployment.js
  game-servers/snippets/create_realm.js
  game-servers/snippets/delete_cluster.js
  game-servers/snippets/delete_config.js
  game-servers/snippets/delete_deployment.js
  game-servers/snippets/delete_realm.js
  game-servers/snippets/get_cluster.js
  game-servers/snippets/get_config.js
  game-servers/snippets/get_deployment.js
  game-servers/snippets/get_realm.js
  game-servers/snippets/get_rollout.js
  game-servers/snippets/list_clusters.js
  game-servers/snippets/list_configs.js
  game-servers/snippets/list_deployments.js
  game-servers/snippets/list_realms.js
  game-servers/snippets/package.json
  game-servers/snippets/quickstart.js
  game-servers/snippets/test/clean.js
  game-servers/snippets/test/create_cluster.test.js
  game-servers/snippets/test/create_realm.test.js
  game-servers/snippets/test/crud_config.test.js
  game-servers/snippets/test/crud_deployment.test.js
  game-servers/snippets/test/delete_cluster.test.js
  game-servers/snippets/test/delete_realm.test.js
  game-servers/snippets/test/get_cluster.test.js
  game-servers/snippets/test/get_realm.test.js
  game-servers/snippets/test/list_clusters.test.js
  game-servers/snippets/test/list_realms.test.js
  game-servers/snippets/test/quickstart.js
  game-servers/snippets/test/quickstart.test.js
  game-servers/snippets/test/rollout.js
  game-servers/snippets/test/update_cluster_test.js
  game-servers/snippets/test/update_realm_test.js
  game-servers/snippets/update_cluster.js
  game-servers/snippets/update_deployment.js
  game-servers/snippets/update_realm.js
  game-servers/snippets/update_rollout_default.js
  game-servers/snippets/update_rollout_override.js
  game-servers/snippets/update_rollout_remove_default.js
  game-servers/snippets/update_rollout_remove_override.js
Labels: api: gameservices, samples, api: workflows

#3674 Update Gemini model versions
  generative-ai/snippets/countTokens.js
  generative-ai/snippets/functionCallingStreamChat.js
  generative-ai/snippets/functionCallingStreamContent.js
  generative-ai/snippets/inference/nonStreamTextBasic.js
  generative-ai/snippets/inference/streamTextBasic.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/nonStreamingMultipartContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/sendMultiModalPromptWithImage.js
  generative-ai/snippets/sendMultiModalPromptWithVideo.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/streamMultipartContent.js
  generative-ai/snippets/test/countTokens.test.js
  generative-ai/snippets/test/functionCallingStreamContent.test.js
  generative-ai/snippets/test/inference/nonStreamTextBasic.test.js
  generative-ai/snippets/test/inference/streamTextBasic.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/nonStreamingMultipartContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
  generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
  generative-ai/snippets/test/streamMultipartContent.test.js
Labels: samples, api: genai

#3676 chore(fixit): remove redundant region tags
  run/hello-broken/index.js
  run/idp-sql/secrets.js
  run/image-processing/app.js
  run/image-processing/image.js
  run/image-processing/index.js
  run/logging-manual/app.js
  run/pubsub/app.js
  run/pubsub/index.js
Labels: api: run, samples, asset: pattern

#3680 fix: complete licence headers
  cloud-sql/mysql/mysql/Dockerfile
  cloud-sql/mysql/mysql2/Dockerfile
  cloud-sql/postgres/knex/Dockerfile
  run/idp-sql/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/logging-manual/index.js
  run/pubsub/Dockerfile
Labels: api: cloudsql, api: run, samples, asset: pattern

#3679 fix: remove redundant run_ tags (fixit)
  functions/tips/lazyGlobals/index.js
  functions/tips/scopeDemo/index.js
  functions/tips/scopeDemo/test/index.test.js
  run/helloworld/index.js
  run/idp-sql/cloud-sql.js
  run/idp-sql/middleware.js
  run/idp-sql/static/config.js
  run/idp-sql/static/firebase.js
  run/markdown-preview/editor/app.js
  run/markdown-preview/editor/render.js
  run/system-package/app.js
Labels: automerge, api: cloudfunctions, api: run, samples, asset: pattern

#3683 chore: update to gemini ga calls
  generative-ai/snippets/functionCallingStreamChat.js
  generative-ai/snippets/functionCallingStreamContent.js
Labels: samples, api: genai

#3673 feat(generative-ai): Add function calling snippets
  generative-ai/snippets/function-calling/functionCallingAdvanced.js
  generative-ai/snippets/function-calling/functionCallingBasic.js
  generative-ai/snippets/function-calling/functionCallingStreamChat.js
  generative-ai/snippets/function-calling/functionCallingStreamContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/test/function-calling/functionCallingAdvanced.test.js
  generative-ai/snippets/test/function-calling/functionCallingBasic.test.js
  generative-ai/snippets/test/function-calling/functionCallingStreamChat.test.js
  generative-ai/snippets/test/function-calling/functionCallingStreamContent.test.js
Labels: samples, api: genai

#3687 fix: update Gemini model version for safety settings sample
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/test/safetySettings.test.js
Labels: samples, api: genai

#3685 feat: add gemini code sample and test for text-only input
  generative-ai/snippets/gemini-text-input.js
  generative-ai/snippets/test/gemini-text-input.test.js
Labels: samples, api: genai

#3686 feat: Add new token counting sample
  generative-ai/snippets/count-tokens/countTokens.js
  generative-ai/snippets/count-tokens/countTokensAdvanced.js
  generative-ai/snippets/test/count-tokens/countTokens.test.js
  generative-ai/snippets/test/count-tokens/countTokensAdvanced.test.js
Labels: samples, api: genai

#3690 feat: update text-only input sample to use a generic review
  generative-ai/snippets/gemini-text-input.js
Labels: samples, api: genai

#3692 feat: Add new samples for VertexAI Gemini grounding
  .github/workflows/generative-ai-snippets.yaml
  generative-ai/snippets/grounding/groundingPrivateDataBasic.js
  generative-ai/snippets/grounding/groundingPublicDataBasic.js
  generative-ai/snippets/test/grounding/groundingPrivateDataBasic.test.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
Labels: samples, api: genai

#3697 fix: remove unused region tags
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
Labels: samples, api: eventarc, asset: pattern

#3696 feat: refactor text-only Gemini prompt
  generative-ai/snippets/gemini-text-input.js
  generative-ai/snippets/test/gemini-text-input.test.js
Labels: samples, api: genai

#3701 feat: Make embedding tuning sample reference new v1.1.3 tuning pipeline
  ai-platform/snippets/embedding-model-tuning.js
Labels: samples, api: aiplatform

#3704 fix: Use Alphabet 10k sample dataset.
  ai-platform/snippets/embedding-model-tuning.js
Labels: samples, api: aiplatform

#3705 feat(vertexai): Update sample models to gemini-1.5-flash-001
  generative-ai/snippets/count-tokens/countTokens.js
  generative-ai/snippets/count-tokens/countTokensAdvanced.js
  generative-ai/snippets/function-calling/functionCallingAdvanced.js
  generative-ai/snippets/function-calling/functionCallingBasic.js
  generative-ai/snippets/function-calling/functionCallingStreamChat.js
  generative-ai/snippets/function-calling/functionCallingStreamContent.js
  generative-ai/snippets/gemini-text-input.js
  generative-ai/snippets/inference/nonStreamMultiModalityBasic.js
  generative-ai/snippets/inference/nonStreamTextBasic.js
  generative-ai/snippets/inference/streamMultiModalityBasic.js
  generative-ai/snippets/inference/streamTextBasic.js
  generative-ai/snippets/nonStreamingChat.js
  generative-ai/snippets/nonStreamingContent.js
  generative-ai/snippets/safetySettings.js
  generative-ai/snippets/streamChat.js
  generative-ai/snippets/streamContent.js
  generative-ai/snippets/test/count-tokens/countTokens.test.js
  generative-ai/snippets/test/count-tokens/countTokensAdvanced.test.js
  generative-ai/snippets/test/function-calling/functionCallingAdvanced.test.js
  generative-ai/snippets/test/function-calling/functionCallingBasic.test.js
  generative-ai/snippets/test/function-calling/functionCallingStreamChat.test.js
  generative-ai/snippets/test/function-calling/functionCallingStreamContent.test.js
  generative-ai/snippets/test/gemini-system-instruction.test.js
  generative-ai/snippets/test/grounding/groundingPrivateDataBasic.test.js
  generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
  generative-ai/snippets/test/inference/nonStreamMultiModalityBasic.test.js
  generative-ai/snippets/test/inference/nonStreamTextBasic.test.js
  generative-ai/snippets/test/inference/streamMultiModalityBasic.test.js
  generative-ai/snippets/test/inference/streamTextBasic.test.js
  generative-ai/snippets/test/nonStreamingChat.test.js
  generative-ai/snippets/test/nonStreamingContent.test.js
  generative-ai/snippets/test/safetySettings.test.js
  generative-ai/snippets/test/streamChat.test.js
  generative-ai/snippets/test/streamContent.test.js
Labels: samples, api: genai
